### ISSUE TITLE
PMC commands don't honor active solution platform during build

### ISSUE THREAD

**Issue by bricelam** [dotnet/ef6#1092]
x64 projects are now supported, however the tools don't build for the active solution platform. 

![image](https://user-images.githubusercontent.com/1226749/62065540-0f5e2a00-b1e4-11e9-8094-9bc5f4950864.png)

This can cause the assemblies to be out of date or missing.

# Workaround
You can work around this issue by manually building the project before running the commands.

**Comment by bricelam** [comment]
Note we avoided this issue on EF Core by building the entire solution, but this also isn't ideal--especially for solutions with a lot of projects.

**Comment by ajcvickers** [comment]
@bricelam How important do you think this is?

(Do we need to do a 6.3 triage?)

**Comment by bricelam** [comment]
OK to punt. It’s not new, just the last thing blocking this scenario now

**Comment by bricelam** [comment]
Yes, we should schedule a triage and punt meeting

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
