### ISSUE TITLE
Publish NuGet localization packages for 6.3

### ISSUE THREAD

**Issue by AnReZa** [dotnet/ef6#1307]
Would you please be so kind to update the NuGet package of EntityFramework.de as well? This assembly has a hard-coded dependency on EntityFramework 6.2.0. Without the update, German devs cannot use 6.3.0.

https://www.nuget.org/packages/EntityFramework.de

**Comment by bricelam** [comment]
Note to implementer: It looks like the source for these is in the internal EFBuild repo. We should port them to [Arcade](https://github.com/dotnet/arcade) and add them to this repo.

**Comment by bricelam** [comment]
@AnReZa The 6.2.0 package might actually just work:
https://github.com/aspnet/EntityFramework6/blob/2c12e7604037e4178b779a85c7236a1710c6e7df/src/SharedAssemblyVersionInfo.cs#L5

**Comment by AnReZa** [comment]
@bricelam The problem is, that NuGet doesn't allow me to update anything, because there is a hard-configured dependency for version 6.2.0. Visit the link in my actual post and expand the "Dependencies" area. There you can find one single entry, which states _EntityFramework (= 6.2.0)._ You should probably consider opening up those dependencies, if possible. Maybe, the correct entry would be ">=6.0.0" or ">=6.2.0" in this case.

**Comment by Ghetti** [comment]
Same problem for https://www.nuget.org/packages/EntityFramework.it

**Comment by AnReZa** [comment]
Any news on this topic? The problem still persists, even for the latest version 6.4.4.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
