### ISSUE TITLE
LocalDbConnectionFactory used in tools no matter what on .NET Core

### ISSUE THREAD

**Issue by onionhammer** [dotnet/ef6#1342]
Using new csproj format with dotnet core 3.0, whenever I run `update-database` it creates a database in localdb rather than using the SqlConnectionFactory and connection string provided in app.config

```xml<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="Data Source=.;Initial Catalog=MyDb;User Id=sa;Password=SuperSecretPassword!" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <connectionStrings>
    <clear />
    <add name="DataContext" providerName="System.Data.SqlClient" connectionString="Data Source=.;Initial Catalog=MyDb;User Id=sa;Password=SuperSecretPassword!" />
  </connectionStrings>
</configuration>

```

### Steps to reproduce
- Create a new classlib referencing netcoreapp3.0
- Add EntityFramework 6.3 as a package reference
- Add a class extending DbContext
- Update app.config (see above)
- Run `enable-migrations`
- Run `update-database -Verbose`
- Check this repo for reference: https://github.com/onionhammer/repro-ef6

Notice database is added to localdb not (.) (say a docker forwarding port 1433); the app.config is completely ignored

- Operating system: Windows 10

**Comment by ajcvickers** [comment]
@bricelam Would we expect an `app.config` in a `netcoreapp3.0` class library to be picked up? More generally, do we have docs (or issues tracking docs) to help understand `app.config` in .NET Core?

**Comment by bricelam** [comment]
It should work. Using app.config with tests is nearly impossible though. See https://github.com/aspnet/EntityFramework.Docs/issues/1784

**Comment by bricelam** [comment]
Basically, if you can get `ConfigurationManager.ConnectionStrings` to work, EF6 should be able to read the config file too

**Comment by onionhammer** [comment]
If app.config doesnt work, there should be a working, documented, alternative

**Comment by chris-sung** [comment]
I second to this

**Comment by ajcvickers** [comment]
@bricelam Assigning to you to investigate. From my testing, everything is working when the code is executed in the normal way, but it's not getting picked up by the migrations commands.

**Comment by bricelam** [comment]
Blocked by dotnet/corefx#32095
