### ISSUE TITLE
Wiki roadmap is not up to date

### ISSUE THREAD

**Issue by mario-mestrovic** [dotnet/ef6#1476]
Hi everybody. I just wanted to point out that the GitHub Wiki section is not up to date. I went there to see the roadmap because I wanted to know when can we expect 6.4.0 release.
The wiki still shows that 6.3 is still in planning but it got released some time ago.

**Comment by bairog** [comment]
@ajcvickers @bricelam What is current state of EF6? 
Is this version still supported (6.4.4 is 8 months old)? 
Roadmap is outdated - are there any plans for EF 6.5?

P. S. Switching to EF Core 5 is not an option for now because Entity Splitting [still not supported](https://github.com/dotnet/efcore/issues/620)

**Comment by ajcvickers** [comment]
@bairog EF6 is still supported. We don't currently have plans for a 6.5 release.

**Comment by bairog** [comment]
> We don't currently have plans for a 6.5 release.
@ajcvickers What exactly do you mean? EF6 is not planned to have new features? Only fixes for critical bugs and security patches?
EF Core consistently releases new version every year. And it is declared to be faster in performance than EF6.
So what are your (and Microsoft) recomendations for new software: continue with EF6 or move to EF Core when it is possible (even EF Core 5 still lack all EF6 features - for example [Entity Splitting support](https://github.com/dotnet/efcore/issues/620))

**Comment by ajcvickers** [comment]
@bairog https://docs.microsoft.com/en-us/ef/efcore-and-ef6/#guidance-for-new-applications

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
