### ISSUE TITLE
ConnectRetryCount causes 10 second hangs on common EF tasks

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/ef6#148]
SQLClient now has a 10 second pause when attempting to connect to a database that does not exist. This means whenever EF does exists checks on a database that does not exist the user sees this 10 second pause. For example:

```
PM> Enable-Migrations
Checking if the context targets an existing database...
...hangs for 10 seconds...
Code First Migrations enabled for project EF6M2.
PM> 
```

We could consider:
* Pushing back on SQLClient doing this by default since it effectively regresses EF, and probably also external customers doing similar things.
* Changing the default connection strings that EF uses to have ConnectRetryCount=0.

**Comment by ErikEJ** [comment]
Beware that ConnectRetryCount is only available in .NET 4.5.1 and later

**Comment by rowanmiller** [comment]
@divega to add link to corefx issue

**Comment by divega** [comment]
This issue is blocked on having a programmatic way to set control ConnectRetryCount on SqlConnection, which is requested at https://github.com/dotnet/corefx/issues/14644.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
