### ISSUE TITLE
In derived TransactionHandler IsolationLevelGot & IsolationLevelGetting are not called

### ISSUE THREAD

**Issue by dekenless** [dotnet/ef6#1498]
If you implement and register a TransactionHandler, the IsolationLevelGot & IsolationLevelGetting  methods are not called.

I have verified the handler is instantiated and initialized, and other overridden methods are called as I would expect.

### Steps to reproduce
Implement the following and not the debug messages never are printed.

```c#
SetDefaultTransactionHandler(() => new DefaultTransactionHandler());
```

```c#
public class DefaultTransactionHandler : TransactionHandler
    {
        public override string BuildDatabaseInitializationScript()
        {
            throw new NotImplementedException();
        }

        public override void IsolationLevelGot(DbTransaction transaction, DbTransactionInterceptionContext<IsolationLevel> interceptionContext)
        {
            Debug.WriteLine($"DefaultTransactionHandler: IsolationLevelGot: {interceptionContext?.OriginalResult}");
            base.IsolationLevelGot(transaction, interceptionContext);
        }
        public override void IsolationLevelGetting(DbTransaction transaction, DbTransactionInterceptionContext<IsolationLevel> interceptionContext)
        {
            Debug.WriteLine($"DefaultTransactionHandler: IsolationLevelGetting: {interceptionContext?.OriginalResult}");
            interceptionContext.Result = IsolationLevel.Snapshot;
            base.IsolationLevelGetting(transaction, interceptionContext);
        }
    }
```

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9

**Comment by ajcvickers** [comment]
@dekenless Is anything setting the isolation level? If so, where and how?

**Comment by dekenless** [comment]
No, I was trying to set it there, but as mentioned these overridden methods are never called.

**Comment by ajcvickers** [comment]
@dekenless This would only work if EF was actually setting the IslolationLevel, which I don't think it does.

**Comment by dekenless** [comment]
If EF is not using these methods, who is? What approach could be used to override the default isolation level used when EF issues a BeginTransaction?

**Comment by ajcvickers** [comment]
@dekenless It's been a while so my memory is sketchy here, but I would imagine by setting it in `BeganTransaction`.

**Comment by dekenless** [comment]
Yes that can be done, however, for all the implicit transactions EF initiates there seemingly is no way to set the default isolation level. The ability to do this would simplify code, and also make using the retry for resilient connections cleaner since user initiated transactions are [not supported](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/retry-logic) out-of-the-box. 

Creating a user transaction seems unnecessary when EF already is wrapping most operations in a transaction--all I want is the ability to specify the isolation level. One would think that the aforementioned methods would be called when EF is determining the isolation level.

**Comment by ajcvickers** [comment]
@dekenless I think you're assuming EF is doing more than it is doing here. I believe EF is just using the connection. The isolation level is handled by the SQLClient layer.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
