### ISSUE TITLE
StringLength / MaxLength ignored by migrations for some columns

### ISSUE THREAD

**Issue by RichardD2** [dotnet/ef6#1499]
I've managed to completely confuse EF 6.3.0 migrations by adding a reference to a .NET Standard project. As a result, both `StringLength` and `MaxLength` attributes are ignored for certain columns when adding a migration, and my "Seed" method throws an `AutomaticMigrationsDisabledException` after the latest migration has been applied.

### Steps to reproduce
I can reproduce this in a single solution with three projects:

#### 1. CustomAnnotations
A .NET Standard 2.0 class library.

Package reference to `System.ComponentModel.Annotations` v4.5.0. 

```c#
using System;
using System.ComponentModel.DataAnnotations;

namespace CustomAnnotations
{
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class DummyValidationAttribute : ValidationAttribute
    {
    }
}
```

#### 2. Entities
An SDK-style project targeting .NET Framework 4.7.2.

Package reference to `System.ComponentModel.Annotations` v4.5.0. 
Package reference to `EntityFramework` v6.3.0. 
Project reference to `CustomAnnotations`.

```c#
using System;
using System.ComponentModel.DataAnnotations;
using CustomAnnotations;

namespace Entities
{
    public class TestEntity    
    {
        public int Id { get; set; }

        [StringLength(20)]
        public string Name { get; set; }

        [StringLength(100), DummyValidation]
        public string Expression { get; set; }
    }
}
```

#### 3. EntityFrameworkStringLengthTest
A console application targeting .NET Framework 4.7.2, set as the startup project.

Assembly reference to `System.ComponentModel.DataAnnotations`.
Package reference to `EntityFramework` v6.3.0. 
Project reference to `Entities`.

```c#
using System;
using System.Data.Entity;
using Entities;

namespace EntityFrameworkStringLengthTest
{
    public class TestContext : DbContext
    {
        public DbSet<TestEntity> TestEntities => Set<TestEntity>();
    }
}
```

#### Migration
Run `enable-migrations`, then `add-migration Initial`.

#### Expected results
The migration should set the string length for both columns.

#### Actual results
The migration sets the string length for the `Name` column, but not the `Expression` column.

```c#
CreateTable(
    "dbo.TestEntities",
    c => new
        {
            Id = c.Int(nullable: false, identity: true),
            Name = c.String(maxLength: 20),
            Expression = c.String(),
        })
    .PrimaryKey(t => t.Id);
```

It seems that the length is dropped for any property decorated with an attribute from the .NET Standard library.

This is not due to the project reference; my real project references the .NET Standard library using a package reference to our private NuGet feed.

Replacing `StringLength` with `MaxLength` makes no difference.

The only way I have been able to get the column lengths to apply is to explicitly set it using the fluent API.

### Further technical details
**EF version:** 6.3.0
**Database Provider:** Any
**Operating system:** Windows 10 1909
**IDE:** Visual Studio 2019 16.3.10

[EntityFrameworkStringLengthTest.zip](https://github.com/aspnet/EntityFramework6/files/3905160/EntityFrameworkStringLengthTest.zip)

**Comment by RichardD2** [comment]
This is still happening with v6.4.0 of `EntityFramework` and v4.7.0 of `System.ComponentModels.DataAnnotations`.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
