### ISSUE TITLE
Unwanted Namespace in TT Files

### ISSUE THREAD

**Issue by SoulFireMage** [dotnet/ef6#1510]
Prior to version 6.2, the TT file did not generate code with additional namespace entries.

However now it does. To correct the problem I manually edit both the [Entities].Context.tt file and the [Entities.tt file and perform a find/replace on two strings:

Namespace <#=code.EscapeNamespace(codeNamespace)#>
To
'Namespace <#=code.EscapeNamespace(codeNamespace)#>

End Namespace
To:
'End Namespace`

This fixes the problem for this project. As I do a lot of work in the TT file to generate methods etc, this is not a big issue for me (We are a database first outfit). However for many others this may be a bit of an unnecessary nuisance.

I've never contributed back into an open source project before, so I was reluctant to submit such a trivial change myself. However, is this something I should consider putting up here - solving the problem myself for others or am I better leaving it to project leaders? :)

Note this is in VB, I've not tried in C#!

**Comment by ajcvickers** [comment]
@bricelam Do you think this is likely to only be an issue in VB? Or might it affect C# projects too?

**Comment by SoulFireMage** [comment]
I've not tried yet. But I suspect it would.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
