### ISSUE TITLE
The type 'DbContext' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1514]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/838864/the-type-dbcontext-is-defined-in-an-assembly-that.html)._

---
I am using VS 2019 community edition

The type 'DbContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' in Visual Studio 2019

Tried install-package EntityFramework but facing error

Install-Package : Unable to find package 'EntityFramework'

---
#### Visual Studio Feedback System on 12/1/2019, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
There isn't enough information here to be able to figure out what the error is. Are you able to install any other packages from NuGet? Can you browse NuGet packages in Visual Studio?

**Comment by benhxy** [comment]
Try to use "Manage Nuget Packages for Solution" GUI instead of console. You can also check if your package source is setup correctly.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
