### ISSUE TITLE
EF 6.4 migrations running in an ASP.NET CORE 3 app not working

### ISSUE THREAD

**Issue by slask** [dotnet/ef6#1524]
I have an ASP.NET core 3.0 app and I am running EF 6.4 on it. Queries works ok but I need to apply migrations to target DB from command line during Continuous Integration.

**What is the exact command to run for that?** I tried various options and none of them worked and the docs are just terrible on this. 

Migrations in:
EF 6.4 + .NET Full 4.x  = OK
EF Core 3.0 + .NET Core 3.0 = OK
EF 6.4 + .NET Core 3.0 = **HOW?**

Key points:
- EF 6.4 running on .NET Core 3.0, so no web.config just appsetting.json
- I need to run from command line not from Visual Studio's Package Manager Console
- in .NET Core 3 project where is no NuGet "packages" folder where do I get the ef6 CLI tool from?

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: VS2019

Others are having the same problem: https://github.com/aspnet/EntityFramework6/issues/1053#issuecomment-548010848

**Comment by phekmat** [comment]
The (unfriendly) command in the linked issue is close, but has the `--assembly` switch in the wrong place. It should go after the EF specific command (e.g. `migrations add`):
```
dotnet exec \
  --depsfile ./bin/Debug/netcoreapp3.0/MyApp.deps.json \
  --runtimeconfig ./bin/Debug/netcoreapp3.0/MyApp.runtimeconfig.json \
  ~/.nuget/packages/entityframework/6.3.0/tools/netcoreapp3.0/any/ef6.dll \
  database update
  --assembly ./bin/Debug/netcoreapp3.0/MyApp.dll \
  <other database update options>
```

The nuget package cache is in `%userprofile%\.nuget\packages` (Windows) or `~/.nuget/packages` by default.

**Comment by spacestr** [comment]
Also make sure that you run the 32bit version of 'dotnet' (ex: C:\Program Files (x86)\dotnet) if your project targets x86 architecture.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
