### ISSUE TITLE
nuget fails

### ISSUE THREAD

**Issue by Martin-Stein** [dotnet/ef6#1525]
Hi there,
updating from 6.2(German) to 6.4 gives me:

Abhängigkeiten können nicht aufgelöst werden. "EntityFramework 6.4.0' ist nicht mit 'EntityFramework.de 6.2.0 Einschränkung: EntityFramework (= 6.2.0)' kompatibel.

(dependencies can not be resolved,EntityFramework 6.4.0' is not compatible with 'EntityFramework.de 6.2.0 , restriction: EntityFramework (= 6.2.0)

kind regards,
Martin

**Comment by benhxy** [comment]
Can you check your build/project file to see if there are any references to 6.2.0 assembly?

**Comment by Martin-Stein** [comment]
Hi Ben,

 

yes, I have references to 6.2.0 assembly.

 

Kind regards,

 

Martin

 

Von: Ben Hu <notifications@github.com> 
Gesendet: Mittwoch, 8. Januar 2020 01:21
An: dotnet/ef6 <ef6@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [dotnet/ef6] nuget fails (#1525)

 

Can you check your build/project file to see if there are any references to 6.2.0 assembly?

**Comment by Telefisch** [comment]
Any Solutions yet?
I have the same Problem.

**Comment by DevilGeek** [comment]
Same problem with the EntityFramework.fr not existing for version > 6.2.0

**Comment by CGX106** [comment]
It is the same problem as "discussed" in:
https://github.com/dotnet/ef6/issues/1307

It does not matter for the dev team, I have the same problem :(.

**Comment by Martin-Stein** [comment]
I removed the german Package ,Entityframework.de, and was able to update to 6.4.4.
It looks like other languages are not longer maintained

Martin

**Comment by Telefisch** [comment]
Martin, how did you remove it?
If I want to uninstall it, I need to uninstall Microsoft.AspNet.Identity.EntityFramework.2.2.3 as well...

**Comment by Martin-Stein** [comment]
> Martin, how did you remove it?
> If I want to uninstall it, I need to uninstall Microsoft.AspNet.Identity.EntityFramework.2.2.3 as well...

When I remember correctly, I have just selected the german Nuget Pakage **EntityFramework.de** and pressed the deinstall button.

**Comment by AnReZa** [comment]
The problem still persists for the latest 6.4.4 release. Latest satellite assembly is still hard-bound to version 6.2.

**Comment by SoyYop** [comment]
Happens with Spanish version too, from 6.3 upwards.
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		No se pueden resolver las dependencias. 'EntityFramework 6.4.4' no es compatible con 'EntityFramework.es 6.2.0 restricción: EntityFramework (= 6.2.0)'.				

Any ideas?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by Zhaohijie** [comment]
在nuget已安装里面找到EntityFramework.zh-Hans，版本号为6.2.0的这个包，卸载掉，然后重新生成项目就可以了
