### ISSUE TITLE
DbGeography properties included in generated SQL queries that leverage DISTINCT, resulting in Exception

### ISSUE THREAD

**Issue by joelmdev** [dotnet/ef6#1527]
Project with minimum repro attached, but the rundown follows. Note that the query used here is NOT the one we're having trouble with- there are other LINQ to EF queries that implicitly use MSSQL's DISTINCT. In our case it's a `GroupBy()` that causes generated SQL to use DISTINCT resulting in the exception. 

With these models:

```c#
    public abstract class AbstractFoo
    {
        public int Id { get; set; }
    }


    public class DerivedFoo : AbstractFoo
    {
        public virtual Bar Bar { get; set; }
    }


    public class CoordinatesFoo : DerivedFoo
    {
        public DbGeography Coordinates { get; set; }
    }


    public class Bar
    {
        public int Id { get; set; }
        public string Property { get; set; }
        public virtual ICollection<DerivedFoo> DerivedFoos { get; set; } = new HashSet<DerivedFoo>();
    }
```

And this  EF LINQ query:

```c#
        ctx.Bars.SelectMany(bar => bar.DerivedFoos).Distinct().Take(100).ToList();
```

We get the following generated SQL:

```sql
SELECT 
    [Limit1].[Id] AS [Id], 
    [Limit1].[Discriminator] AS [Discriminator], 
    [Limit1].[Coordinates] AS [Coordinates], 
    [Limit1].[Bar_Id] AS [Bar_Id]
    FROM ( SELECT DISTINCT TOP (100) 
        [Extent2].[Id] AS [Id], 
        [Extent2].[Coordinates] AS [Coordinates], 
        [Extent2].[Discriminator] AS [Discriminator], 
        [Extent2].[Bar_Id] AS [Bar_Id]
        FROM  [dbo].[Bars] AS [Extent1]
        INNER JOIN [dbo].[AbstractFoos] AS [Extent2] ON ([Extent2].[Discriminator] IN (N'DerivedFoo',N'CoordinatesFoo')) AND ([Extent1].[Id] = [Extent2].[Bar_Id])
    )  AS [Limit1]
go
```
Which generates a SqlException with this message:
"The geography data type cannot be selected as DISTINCT because it is not comparable."

In our production app, we are a) not using a call to `Distinct()` directly and b) the derived type does not have a DbGeography property, but since we use TPH `null` is being cast to `geography`, resulting in the same exception. As a result simply avoiding calls to Distinct() on the derived types that include DbGeography is not enough- we have no idea when this will cause runtime errors.

### Steps to reproduce
run the included app

[EF6DbGeographyExceptionDemo - Copy.zip](https://github.com/aspnet/EntityFramework6/files/3957583/EF6DbGeographyExceptionDemo.-.Copy.zip)

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.1
SQL Server 14.0.2027 (and whatever our Azure SQL DB instance currently uses)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
