### ISSUE TITLE
Generate async version of a Stored Procedure method in DB first approach

### ISSUE THREAD

**Issue by kinguru** [dotnet/ef6#1531]
Can't find a way to call Stored Procedure asynchronously in the DB first approach.

### Steps to reproduce
Update model from database involving any Stored Procedure from the database.
Try to find async method to call imported Stored Procedure.

### Further technical details
EF version: 6.1.3
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2019 16.4.1

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
