### ISSUE TITLE
Question: Is there something special I have to do to get EF 6.4 running on a .Net Core Azure App Service?

### ISSUE THREAD

**Issue by Tiberriver256** [dotnet/ef6#1540]
Everything works fine with my app when I run it locally and I can connect to my Azure SQL database just fine. When I push it up to an Azure App Service all of a sudden it seems to ignore the connection string and just attempt to connect to mslocaldb.

### Further technical details
EF version: 6.4
Database Provider:  EntityFramework.SqlServer 
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by Tiberriver256** [comment]
Figured it out...

I had to put an app.config at the root with the following in it:
```
<configuration>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
</configuration>
```

**Comment by Tiberriver256** [comment]
Nevermind... that didn't do it either. It was just an issue with migrations apparently so I was able to solve the problem and get the site running by setting the DbInitization to null for now.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
