### ISSUE TITLE
Child entity state does not change when parent entity state is changed

### ISSUE THREAD

**Issue by HoomanBahreini** [dotnet/ef6#1546]
I am not sure if this is a bug... but the following behavior is not what I was expecting. 

Here is how my models look like:

A `Branch` belongs to an `Organisation`. An `Organisation` belongs to a `User`:

    [Table("branch")]
    public class Branch
    {
        public long BranchId { get; set; }

        public string BranchName { get; set; }

        public long OrganisationId { get; set; }

        [ForeignKey("OrganisationId")]
        public Organisation Organisation { get; set; }
    }

    [Table("organisation")]
    public class Organisation
    {
        public long OrganisationId { get; set; }

        public string OrganisationName { get; set; }

        public long UserId { get; set; }

        [ForeignKey("UserId")]
        public UserProfile UserProfile { get; set; }
    }

    [Table("userprofileview")] // <-- UserProfile is representing a view 
    public class UserProfile
    {
        public long UserId { get; set; }

        public string Name { get; set; }
    }

`UserProfile` entity is representing a view and is not insertable (because it has a left join). 

I want to add a new `Branch` to an existing `Organisation` (which belongs to an existing `User`), the following code gives me an error:

    public void AddOrUpdateBranchAsAdminUser(Branch branch)
    {
        if (branch.BranchId > 0)
        {
            // code to update branch
        }
        else
        {
            _context.Branch.Add(branch);
            _context.Entry(branch.Organisation).State = EntityState.Unchanged; // <-- Don't update Organisation 
            /*
             * uncommenting this line will fix the problem
             * _context.Entry(branch.Organisation.UserProfile).State = EntityState.Unchanged;  
             */
            _context.SaveChanges();
        }
    }

This is the error that I get:

> The target table userprofileview of the INSERT is not insertable-into

If I uncomment the line that sets the state of `UserProfile` then it works fine... 

I would have expected that changing `Organisation` state (parent entity) should change the state of `UserProfile` too.

**Comment by Seabizkit** [comment]
You need to show how branch was constructed. this is better for SO, rather than here.

You creating a new branch... making the Organication to unchanged, but yet didnt dhow how this was linked or even added, seem weird to even touch the property, considering it has to exist first.

which means when creating a branch you need to set the or OrganisationId property on branch.

then you wanting to interact on the UserProfile and make its state different.

I believe rather than this being an issue with EF, you are interacting on them in a strange way.

Which lead me to believe this should be on SO. (https://stackoverflow.com/)

**Comment by HoomanBahreini** [comment]
@Seabizkit thanks for your comment. I have shown the navigation properties...
 
The issue is when I set the state of `Organisation` to `Unchanged`, it does not set the state of `UserProfile` (which is a property of `Organisation` to `Unchanged`... 

    _context.Entry(branch.Organisation).State = EntityState.Unchanged;
   // Since UserProfile belongs to Organisation the following line should not be needed, but in practice it is
   _context.Entry(branch.Organisation.UserProfile).State = EntityState.Unchanged;

**Comment by Seabizkit** [comment]
Hi @HoomanBahreini 

> You need to show how branch was constructed

again you cannot be helped without this information

> his is better for SO, rather than here.

again 

------------------

you are better off creating this in SO and adding a link.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
