### ISSUE TITLE
[Discussion] Moving EntityFramework6 repo to dotnet org 2020-01-07

### ISSUE THREAD

**Issue by Pilchie** [dotnet/ef6#1547]
As a first step towards the work describe [here](https://github.com/dotnet/announcements/issues/127), we're planning on migrating the EntityFramework6 repo to the dotnet org, and renaming it to "ef6". We'd like to get this done ASAP.

We don't expect any significant issues for contributors, GitHub is great about adding redirects. However, it may impact our ability to produce nightly builds and flow dependencies for a few days.

Please let us know if you run into any other issues.

**Comment by Pilchie** [comment]
The initial move and rename are complete.  May need to do more work to get builds going again.

**Comment by jzabroski** [comment]
How will moving issues work?  Can we undo a bunch of the close-wont-fix decisions that have been made over the past 4 years by the previous maintainers?

**Comment by Pilchie** [comment]
Issues move automatically and transparently with the repository.

This move doesn't change the set of owners or maintainers of the repository, it merely makes it easier to work with partner teams that are already in the "dotnet" org.  It doesn't change the triage decisions already made.  If you have new data about a particular issue, then it can be discussed again, but there is no cause for a bulk re-evaluation.

**Comment by jzabroski** [comment]
Ah, dotnet org.  I thought you were saying dotnet foundation.  Sorry.

**Comment by Pilchie** [comment]
This is done now.
