### ISSUE TITLE
error : Unable to find version '5.0.0' of package 'EntityFramework' while building the EF tooling

### ISSUE THREAD

**Issue by TapanGhoshRocket** [dotnet/ef6#1565]
Followed the steps mentioned below to build the tool.
https://github.com/dotnet/ef6/wiki/Building-the-Tools

However, getting the error while executing the command "BuildEFTools /t:Install". Here is the output of the command execution.

E:\ef6-6.1.3>BuildEFTools /t:Install
Microsoft (R) Build Engine version 12.0.40629.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring NuGet packages...
  All packages listed in packages.config are already installed.
  All packages listed in packages.config are already installed.
  EntityFramework -> E:\ef6-6.1.3\bin\Debug\EntityFramework.dll
  EntityFramework.SqlServer -> E:\ef6-6.1.3\bin\Debug\EntityFramework.SqlServer.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  EntityFramework.SqlServerCompact -> E:\ef6-6.1.3\bin\Debug\EntityFramework.SqlServerCompact.dll
  XmlCore -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Tools.Design.XmlCore.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  DesignXmlCore -> E:\ef6-6.1.3\bin\Debug\Microsoft.VisualStudio.Data.Tools.Design.XmlCore.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesignerVersioningFacade -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.VersioningFacade.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesignModel -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.Model.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesignExtensibility -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.Extensibility.dll
  Running Code Analysis...
  EntityDesignDatabaseGeneration -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.DatabaseGeneration.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesign -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.dll
  Running Code Analysis...
  One or more indirectly-referenced assemblies could not be found. These assemblies are not required for analysis. However, without them, analysis results could be incomplete.
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesignBootstrapPackage -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.BootstrapPackage.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesigner -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.EntityDesigner.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  EntityDesignPackage ->
  EntityDesignPackage ->
  EntityDesignPackage -> E:\ef6-6.1.3\bin\Debug\Microsoft.Data.Entity.Design.Package.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  Creating intermediate PkgDef file.
  VsIdeTestHostFramework -> E:\ef6-6.1.3\bin\Debug\Microsoft.VisualStudio.QualityTools.VsIdeTestHostFramework.dll
  TestInfrastructure -> E:\ef6-6.1.3\test\EFTools\TestInfrastructure\bin\Debug\EFDesigner.TestInfrastructure.dll
  InProcTests -> E:\ef6-6.1.3\test\EFTools\InProcTests\bin\Debug\EFDesigner.InProcTests.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  E2ETests -> E:\ef6-6.1.3\test\EFTools\E2ETests\bin\Debug\EFDesigner.E2ETests.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  FunctionalTests -> E:\ef6-6.1.3\test\EFTools\FunctionalTests\bin\Debug\EFDesigner.FunctionalTests.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  UnitTests -> E:\ef6-6.1.3\test\EFTools\UnitTests\bin\Debug\EFDesigner.UnitTests.dll
  VsIdeTestHostAddin -> E:\ef6-6.1.3\bin\Debug\Microsoft.VisualStudio.QualityTools.HostAdapters.VsIdeAddIn.dll
  Installer -> E:\ef6-6.1.3\bin\Debug\VsIdeTestHost.msi
  Restoring NuGet packages...
  All packages listed in packages.config are already installed.
  All packages listed in packages.config are already installed.
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  EntityFramework -> E:\ef6-6.1.3\bin\DebugNet40\EntityFramework.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  EntityFramework.SqlServerCompact -> E:\ef6-6.1.3\bin\DebugNet40\EntityFramework.SqlServerCompact.dll
  Migrate -> E:\ef6-6.1.3\bin\DebugNet40\migrate.exe
  EntityFramework.SqlServer -> E:\ef6-6.1.3\bin\DebugNet40\EntityFramework.SqlServer.dll
  EntityFramework.SqlServerCompact.Legacy -> E:\ef6-6.1.3\bin\DebugNet40\EntityFramework.SqlServerCompact.Legacy.dll
  EntityFramework.PowerShell.Utility -> E:\ef6-6.1.3\bin\DebugNet40\EntityFramework.PowerShell.Utility.dll
  EntityFramework.PowerShell -> E:\ef6-6.1.3\bin\DebugNet40\EntityFramework.PowerShell.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  EntityFramework -> E:\ef6-6.1.3\bin\Debug\EntityFramework.dll
  EntityFramework.SqlServer -> E:\ef6-6.1.3\bin\Debug\EntityFramework.SqlServer.dll
  EntityFramework.SqlServerCompact -> E:\ef6-6.1.3\bin\Debug\EntityFramework.SqlServerCompact.dll
  EntityFramework.SqlServerCompact.Legacy -> E:\ef6-6.1.3\bin\Debug\EntityFramework.SqlServerCompact.Legacy.dll
  Migrate -> E:\ef6-6.1.3\bin\Debug\migrate.exe
  EntityFramework.PowerShell.Utility -> E:\ef6-6.1.3\bin\Debug\EntityFramework.PowerShell.Utility.dll
  EntityFramework.PowerShell -> E:\ef6-6.1.3\bin\Debug\EntityFramework.PowerShell.dll
  Attempting to build package from 'EntityFramework.CodeTemplates.CSharp.nuspec'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.CodeTemplates.CSharp.6.1.3.nupkg'.
  Attempting to build package from 'EntityFramework.CodeTemplates.VisualBasic.nuspec'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.CodeTemplates.VisualBasic.6.1.3.nupkg'.
  Attempting to build package from 'EntityFramework.SqlServerCompact.Legacy.nuspec'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.SqlServerCompact.Legacy.6.1.3.nupkg'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.SqlServerCompact.Legacy.6.1.3.symbols.nupkg'.
  Attempting to build package from 'EntityFramework.SqlServerCompact.nuspec'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.SqlServerCompact.6.1.3.nupkg'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.SqlServerCompact.6.1.3.symbols.nupkg'.
  Attempting to build package from 'EntityFramework.nuspec'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.6.1.3.nupkg'.
  Successfully created package 'E:\ef6-6.1.3\bin\Debug\Packages\EntityFramework.6.1.3.symbols.nupkg'.
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  Installing 'Microsoft.SqlServer.Compact 4.0.8876.1'.
  Successfully installed 'Microsoft.SqlServer.Compact 4.0.8876.1'.
**E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.de'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.es'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.fr'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.it'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.ja'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.ko'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.ru'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.zh-Hans'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error : Unable to find version '5.0.0' of package 'EntityFramework.zh-Hant'. [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]
E:\ef6-6.1.3\.nuget\NuGet.targets(106,9): error MSB3073: The command ""E:\ef6-6.1.3\.nuget\NuGet.exe" install "packages.config" -source "" -NonInteractive -RequireConsent   -solutionDir "E:\ef6-6.1.3\bin\Debug\MsiRuntimeInputs "" exited with code 1.
 [E:\ef6-6.1.3\src\EFTools\setup\GenerateMsiInputs\GenerateMsiInputs.msbuild]**

Thanks,
Tapan

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
