### ISSUE TITLE
6.3 and 6.4 generating OUTER APPLY more often

### ISSUE THREAD

**Issue by pergardebrink** [dotnet/ef6#1566]
Using Entity Framework < 6.3 with MySQL, we have been able to dodge most OUTER APPLY that happens in some situations (OUTER/CROSS APPLY is not supported by MySQL). 

In 6.3 and 6.4, Entity Framework seems to be much more eager to emit OUTER APPLY queries, which causes the MySql provider not being able to generate a query. 

### Steps to reproduce
I have included two projects. We use Devart, which is a licensed product, but I provided another version that is using MySql.Data (where the problem appears differently but is having the same limits). Devart fails with `System.NotSupportedException: OUTER APPLY is not supported by MySQL.`

[OuterApplyDevartMySql.zip](https://github.com/dotnet/ef6/files/4070803/OuterApplyDevartMySql.zip)
[OuterApplyMySqlData.zip](https://github.com/dotnet/ef6/files/4070804/OuterApplyMySqlData.zip)

Digging into the commits, I found that the setting MaxNodeCountForTransformations seems to be what's changed (248330348ea7b5d756fa4bab52d5cebc98887fde), which I can change the setting for, back to the previous value it had in 6.2. But I wonder if there's a way to avoid just OUTER/CROSS APPLY without losing the performance benefits of that change for other queries? 

### Further technical details
EF version: 6.3 and 6.4
Database Provider: Devart.MySql (and MySql.Data)
Operating system: Windows 10, Windows Server 2016
IDE: Visual Studio 2019

**Comment by lyadeski** [comment]
we are having the exact same issue, its becoming unbearable and sporadically taking our production systems offline. did you ever find a solution? We also use Devart.

**Comment by pergardebrink** [comment]
> we are having the exact same issue, its becoming unbearable and sporadically taking our production systems offline. did you ever find a solution? We also use Devart.

I did find the setting MaxNodeCountForTransformation, which controls an optimization that was added in 6.3. 
If you add that setting to app.config/web.config, and set it to 100000, it should return to the a similar behaviour as in Entity Framework 6.2!

```
<appSettings>
        <!-- This setting forces Entity Framework 6.4 to use the same optimization as 6.2 does -->
        <add key="EntityFramework_EntityClient_MaxNodeCountForTransformations" value="100000"/>
</appSettings>
```

**Comment by lyadeski** [comment]
this is fantastic - thank you @pergardebrink

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
