### ISSUE TITLE
The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1578]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/887736/the-type-initializer-for-microsoftdatasqlclienttds.html)._

---
<p>Hello</p> When I run my application through Visual Studio the app runs smoothly, but when I publish the app through the option: Properties -&gt; Publish when installing the app and run it I get the following error: &quot;The type initializer for 'Microsoft . Data.SqlClient.TdsParser 'threw an exception. &quot;. Thank you

---
#### Visual Studio Feedback System on 1/16/2020, 07:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 1/16/2020, 11:36 PM: 

<p>It seems you successfully build and publish this application, but meet this exception error message when you install it on the same computer or different computer, right? Could you please share more detail information about this application? That will help us analysis this issue.<br>
According to the error message, please have a try with the following to troubleshoot this issue:</p>
<ol>
<li>Please check the app.config file and check there have badly formed XML or unexpected elements</li>
<li>Change the publish settings to have a try</li>
</ol>
<p>If you have any updates, please feel free to let us know.</p>

#### Julio Cesar Serna Hincapie on 1/17/2020, 04:36 AM: 

<p>Hello</p>The problem occurs in both cases when I install on the same computer on which I develop and when I install on a different computer.  I have also checked the publication settings and apparently it's fine since I have other applications that work without problem  This is my app.config file: &lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;configuration&gt;
  &lt;configSections&gt;
    &lt;section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" /&gt;
    &lt;!-- For more information on Entity Framework configuration, visit https://go.microsoft.com/fwlink/?LinkID=237468 --&gt;
  &lt;/configSections&gt;
  &lt;startup&gt;
    &lt;supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" /&gt;
  &lt;/startup&gt;
  &lt;appSettings&gt;
    &lt;add key="Local" value="Data Source =.; Initial Catalog = database; Persist Security Info = True; User ID = user; Password = *****;" /&gt;
    &lt;add key="Remoto" value="Data Source=datasource;Initial Catalog=database;User ID=user;Password=******"/&gt;
  &lt;/appSettings&gt;
  &lt;runtime&gt;
    &lt;assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"&gt;
      &lt;dependentAssembly&gt;
        &lt;assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" /&gt;
        &lt;bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" /&gt;
      &lt;/dependentAssembly&gt;
      &lt;dependentAssembly&gt;
        &lt;assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" /&gt;
        &lt;bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" /&gt;
      &lt;/dependentAssembly&gt;
      &lt;dependentAssembly&gt;
        &lt;assemblyIdentity name="System.ComponentModel.Annotations" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" /&gt;
        &lt;bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" /&gt;
      &lt;/dependentAssembly&gt;
    &lt;/assemblyBinding&gt;
  &lt;/runtime&gt;
  &lt;entityFramework&gt;
    &lt;defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework"&gt;
      &lt;parameters&gt;
        &lt;parameter value="mssqllocaldb" /&gt;
      &lt;/parameters&gt;
    &lt;/defaultConnectionFactory&gt;
    &lt;providers&gt;
      &lt;provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" /&gt;
    &lt;/providers&gt;
  &lt;/entityFramework&gt;
  &lt;system.web&gt;
    &lt;membership defaultProvider="ClientAuthenticationMembershipProvider"&gt;
      &lt;providers&gt;
        &lt;add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" /&gt;
      &lt;/providers&gt;
    &lt;/membership&gt;
    &lt;roleManager defaultProvider="ClientRoleProvider" enabled="true"&gt;
      &lt;providers&gt;
        &lt;add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" cacheTimeout="86400" /&gt;
      &lt;/providers&gt;
    &lt;/roleManager&gt;
  &lt;/system.web&gt;
&lt;/configuration&gt;<br>Thank you.

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This is tracked by https://github.com/dotnet/SqlClient/issues/85
