### ISSUE TITLE
DbContext.Entity() taking long time

### ISSUE THREAD

**Issue by Manikese** [dotnet/ef6#1579]
Describe what is not working as expected.

DbContext.Entity() should take < 5 milliseconds

Actual result:

Average time it takes in our environments is 380 milliseconds

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

Create a class:
class UnitOfWork : DbContext

Add a function:
protected UnitOfWork(string contextName)
            : base(ContextConnectionStringManager.Get(contextName))

Attach a SavingChanges Event Handler

var _thisObjectContext.SavingChanges = ((IObjectContextAdapter)this).ObjectContext;
_thisObjectContext.SavingChanges += new EventHandler(SavingChanges);

Create SavingChanges function:

private void SavingChanges(object sender, EventArgs e)

Create and start a timer:

var timer = Stopwatch.StartNew();

Add a loop:

foreach (var entry in context.ObjectStateManager.GetObjectStateEntries(EntityState.Added | EntityState.Modified).Where(x => x?.Entity != null))

Call DbContext.Entity() and output the timing info:

var temp = Entry(entry.Entity);
Console.WriteLine($"Entry(entry.Entity):  {timer.ElapsedMilliseconds}");
timer.Restart();

```c#
Output:
Entry(entry.Entity):  351
```

### Further technical details
EF version: (found in project.csproj or packages.config)
<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>

Database Provider: (e.g. EntityFramework.SqlServer)
Product Name: Microsoft SQL Server Standard Edition (64-bit)
Product Version:  14.0.1000 RTM
Collation:  SQL_Latin1_General_CP1_CI_AS
Compatibility level:  SQL Server 2017 (140)

Operating system: (e.g. Windows 10) 
Windows 10

IDE: (e.g. Visual Studio 2017 15.6)
Visual Studio Professional 2019
Version 16.4.1

**Comment by ajcvickers** [comment]
@Manikese Likely because of [auto-detect changes](https://blog.oneunicorn.com/2012/03/11/secrets-of-detectchanges-part-2-when-is-detectchanges-called-automatically/).
