### ISSUE TITLE
Deploying a web app using web deploy in visual studio problematic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/884448/deploying-a-web-app-using-web-deploy-in-visual-stu.html)._

---
When deploying a dotnet 3.0 app to azure with sqlserver configured, deployment is successful but I get a 404 error on website launch. This is unlike previous behaviour in 2.1 LTS where no such error exists.

---
#### Visual Studio Feedback System on 1/14/2020, 07:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/15/2020, 00:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
