### ISSUE TITLE
Migration fails when older version of EntityFramework is in GAC, what to do against this?

### ISSUE THREAD

**Issue by TimonChristl** [dotnet/ef6#1587]
We have a customer where migrations fail in EF 6.2 with MethodNotFoundException because the property 
`System.Data.Entity.Migrations.Model.AddPrimaryKeyOperation.IsClustered` was moved to the base class between 6.1 and 6.2 (This change is mentioned in #190). Normally this would not be problem, since we deploy the 6.2 version of EntityFramework.dll in the application directory, but on that customer's machine, apparently some other setup installed version 6.1 to the GAC. This is a real problem because the assembly identity for 6.1 and 6.2 (and in fact all versions since 6.0) is exactly the same: "EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Therefore assembly binding requests 6.0.0.0, finds it in the GAC and the assembly in the application directory is never really used.

Is there any specific reason why EntityFramework.dll did not change its assembly version? I know that EntityFramework is not designed to be installed in the GAC, but the way that it is now means that a single "rogue setup" can deny other applications from running. Is there anything I could do to make our application run nevertheless?

**Comment by pboisso** [comment]
Hi @TimonChristl,
I have the same issue here.  Was wondering if you find out a work around this issue by any luck?
Keep wondering too why MS keeps the same version number.
Thanks in advance.
P

**Comment by TimonChristl** [comment]
We simply suggested to the customer to uninstall the assembly from the GAC. This might break some other app in the long run, but at least our app would then be able to make it past the failing migration. Have not heard anything from the customer since then, so I assume it worked.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
