### ISSUE TITLE
EF 6.4 Manual migrations do not work for user with Azure AD authorization

### ISSUE THREAD

**Issue by NikolayNahimov** [dotnet/ef6#1588]
Our company recently switched to Azure AD MFA authorization. 
After that migration scaffolding from Package Manager Console no longer works.
Executing `add-migration` command results in error
```
Cannot scaffold the next migration because the target database was created with a version of Code First earlier than EF 4.3 and does not contain the migrations history table. To start using migrations against this database, ensure the current model is compatible with the target database and execute the migrations Update process. (In Visual Studio you can use the Update-Database command from Package Manager Console to execute the migrations Update process).
```
The database has `__MigrationHistory` table with multiple entries in it.
Before switching to AAD auth migrations used to work as expected.

### Steps to reproduce
Open Package Manager Console and run `add-migration` command for AAD auth user.

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework.SqlServer
Operating system:Windows 10
IDE: Visual Studio Enterprise 2019, version 16.4.4

Scaffolding a new migration from the code works fine (the code below).
However, note that we pass DbContext to DbMigrator constructor.
```c#
var config = new Configuration();

var migrator = new DbMigrator(config, new AppDbContext());
var methodInfo = migrator.GetType().GetMethod("Scaffold", BindingFlags.NonPublic | BindingFlags.Instance);
if (methodInfo == null) return;

object[] parameters = { migrationName, config.MigrationsNamespace, false };
var migration = (ScaffoldedMigration) methodInfo.Invoke(migrator, parameters);
```

Our investigation (based on PDB generated by dotPeek) shows that the problem is due to unexpectedly missing connection access token (AccessToken fields) when executing `context.Database.Exists()` in
```
EntityFramework.dll!System.Data.Entity.Migrations.History.HistoryRepository.QueryExists(string contextKey)
EntityFramework.dll!System.Data.Entity.Migrations.History.HistoryRepository.Exists(string contextKey)
EntityFramework.dll!System.Data.Entity.Migrations.History.HistoryRepository.GetPendingMigrations(System.Collections.Generic.IEnumerable<string> localMigrations)
EntityFramework.dll!System.Data.Entity.Migrations.DbMigrator.Scaffold(string migrationName, string namespace, bool ignoreChanges)
```
Note, that in the constructor of DB context the connection has valid access token.

So it looks like DbConnection/DbContext is being cloned somewhere internally and AccessToken property is not copied there.

**Comment by InteXX** [comment]
I was having this problem, and it turned out to be differing versions of the EF6 package among various projects in my solution. Once I updated all projects to the latest version, `Add-Migration` worked correctly.

YMMV

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
