### ISSUE TITLE
Edmx serialization doesn't serialize all MetadataProperties

### ISSUE THREAD

**Issue by Sironas** [dotnet/ef6#1597]
Hello,

I upgraded our version EF 6.1.3 to 6.4.0 to use the new cache system with DbModelStore.
All the serialization and deserialization of the file went well but some data are lost in the process such as ClrPropertyInfo and ClrAttributes of NavigationProperties

We use custom property attributes in our code to enable some behavior when using EF but after the deserialization of the .edmx we can't find them anymore.

While checking the code I saw the class EdmModelVisitor which visits everything without exception (even MetadataProperties also called Annotation) : VisitEdmEntityType > VisitEdmNavigationProperty > VisitMetadataItem > VisitAnnotations
But the class EdmSerializationVisitor doesn't override the method VisitAnnotations to write them in the xml file

(this problem happens for all MetadataProperty not only NavigationProperty's MetadataProperties)

Is it possible to fix this or to retrieve all Clr information after deserialization of the edmx in another way ?

### Steps to reproduce

You can reproduce with this model

```c#
    public class SampleCustomAttribute : Attribute
    {

    }
    public class Sample
    {
        [SampleCustom]
        public Sample MyNavigationProperty { get; set; }
    }
```
SampleCustomAttribute will not be available after deserialization of the cached DbModel

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework.SqlServer or MySQL provider
Operating system: Windows 10
IDE: Visual Studio 2015

Thank you
Regards,
Hervouet Thomas

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
