### ISSUE TITLE
Cannot load the solution projects: Microsoft.DotNet.Arcade.Sdk\Sdk\Sdk.props was not found

### ISSUE THREAD

**Issue by dkiryanov** [dotnet/ef6#1599]
Hi colleagues,
I have just forked the repository and tried to open the solution in VS 2017. I have found that the projects cannot be loaded due to the error:

`C:\Users\dk\Source\Repos\EF6\src\ef6\ef6.csproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\dk\Source\Repos\EF6\Directory.Build.props`

The same error for every project in the solution. Iif I run `cmd: build.exe`, it builds the project without errors but the projects in solution are still unloaded. I had investigated the /MSBuild/Sdks/ folder and it really does not contain Sdk.props file.

Also, I tried to open the solution in VS 2019 and got the same problem: the projects are not loaded at all. 

### Steps to reproduce

1. Clone the repository
2. Open it using VS 2017/VS 2019
Actual result: the projects are not loaded.
Expected result: the solution is loaded correctly, restoring all the necessary packages.

### Further technical details
Operating system: Windows 10
IDE: Visual Studio 2017 15.2
.NET framework: 4.8

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
