### ISSUE TITLE
Incorrect migration script when TPH sub classes has same property name

### ISSUE THREAD

**Issue by lyttlegy** [dotnet/ef6#1601]
Code first TPH table with the same property names on the sub classes generated migration missing columns.
Lets have the following class
```c#
    public class Doc 
    {
        public int Id { get; set; }
    }
```
with sub classes as follows:
```c#
    public class D: Doc
    {
        public string Bar{ get; set; }
    }
    public class F: Doc
    {
        public string Bar{ get; set; }
    }
```
Migration generate Bar and Bar1 columns, which is intended.

However introducing a new class
```c#
    public class A: Doc
    {
        public string Bar{ get; set; }
    }
```
Migration use column order according to the name of the table. According to this logic, it should 

- rename column `Bar1` to `Bar2`
- rename column `Bar` to `Bar1`
- create `Bar` column
 
Instead it create a migration as follows:
```c#
            RenameColumn(table: "dbo.Docs", name: "Bar", newName: "Bar1");
            RenameColumn(table: "dbo.Docs", name: "Bar1", newName: "Bar2");
```
The order seems to be off and missing creating the new column. (same happens with index creation)

In case the class name is alphabetically later then the last one it creates `Bar2` normally. 

### Further technical details
EF version: 6.2.0
Database Provider:  EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.11

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
