### ISSUE TITLE
DbExecutionStrategy does not detect user transactions

### ISSUE THREAD

**Issue by gregpakes** [dotnet/ef6#1615]
I am using EF 6.2 and have an issue where we are using the **DbExecutingStrategy** to retry database deadlocks.

I can see in the documentation, that User Transactions are not supported.  However, I believe the framework is supposed to detect when they are used and throw an exception.  This is not happening for me.

Is this a known bug in 6.2?  I have looked at the 6.3 and 6.4 milestones and can't see any closed issues that address this.

My code is as follows:

```
    using (var tran = this._devContext.Database.BeginTransaction())
    {
        this._devContext.Database.ExecuteSqlCommand(sql);
        tran.Rollback();
    }
```

In my case, this is test code and the SQL being executed causes a deadlock.  What happens when I use **DbExecutionStrategy** is that the SQL is successfully retried and it works.  However, when `tran.Rollback()` is called, an exception is thrown because the retry has ignored the user transaction and commited the query.

Here is the exception that occurs:

```
Message: Value cannot be null. Parameter name: connection
System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName):14
System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext.WithConnection(DbConnection connection)
System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Rollback(DbTransaction transaction, DbInterceptionContext interceptionContext):50
System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
```

I would have expected EF to identify the user transaction and throw an exception before running the SQL.

**Update**

I have replicated this same issue in EF 6.4

**Comment by gregpakes** [comment]
I am blocked quite badly by this.  Without proper/functional detection of existing user transactions, I can't use any execution strategy.

**Comment by gregpakes** [comment]
I have looked into this further and the issue appears to be with this line:

https://github.com/dotnet/ef6/blob/8efe9091b87fb5ba8a8c6419373e57a1013017e8/src/EntityFramework/Infrastructure/DbExecutionStrategy.cs#L323

It only checks for the old style `TransactionScope` transactions and does not check for the preferred EF6 transactions `context.Database.BeginTransaction()`.

I am assuming this is a bug.

**Comment by gregpakes** [comment]
EF Core fixes this by checking both types of transaction.

https://github.com/dotnet/efcore/blob/288fedb6bcff0ff437132b7f36459c374070659b/src/EFCore/Storage/ExecutionStrategy.cs#L310

Is this possible in EF 6?  I have looked through the code, but can't find something similar to get the Current Database Context, in order to get the transaction.

**Comment by gregpakes** [comment]
@AndriySvyryd Sorry to tag you directly, but it looks like you solved the reverse of this issue in EF Core (adding support for System.Transactions).

**Comment by gregpakes** [comment]
I guess this is the reality of a "finished" product.   I can't see this being fixed anymore.

**Comment by AndriySvyryd** [comment]
@gregpakes Even if you submit a PR we don't currently have a release planned for EF6 and this issue doesn't satisfy the criteria for a patch.

**Comment by gregpakes** [comment]
Appreciate the response.  😞

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by jgtestw** [comment]
This happened to me too.
