### ISSUE TITLE
an error occurred during model generation from the database

### ISSUE THREAD

**Issue by Varorbc** [dotnet/ef6#1616]
![image](https://user-images.githubusercontent.com/5714438/76716422-159d1880-676b-11ea-849c-d7710212bf08.png)

### Further technical details
EF version: 6.3
Database Provider:  EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.6

**Comment by lajones** [comment]
Hi @Varorbc I've not seen that error message before. Could you please provide a small repro project? And explain exactly what actions you were taking at the time (I'd imagine just calling Add New Item on an ADO.NET Entity Data Model but I'd like to check).

**Comment by Varorbc** [comment]
@lajones  If you use the new csproj format, this issue will be reproduced

**Comment by lajones** [comment]
If you mean a .NET Core or .NET Standard project then I'm afraid the EF6 designer is not supported on that, see [the docs here](https://docs.microsoft.com/en-us/ef/ef6/what-is-new/). We are encouraging people to move towards the CodeFirst approach for EFCore.

Actually I'm not even sure how you did it. For me the Add New Item|Ado.NET Entity Data Model option does not even show up for a .NET Core project.

**Comment by Varorbc** [comment]
I'm use the new csproj format and .net framework target framework

**Comment by lajones** [comment]
@Varorbc I'm sorry but please provide a small repro project. There's so much that could potentially be wrong that without a project continuing to guess would not be useful. Also it would be useful to know what steps you took to create this project in the first place. Did you use one of the tools available on the web? If so which one?

**Comment by Varorbc** [comment]
# step 1

[ClassLibrary1.zip](https://github.com/dotnet/ef6/files/4346448/ClassLibrary1.zip)

#  step 2
![20200318091250](https://user-images.githubusercontent.com/5714438/76915549-a9e8b600-68f8-11ea-9d19-526489d37f0b.jpg)

# step 3

![20200318091454](https://user-images.githubusercontent.com/5714438/76915654-0055f480-68f9-11ea-81a4-c00d164ff867.jpg)

# step 4

![4](https://user-images.githubusercontent.com/5714438/76915740-51fe7f00-68f9-11ea-8150-b0277093e6a5.jpg)

# step 5

![5](https://user-images.githubusercontent.com/5714438/76915743-532fac00-68f9-11ea-94e2-f6f05ff8a830.jpg)

# step 6

![6](https://user-images.githubusercontent.com/5714438/76915762-5fb40480-68f9-11ea-97b0-42fb138ad2d3.jpg)

**Comment by lajones** [comment]
Thanks @Varorbc. That allowed me to repro it. Unfortunately we don't support the EF6 designer in SDK-style projects. We are tracking that issue in #883. I agree that the [docs I pointed you to](https://docs.microsoft.com/en-us/ef/ef6/what-is-new/) did not make that clear - so I have a [PR out to fix that](https://github.com/dotnet/EntityFramework.Docs/pull/2195).

If you want to use SDK-style projects then we encourage you to use EFCore instead of EF6. If you want to continue to use the EF6 designer then please do that in an old-style, i.e. non-SDK-style, .NET Framework project.

**Comment by Varorbc** [comment]
When will the issue(#883) be fixed

**Comment by lajones** [comment]
I'm afraid it is low on our list of priorities as there is an easy workaround - see [this comment](https://github.com/dotnet/ef6/issues/883#issuecomment-562341058) in the referenced issue.

**Comment by Varorbc** [comment]
Thank you
