### ISSUE TITLE
Identity Library to use for EF6.4 on .Net core

### ISSUE THREAD

**Issue by rangav** [dotnet/ef6#1617]
I am trying to use EF 6.4 in .Net standard 2.1 library.

What Identity library should i use with EF.6.4 in .Net core?

I am using Microsoft.AspNet.Identity.EntityFramework in .Net framework library

Is there any example project using EF 6.4 and .Net core

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: VS 2019

**Comment by ajcvickers** [comment]
@rangav ASP.NET Core uses EF Core for Identity. There is no EF6 support. Non-core ASP.NET doesn't run on .NET Core.

Effectively, if you want to use ASP.NET Identity on .NET Core, then you need to use ASP.NET Core and EF Core.
