### ISSUE TITLE
nuget.org has ef 6.4, but not 6.4.2

### ISSUE THREAD

**Issue by minoseah629** [dotnet/ef6#1619]
is there a reason why ef 6.4.2 is not available on nuget.org?

**Comment by ajcvickers** [comment]
@minoseah629 6.4.2 doesn't exist. Where did you hear about a 6.4.2 release?

**Comment by minoseah629** [comment]
https://github.com/dotnet/ef6/releases/tag/v6.4.2

**Comment by ajcvickers** [comment]
@minoseah629 Thanks. I deleted the tag.

**Comment by CZEMacLeod** [comment]
@ajcvickers There are also supposedly releases for 6.3.1, 6.3.2, 6.3.3 and 6.4.1
These seem to be sync'd with the .NET Core releases; but it is not obvious if anything changed in the EF6 builds during that period. This seems to be a result of the pull requests like #1484 
This is rather confusing; my understanding was EF6 shipped on [Nuget.org](https://www.nuget.org/packages/EntityFramework/) and was not actually part of NetCore 3.x so the NetCore releases (e.g. [.NET Core 3.1.2](https://github.com/dotnet/ef6/releases/tag/v3.1.2)) and versions etc. make it difficult to track.

**Comment by ajcvickers** [comment]
@CZEMacLeod NuGet is the source of truth. Often these things are done by a build team and happen to all reopos, even when we later don't have anything to ship.
