### ISSUE TITLE
Default value is lost on non-nullable decimal during migration

### ISSUE THREAD

**Issue by rikrak** [dotnet/ef6#1620]
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019

I've just upgraded from v6.1.3 to v6.4 and noticed that some of my columns have lost a default constraint.  It seems to affect decimal values whose precision has changed.  I think the Alter Column behaviour has changed at some point between v6.1.3 and v6.4

See replication project: https://github.com/rikrak/EF6_DefaultValOnMigrationIssue
Repeat the the following with 6.1.3 and 6.4 to see the difference in behaviour.

Replication Steps.  
- Add the EF Nuget package to a project and initialise Migrations
- Create a DbContext class
- Add a simple Model class with an Id and a decimal property: "MyDecimal"
- Add the Model class to the Db Context
- Create a Migration: "Initial"
- Update the database
- Add a second decimal property to the model class: "MySecondDecimal"
- Create a Migration "Second"
- Update the database
- Review the generated db table, note the default constraint for "MySecondDecimal" (defaults to zero)
- Using a model configuration class set the Precision of "MySecondDecimal" to be 18,5
- Create a Migration: "Third"
- Update the database
- Review the generated db table

Expected Result:
- MySecondDecimal should have a default constraint

Actual Result:
- (With EF6.4) the default constraint has been dropped
- (With EF6.1) the default constraint is retained

This may be the same issue as #1264

**Comment by Reci** [comment]
Noticed losing some default constraints with upgrading 6.1.3 -> 6.3. After some investigations I suppose that such behavior was added not later [6.2.0-beta1](https://github.com/dotnet/ef6/releases/tag/6.2.0-beta1).
Example migration to reproduce:
```c#
public override void Up()
        {
            // Id with default value
            Sql("Create table Ntts ([Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()), CONSTRAINT [PK_Ntts] PRIMARY KEY CLUSTERED ([Id] ASC))");
            DropPrimaryKey("Ntts", name: "PK_Ntts");
            AlterColumn("Ntts", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("Ntts", "Id");
            // Column with default value
            AddColumn("Ntts", "BilledByBillingTypeFlatFee", c => c.Boolean(nullable: true, defaultValue: false));
            Sql("UPDATE Ntts SET BilledByBillingTypeFlatFee = 0");
            AlterColumn("Ntts", "BilledByBillingTypeFlatFee", c => c.Boolean(nullable: false));
        }
```

On 6.1.3 version it leads to creation table with constraints:
```sql
CREATE TABLE [dbo].[Ntts](
	[Id] [uniqueidentifier] NOT NULL,
	[BilledByBillingTypeFlatFee] [bit] NOT NULL,
 CONSTRAINT [PK_Ntts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Ntts] ADD  DEFAULT (newsequentialid()) FOR [Id]
GO

ALTER TABLE [dbo].[Ntts] ADD  DEFAULT ((0)) FOR [BilledByBillingTypeFlatFee]
GO
```

But on 6.2+ default constraints are lost:
```sql
CREATE TABLE [dbo].[Ntts](
	[Id] [uniqueidentifier] NOT NULL,
	[BilledByBillingTypeFlatFee] [bit] NOT NULL,
 CONSTRAINT [PK_Ntts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)) ON [PRIMARY]
GO
```

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
