### ISSUE TITLE
6.4.0 nuget is broken

### ISSUE THREAD

**Issue by maxima120** [dotnet/ef6#1624]
if I try to install 6.4.0 nuget in visual studio it says System.ComponentModel.DataAnnotation is missing in the GAC

**If I add DataAnnotation ref manually it works**. It seems nuget config is incorrect.

.NET 4.8
VS 2019 Pro
Windows 10 Pro x64

**Comment by gregpakes** [comment]
I am using 6.4 on nuget and am not having this issue.

**Comment by maxima120** [comment]
Probably because you have it in the gac

**Comment by gregpakes** [comment]
Can't see it in the GAC?

![image](https://user-images.githubusercontent.com/102243/78725637-5e637e00-7973-11ea-9a47-c93ee9e2bdb3.png)

**Comment by Oglan** [comment]
Try to add reference to this assembly in the project.
We have this assembly as a reference but with newest version, ef6.exe in turn references older version, as result we had to add assembly binding redirect to ef6.exe.config and put this config to the packages\EntityFramework.6.4.0\tools\net45\any\ (you may use other version of ef6.exe in your project).

Hope this will help.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
