### ISSUE TITLE
Entity Data Model Wizard crashes with Oracle connection

### ISSUE THREAD

**Issue by gphillip98** [dotnet/ef6#1627]
When I try to add a new EF Designer from Database and select an Oracle db connection as soon as Next is clicked the designer just closes.  There is no error message and nothing in the eventlog.
I am using VS 2017 and created a new MVC Web app.  Pulled in "Oracle.ManagedDataAccess" version="19.6.0" and "Oracle.ManagedDataAccess.EntityFramework" version="19.6.0" from Nuget
and I have the ODAC 122011 installed

### Further technical details
EF version: 6
Database Provider: Oracle.ManagedDataAccess version=19.6.0
Operating system: Windows 10 
IDE: Visual Studio 2017 15.9.21

**Comment by ErikEJ** [comment]
Have you tried VS 2019?

**Comment by gphillip98** [comment]
VS 2019 doesn't see the Oracle provider when I try to create a new connection.

**Comment by ErikEJ** [comment]
You need this: https://www.oracle.com/database/technologies/dotnet-odtvsix-vs2019-downloads.html (Nuget packages in your project has no effect on the VS designers/tools)

**Comment by gphillip98** [comment]
I'll give it a try, thanks!

**Comment by gphillip98** [comment]
VS 2019 works!  I suspect VS 2017 would also work with the updated vsix for 2017.
