### ISSUE TITLE
Adding a relationship with an entity which is in the Deleted state is not allowed

### ISSUE THREAD

**Issue by Mamikel** [dotnet/ef6#1640]
This is my second attempt to get to the bottom of this.  
I have tried creating a brand new project from scratch and recreating the model and performing this function and cannot reproduce the issue.  Perhaps this issue is due to something awry in the migrations - there are 11 migrations in the project, most of which are the result of dozens of changes to the model.

On my webpage, a user is able to change the selected consultant and can add up to 5 consultants.
But by way of a simple example,  in this case, the user is just changing the first consultant (though the error also occurs if they try to change or delete any of the consultants.

When they change the consultant and click save, 
a) I remove the old relationship
consultationType1.Consultations.Consultants.RemoveAt(0);
b) then add the new relationship
var consultant = db.Consultants.First(c => c.Id == consultantId);
consultationType1.Consultations.Consultants.Add(consultant);

I then want to capture the change in an audit table so I've added an overloaded Save method to my calls (which inherits from the DbContext) in which I call
context.ChangeTracker.DetectChanges();

This is throwing an error:
**'Adding a relationship with an entity which is in the Deleted state is not allowed.'**
The error doesn't even include which relationship the EF has a problem with which is a major issue for complex object models.  But further, I'm wondering if it's an internal issue with how the EF is seeing the relationship which is causing the problem.  The bizarre thing is I'm doing the same thing in another form consultationType2 with the only difference being that it uses it's own parallel set of objects (and resulting tables in the database) and the error doesn't occur.

**N.B.** If I do not call context.ChangeTracker.DetectChanges() the record saves fine.  

Perhaps this means there's an issue somewhere in how the EF "sees" the relationship in the first case.  But even so, why is the EF throwing an error here?  Why isn't this causing an issue with the actual saving of the data?  

**If you are seeing an exception, include the full exceptions details (message and stack trace).**
```
**Exception message:**
Stack trace:
"   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectConflicts(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Core.Objects.ObjectContext.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Infrastructure.DbChangeTracker.DetectChanges()
   at App.Models.DbContextExtensions.GetRelationshipChanges(DbContext context) in ...\Models\DBContextExtensions.cs:line 58
   at App.Models.Entities.SetAudit[T](FormType formType, FormActionType actionType, T entity) in ...\Models\Entities.cs:line 431
   at App.Models.Entities.SaveChanges[T](FormType formType, T form, Boolean auditChanges) in ...\Models\Entities.cs:line 322"
```

**## Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.**
Unsure how I can provide the whole code base - I work for a government organisation.  

**### Further technical details**
EF version: 6.4.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.1

**Comment by Mamikel** [comment]
This issue appears to creep in after several iterations of making changes, reversing them and then making the changes again.  So it may not be specific to the DetectChanges call, but because the EF gets it's version of the model mixed up.  So perhaps a "fix" would be if anyone can advise how to reset the EF's internal representation of the model.  Any ideas?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by iqoOopi** [comment]
got the same error when just call entity.removeRange....

**Comment by primate-rick** [comment]
@Mamikel https://terrancezation.github.io/IQdKPeTnD5IfeeAlI9a_gOZRBp8gTHijh9_riZuvOdxXRg_PvlU_3Gs/
