### ISSUE TITLE
Database first and default user schema

### ISSUE THREAD

**Issue by GiuseppePoerio** [dotnet/ef6#1641]
I am using EF6, database first approach in a C# client application.
The database is on a Sql Server Express (>2012) instance.
The connection string requires instance name, database name, user name ... but no the schema used by the user.
I discovered that the schema is emebedded in the edmx file.
If it changes for the user on the Sql Server instance I'll have to update the edmx file.
Could you suggest me some tips to solve this problem?
I would like to change my application in order to use the DEFAULT schema used/configured by the user on the Sql Server instance.
I read something related to the overriding OnModelCreating(modelBuilder) and using DbModelBuilder.HasDefaultSchema.
But, my Entities inherits from ObjectContext and not from DbContext.

### Further technical details
EF version: EF6
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2019

**Comment by ErikEJ** [comment]
Maybe https://stackoverflow.com/q/2663164/183934

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
