### ISSUE TITLE
instance not released when they are part of a projection

### ISSUE THREAD

**Issue by cyrildurand** [dotnet/ef6#1642]
When I use an instance in a projection, this instance will stay in memory even after releasing the associated context and running `GC.Collect()`.

Let's consider the following code : 

```
void Do()
{
    // BigObject is a custom class that allocate a large array
    BigObject b = new BigObject(100 * 1024 * 1024);

    using (FooContext c = new FooContext())
    {
        var q = c.Foos
                      .Select(o => new { o.FooId, IsValid = b.Name == "test" })
                      .ToList();
        q.ToList();
    }
}
```

`BigObject` will stay in memory for the whole application lifetime. I try to release memory using `GC.Collect()` but the memory is still not released

My whole test code is the following : 

    class Program
    {
        static void Main(String[] args)
        {
            Collect("init");
            Do();
            Collect("before app exit");
        }
        static void Do()
        {
            BigObject b = new BigObject(100 * 1024 * 1024);
            Collect("after bigObject init");

            using (FooContext c = new FooContext())
            {
                var q = c.Foos
                              .Select(o => new { o.FooId, IsValid = b.Name == "test"})
                              .ToList();
                q.ToList();
            }

            Collect("before Do exit");
        }

        static void Collect(String message)
        {
            Console.WriteLine("{0} - before collect - {1:N0} ko", message, Process.GetCurrentProcess().PrivateMemorySize64 / 1024);
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.WaitForFullGCComplete(-1);
            GC.Collect();
            Console.WriteLine("{0} - after collect - {1:N0} ko", message, Process.GetCurrentProcess().PrivateMemorySize64 / 1024);
        }
    }

    public class FooContext : DbContext
    {

        public FooContext()
        : base("Server=.;Database=Test;Trusted_Connection=True;")
        {
            this.Database.CreateIfNotExists();
        }

        public virtual IDbSet<Foo> Foos { get; set; }
    }

    public class Foo
    {
        public Int32 FooId { get; set; }
        public String Name { get; set; }
    }

    class BigObject
    {
        public BigObject(Int32 size)
        {
            Byte[] data = new Byte[size];

            Unsafe.InitBlock(ref data[0], (Byte)'a', (uint)size);
            this.Data = data;
            this.Name = Guid.NewGuid().ToString();
            this.IsValid = this.Name.StartsWith("1");
        }

        public Byte[] Data { get; private set; }
        public String Name { get; private set; }
        public Boolean IsValid { get; private set; }
    }

and the output is : 

```
init - before collect - 8,836 ko
init - after collect - 8,932 ko
after bigObject init - before collect - 114,616 ko
after bigObject init - after collect - 114,608 ko
before Do exit - before collect - 133,712 ko
before Do exit - after collect - 133,776 ko
before app exit - before collect - 133,776 ko
before app exit - after collect - 133,776 ko
```

if I change the query to 

```
var q = c.Foos
              .Where(f => f.Name == b.Name)
              .ToList();
```

The memory is released 

```
init - before collect - 8,872 ko
init - after collect - 8,968 ko
after bigObject init - before collect - 114,588 ko
after bigObject init - after collect - 114,580 ko
before Do exit - before collect - 133,856 ko
before Do exit - after collect - 31,312 ko
before app exit - before collect - 31,312 ko
before app exit - after collect - 31,312 ko
```

If I run the `Do` method multiple time, only the first instance stay in memory

I looked at the memory before the application exit (after the last Collect method call) 

![image](https://user-images.githubusercontent.com/2543836/79002908-c40d6100-7b51-11ea-9350-243f40f77a38.png)

The object seems to be associated to the `DbCompiledModel`, it's like if the object is used for the query execution plan. 

I try to disable the PlanCaching for this query, but I could not find a way to do it with `DbSet`. I use the `GetObjectQuery` method provided here : https://stackoverflow.com/questions/38124984/entity-frameworks-6s-objectquery-enableplancaching-where-is-it but the object is still stuck with `DbCompiledModel`

I could not find a related issue for this behavior. Is it a known issue ? 

I find this issue while I try to understand a *memory leak* on a large ASP.net project. This kind of query is common in the solution and it will be difficult to change all of them. How can I bypass this behavior ? 

I think an expression visitor could *fix* this but I'm still not sure to fully understand what should I rewrite. 

### Further technical details
EF Version : 6.4 (latest) - same result with 6.2
Database Provider: EntityFramework.SqlServer

All tests were done in release mode 

I try with EF Core (latest) and the problem is not present.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by GabrielHSFerreira** [comment]
> When I use an instance in a projection, this instance will stay in memory even after releasing the associated context and running `GC.Collect()`.
> 
> Let's consider the following code :
> 
> ```
> void Do()
> {
>     // BigObject is a custom class that allocate a large array
>     BigObject b = new BigObject(100 * 1024 * 1024);
> 
>     using (FooContext c = new FooContext())
>     {
>         var q = c.Foos
>                       .Select(o => new { o.FooId, IsValid = b.Name == "test" })
>                       .ToList();
>         q.ToList();
>     }
> }
> ```
> 
> `BigObject` will stay in memory for the whole application lifetime. I try to release memory using `GC.Collect()` but the memory is still not released
> 
> My whole test code is the following :
> 
> ```
> class Program
> {
>     static void Main(String[] args)
>     {
>         Collect("init");
>         Do();
>         Collect("before app exit");
>     }
>     static void Do()
>     {
>         BigObject b = new BigObject(100 * 1024 * 1024);
>         Collect("after bigObject init");
> 
>         using (FooContext c = new FooContext())
>         {
>             var q = c.Foos
>                           .Select(o => new { o.FooId, IsValid = b.Name == "test"})
>                           .ToList();
>             q.ToList();
>         }
> 
>         Collect("before Do exit");
>     }
> 
>     static void Collect(String message)
>     {
>         Console.WriteLine("{0} - before collect - {1:N0} ko", message, Process.GetCurrentProcess().PrivateMemorySize64 / 1024);
>         GC.Collect();
>         GC.WaitForPendingFinalizers();
>         GC.WaitForFullGCComplete(-1);
>         GC.Collect();
>         Console.WriteLine("{0} - after collect - {1:N0} ko", message, Process.GetCurrentProcess().PrivateMemorySize64 / 1024);
>     }
> }
> 
> public class FooContext : DbContext
> {
> 
>     public FooContext()
>     : base("Server=.;Database=Test;Trusted_Connection=True;")
>     {
>         this.Database.CreateIfNotExists();
>     }
> 
>     public virtual IDbSet<Foo> Foos { get; set; }
> }
> 
> public class Foo
> {
>     public Int32 FooId { get; set; }
>     public String Name { get; set; }
> }
> 
> class BigObject
> {
>     public BigObject(Int32 size)
>     {
>         Byte[] data = new Byte[size];
> 
>         Unsafe.InitBlock(ref data[0], (Byte)'a', (uint)size);
>         this.Data = data;
>         this.Name = Guid.NewGuid().ToString();
>         this.IsValid = this.Name.StartsWith("1");
>     }
> 
>     public Byte[] Data { get; private set; }
>     public String Name { get; private set; }
>     public Boolean IsValid { get; private set; }
> }
> ```
> 
> and the output is :
> 
> ```
> init - before collect - 8,836 ko
> init - after collect - 8,932 ko
> after bigObject init - before collect - 114,616 ko
> after bigObject init - after collect - 114,608 ko
> before Do exit - before collect - 133,712 ko
> before Do exit - after collect - 133,776 ko
> before app exit - before collect - 133,776 ko
> before app exit - after collect - 133,776 ko
> ```
> 
> if I change the query to
> 
> ```
> var q = c.Foos
>               .Where(f => f.Name == b.Name)
>               .ToList();
> ```
> 
> The memory is released
> 
> ```
> init - before collect - 8,872 ko
> init - after collect - 8,968 ko
> after bigObject init - before collect - 114,588 ko
> after bigObject init - after collect - 114,580 ko
> before Do exit - before collect - 133,856 ko
> before Do exit - after collect - 31,312 ko
> before app exit - before collect - 31,312 ko
> before app exit - after collect - 31,312 ko
> ```
> 
> If I run the `Do` method multiple time, only the first instance stay in memory
> 
> I looked at the memory before the application exit (after the last Collect method call)
> 
> ![image](https://user-images.githubusercontent.com/2543836/79002908-c40d6100-7b51-11ea-9350-243f40f77a38.png)
> 
> The object seems to be associated to the `DbCompiledModel`, it's like if the object is used for the query execution plan.
> 
> I try to disable the PlanCaching for this query, but I could not find a way to do it with `DbSet`. I use the `GetObjectQuery` method provided here : https://stackoverflow.com/questions/38124984/entity-frameworks-6s-objectquery-enableplancaching-where-is-it but the object is still stuck with `DbCompiledModel`
> 
> I could not find a related issue for this behavior. Is it a known issue ?
> 
> I find this issue while I try to understand a _memory leak_ on a large ASP.net project. This kind of query is common in the solution and it will be difficult to change all of them. How can I bypass this behavior ?
> 
> I think an expression visitor could _fix_ this but I'm still not sure to fully understand what should I rewrite.
> ### Further technical details
> 
> EF Version : 6.4 (latest) - same result with 6.2 Database Provider: EntityFramework.SqlServer
> 
> All tests were done in release mode
> 
> I try with EF Core (latest) and the problem is not present.

Hi @cyrildurand. Looks like I have the same problem that you. Did you find any solution?

**Comment by cyrildurand** [comment]
Hi @GabrielHSFerreira 

I could not find any easy way to bypass the issue.

I worked only few days on this project to improve performance and found this memory leak related to EF. Because this leak was not that big we didn't go further. I guess we can write some kind of visitor to cancel this behavior but I didn't worked on it.
