### ISSUE TITLE
Add-Migration InitialCreate –IgnoreChanges EF Core does not work

### ISSUE THREAD

**Issue by Lequoa** [dotnet/ef6#1644]
As per Microsoft documentation, the command "**Add-Migration InitialCreate –IgnoreChanges**" should help me to enable database migration of an existing database, as I wanna go code-first migration route. But when I try to run the command on Package Manager Console it gives me the below error:

![image](https://user-images.githubusercontent.com/15086066/79055194-5ba2aa80-7c4b-11ea-8bc2-ed940317ce48.png)

### Further technical details or Dependencies
![image](https://user-images.githubusercontent.com/15086066/79055260-e5527800-7c4b-11ea-9cb1-aea8459865a4.png)

Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2019 16.4.1)

Please help me out.

**Comment by peymanr34** [comment]
> This repository is for the Entity Framework 6 runtime and Visual Studio tools. Entity Framework Core is maintained at https://github.com/dotnet/efcore.

To answer your question EF Core doesn't support `–IgnoreChanges` at the moment see https://github.com/dotnet/efcore/issues/2167#issuecomment-232204499

**Comment by sam17896** [comment]
is it still not supported as its mention here?
https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/existing-database

**Comment by msvmelo** [comment]
Realmente o comando IGNORECHANGES não existe. Como eu fiz e deu certo?
- Gere a migration inicial 
- Abra o arquivo .CS , retire todo o código do UP e DOWN e dê um update. Ele irá gravar um registro no History. 
- Quando gerar nova migration, ele irá criar apenas com o que não foi atualizado entre código e base de dados.
