### ISSUE TITLE
Nuget: Unable to migrate from EF 6.2 ru to EF 6.4

### ISSUE THREAD

**Issue by lefig** [dotnet/ef6#1645]
Hi there,

It seems there is still a version compatibility problem and I was hoping that this has been fixed.

Possibly related to:
nuget fails #1525

Thanks

Fig

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
