### ISSUE TITLE
An approach to testing SaveChanges with Entry

### ISSUE THREAD

**Issue by KevinBurton** [dotnet/ef6#1646]
I have used this [page](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking) to test most of my access to the DB that uses EF. However When I want to modify or update a row I have the code:

```
				DbContext.Entry(creditCard).State = EntityState.Modified;
				var response = DbContext.SaveChanges();

```
that I naturally want to find a way to test. But using this doesn't seem to have a solution for mocking or otherwise faking the method call to Entry. I have started with these lines in my unit test:
```
			var dbCreditCardEntity = new DbEntityEntry<CreditCard>();
			mockChangepointAuxDbContext.Setup(m => m.Entry(It.IsAny<CreditCard>()))
									   .Returns(dbCreditCardEntity);
 
```

But I get an error constructing the DbEntityEntry indicating that there isn't a parameterless constructor and I should get this value from the Entity or Entities. 
I am not sure how to do this. But maybe I am pursuing the wrong approach. Is all I want to do setup a test so that DbContext.Entry(creditCard).State = EntityState.Modified; always succeeds?

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.3

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
