### ISSUE TITLE
How do I access the resource-file version of an entity model's MSL file/XML?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1648]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/981449/how-do-i-access-the-resource-file-version-of-an-en.html)._

---
<p><strong>WHAT I HAVE:</strong></p><p>Visual Basic 2019, .NET 4+, WinForms, Entity Framework</p><p><strong>MY PROBLEM:</strong></p><p>I've found that it's often convenient to be able to <em>programmatically convert</em> between the entity/property names of the conceptual EF model and the corresponding table/field names of the store model. If one wants to do SQL for, say, creating additional indexes on an entity's table, if the EF and/or store model is very complex, or if one is frequently changing the relationship between the 2 models, then having a tool to discover the mapping between the conceptual and the store is very useful, as EF doesn't directly expose the MSL mapping info in the EF object heirarchy!</p> <p>The <em>good</em> news is that I've created a tool that, given an entity name and a property-expression name, returns the corresponding table and field names, by parsing the XML of the MSL file. The <em><strong>bad</strong></em> news is that it depends on the model opting to copy the MSL, CSDL, and SSDL files to the Output Directory. What if the EF model doesn't do this? Then one has to find the XML data in the resource files!</p> <p>I'd like a function that, given the &quot;res://<em>model</em>.csdl|res://<em>model</em>.ssdl|res://<em>model</em>.msl&quot; info, returns the file, or the XML data, with the MSL (or, for that matter, the CSDL or SSDL) information.</p> <p>Please give me someting ASAP, and <em><strong>in VB</strong></em>!</p> <hr>
<p><br>Robert Gustafson</p>

---
#### Visual Studio Feedback System on 4/8/2020, 00:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by lajones** [comment]
I think if you look at the code in [MetadataArtifactLoader](https://github.com/dotnet/ef6/blob/master/src/EntityFramework/Core/Metadata/Edm/MetadataArtifactLoader.cs) and its sub-classes you'll find what you need.

**Comment by RobertAlanGustafsonII** [comment]
1. Can I convert this code to VB? (My project is in VB.NET 2019.)
2. Which methods should I use to get the MSL XML? (There's no "example".)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
