### ISSUE TITLE
Database Exists Still Called If NullDatabaseInitializer Is Used

### ISSUE THREAD

**Issue by mike-card** [dotnet/ef6#1651]
We've found an issue with using EF and the NullDatabaseInitializer - we came across the issue in our move to Azure, everything worked okay with our on-premise SQL server because the guest account is enabled and allows you do the database check without error. On Azure, guest is disabled and the database check fails (causing a 10 second delay (https://github.com/dotnet/ef6/issues/148)).

We've always used the NullDatabaseInitializer on our production versions and handled migrations ourselves and we thought that the NullDatabaseInitializer shouldn't do the database exists check, but somewhere in the code is still seems to call the database exists function which then causes the delay.

The only way for us to solve the issue until the 10 second delay is fixed is to add public access to master for all of our EF user accounts.

Can the database exists check be eliminated if the NullDatabaseInitializer is used?

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.4

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
