### ISSUE TITLE
I am getting an error which i was not getting before today. Entity framework model is not updating for MySql

### ISSUE THREAD

**Issue by AlpaBa** [dotnet/ef6#1652]
![entity framework error](https://user-images.githubusercontent.com/47463676/80044988-bfd73100-84cb-11ea-8535-df56fa179355.JPG)
![entity framework error](https://user-images.githubusercontent.com/47463676/80044997-c796d580-84cb-11ea-8160-4c0cfe9c1a51.JPG)

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF version: (found in project.csproj or packages.config)
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by AlpaBa** [comment]
I am using Microsoft Visual Studio 2019.

**Comment by RyanJMcGowan** [comment]
Are you running Entity Framework in a .Net Core project? EF6 has a dependency on DbProviderFactories that is not in .Net Core that would give you an error like that.

If this is the case, you may want to [look at this workaround](https://weblog.west-wind.com/posts/2017/nov/27/working-around-the-lack-of-dynamic-dbproviderfactory-loading-in-net-core).

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
