### ISSUE TITLE
Slow materialization of objects that contain collections.

### ISSUE THREAD

**Issue by briangsweeney** [dotnet/ef6#1655]
I've become convinced that the slowest portion of my LINQ to Entities query is materializing the result set into my view model.  I've measured the time to execute the SQL query against the server, the network I/O time, the time to generate the SQL statement from the IQueryable, leaving from what I gather, only the time required to project the result set onto a collection of objects (a collection of my view model).

My view model is perhaps non-trivial.  It is mostly a POCO consisting of members of various primitive types, however, it does include several collections over other objects or primitive types.

Removing those members from the view model, yields the biggest performance gains I've managed to achieve, and seems to account for upwards of 70% of the time consumed starting at building up the `IQueryable` all the way through returning useful objects via calling `ToList()`: indeed it's the execution of `ToList()` that consumes practically all of the time.

FWIW, I've disabled tracking by way of calling `AsNoTracking()`.  I have not attempted to precompile the query, as I am led to understand that this really only improves the time it takes to generate a SQL statement and I don't believe this is the major hold up for me.  Similarly, I've not yet tried to pre-generate mapping views, as constructing the object context does not seem to be a major bottleneck either.

I have seen discussion suggesting that the best approach to dealing with this class of problem is to be sure that you are projecting onto the minimum set of data required from your result set such that the number of members that need to be mapped from the result set to the view model is minimized.  This has indeed yielded sizable performance gains, but not quite enough for us to be satisfied.

To be clear, I'm not selecting all that much data.   I'm projecting my result set onto a view model with maybe 20 members.  Only about 4 of them are collections.  Three of those are collections of int (`IEnumerable<int>`) or some other primitive, and one of them is a collection of a very simple (two primitive members) object (`IEnumerable<MyPoco>`)  The query is bounded at 15 rows.  As far as SQL is concerned, we are actually selecting 15 * some small factor due to the number of results which we may find in the joined data used to populate the aforementioned collections, but still, we're talking about a pretty trivial amount of data.  I guess that the slow-down is in assigning some of the data to the collections, or in determining the runtime type of those collections or constructing those collections for each item in the result set, or something of that sort.

Apart from not selecting more data than you need, I have not seen any reason why this should take as long as it does.  I have observed a few people on the internet who may be suffering from the same problem, but it's hard to be certain.

Here is my story on StackOverflow, for posterity: https://stackoverflow.com/questions/61396676/projecting-ef-result-sets-onto-complex-object-model-is-slow

Here are a couple of issues which I believe may be the same thing:
https://stackoverflow.com/questions/31725010/linq-slowness-materializing-complex-queries?rq=1
https://stackoverflow.com/questions/29102923/entity-framework-gets-progressively-slow-with-extra-join-added-even-though-sql-g?rq=1

The accepted solution in both of the above issues is to simplify the query or result set, neither of which seems to get at the root issue.

Is this expected behavior and if so is there some workaround I've not considered?  If it is not expected behavior, is it something that might be fixed eventually?

### Steps to reproduce
Here is what I believe to be a representative code sample.  If this is not sufficient for reproducing or understanding the issue, I will have to concoct a new solution.

```c#
public class MyBusinessObject {

    public int SomeMember {get;set;}
    public double SomeOtherMember {get;set;}
    //more primitive members here

    public IEnumerable<int> MyList {get;set;}
    //more collections here
}

//query is dynamically generated and will be considerably more complicated than this...
//...(more joins and inner selects), but it's bounded, and the runtime is acceptable to me
IQueryable<MyDbSetEntity> query = myContext.MyDbSet.Join(...).Where(...).OrderBy(...).Skip(...).Take(...).AsNoTracking();

IQueryable<MyBusinessObject> model = query.Select(myEntity => new MyBusinessObject {
    SomeMember = myEntity.SomeMember,
    SomeOtherMember = myEntity.SomeOtherMember,
    MyList = myEntity.MyList
});

//this is the line that takes forever - I have determined that walking the expression tree,...
//...generating the SQL, running the SQL, returning the data over the wire are all not implicated...
//...in the majority of the time spent with maybe a second spent on all of the aforementioned,...
//...and the remaining 5 or seconds spent building the list of objects.
List<MyBusinessObject> objects = model.ToList();
```

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10, but the same performance is witnessed when the app is deployed to Azure Cloud
IDE: Visual Studio 2013

**Comment by tccf1109** [comment]
Hello, I'm encountering the same problem. The query takes not more than 27 ms to retrieve information, but the materialization takes up to 30 seconds for that data. Did you encounter a solution to the problem ?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
