### ISSUE TITLE
Insufficient information when exception is thrown

### ISSUE THREAD

**Issue by mortensp** [dotnet/ef6#1657]
I have a problem in my code where one of the key properties on an entity is changed. That an error in my code, but all i get from the exception thown is something like: Key property 'TableNo" cannot be changed. As there are close to 600 entities tracked at the time, it's impossible to narrow down.

My suggestion is that you in:  
file:         EntityEntry.cs 
method: DetectChangesInProperty
Code:              throw new InvalidOperationException(Strings.ObjectStateEntry_CannotModifyKeyProperty((object) managerMemberMetadata.CLayerName));

Here you should atleast supply the EntitySetName and maybe the original key values!

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
