### ISSUE TITLE
Migration files are not being added to the project automatically

### ISSUE THREAD

**Issue by Manikese** [dotnet/ef6#1658]
Files created from "add-migration" are not being added to the project file.

### Steps to reproduce

Enter Package Manager Console.  Then type:
PM> add-migration "Test Migration"
Scaffolding migration 'Test Migration'.
The Designer Code for this migration file includes a snapshot of your current Code First model. This snapshot is used to calculate the changes to your model when you scaffold the next migration. If you make additional changes to your model that you want to include in this migration, then you can re-scaffold it by running 'Add-Migration Test Migration' again.

At this point it basically freezes.  I'm able to use all other parts of Visual Studio, just not the Package Manager Console.  The "PM> " never comes back.  Even clicking Stop Command Execution, doesn't get to a state when key presses result in any characters being output to the window. 

I've checked to make sure the project file isn't read only.  I've also restarted my machine to make sure my outside agents were negatively affecting my environment. 

This happens every time I try to do an add-migration.

What could this be?

I can add the migration files to the project manually afterward.  Then I run update-database and that finishes successfully:

PM> update-database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [202004281543231_Test Migration].
Applying explicit migration: 202004281543231_Test Migration.
Running Seed method.
PM> 

Any feedback is greatly appreciated.  I hope you all are safe and healthy.

Best regards,
-Jeff

### Further technical details

EF version:  EF 6.0.0.0
Package Manager Console Host Version 5.4.0.6292
Database provider: Microsoft SQL Server:  MSSQL14.MSSQLSERVER (14.0.1000.169)
Target framework: .NET 4.6.2
Operating system:  Windows 10 Enterprise
IDE:  Microsoft Visual Studio Professional 2019 (Version 16.4.1)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
