### ISSUE TITLE
Where is the latest source code of migrate.exe?

### ISSUE THREAD

**Issue by zsong** [dotnet/ef6#1661]
https://github.com/dotnet/ef6/commit/d9b3ba7f8b082c6226cde152c37b3a73e125a753#diff-25d902c24283ab8cfbac54dfa101ad31

I see it got deleted from this commit. But where is the code moved to?

Thank you!

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
