### ISSUE TITLE
Generating a migration script with custom SQL breaks if DbMigration has LF line endings

### ISSUE THREAD

**Issue by skiplax** [dotnet/ef6#1664]
Describe what is not working as expected.

We force LF line endings for our repository.  Sometimes when we generate migrations we add custom SQL (for example when inserting some data into a newly created table.)  This in conjunction with verbatim literal strings as in:

```
Sql(@"
-- Some command;
-- Some other command;
-- Some ...
--     multiline ...
--         command;
");

```
When this combination is used, and you try to generate a migration script, the generated migration script is incomplete.  Depending on where the LF's are, the script can hop back and forth between outputting into the unsaved generated SqlQuery_1.sql file and the Package Manager Console window.

Neither the SqlQuery_1.sql script nor the output to the Package Manager Console is complete!  Running either one as your migration can leave your database in an incorrect state!

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

// Create a model:

```
namespace BugReport
{
	public class Test
	{
		public int Id { get; set; }

		public string Name { get; set; }
	}
}
```

// Add to the database context:

`public DbSet<Test> Test { get; set; }`

// Generate the migration from the Package Manager Console:

`Add-Migration TestMigration`

// This will generate the migration script.
// We will add some custom SQL to it:

```
namespace PureChatDb.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class TestMigration : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Tests",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                    })
                .PrimaryKey(t => t.Id);

            // ==================================
            // Here we add some custom multi-line SQL.
            // This example is contrived, but it could be generating
            // a view or something more complex.
            // Note that we are using the verbatim literal string
            // and adding multiple lines of SQL. 
            // ==================================
            Sql(@"INSERT INTO [Tests] ([Name]) VALUES ('Test 1');
INSERT INTO [Tests] ([Name]) VALUES ('Test 2');
INSERT INTO [Tests] ([Name]) VALUES ('Test 3');
");
        }
        
        public override void Down()
        {
            DropTable("dbo.Tests");
        }
    }
}
```

// Ensure that the line break mode is of this file is set to LF !!!!!

// Next attempt to generate the migration script:

`update-database -script`

// Here is the output to the SqlQuery_1.sql script:

```
CREATE TABLE [dbo].[Tests] (
    [Id] [int] NOT NULL IDENTITY,
    [Name] [nvarchar](max),
    CONSTRAINT [PK_dbo.Tests] PRIMARY KEY ([Id])
)
INSERT INTO [Tests] ([Name]) VALUES ('Test 1');
INSERT [dbo].[__MigrationHistory]([MigrationId], [ContextKey], [Model], [ProductVersion])
VALUES (N'202005081800514_TestMigration', N'YourTest.Migrations.Configuration',  0x...<truncated> , N'6.4.0')
```

// Here is the output to the Package Manager Console window:

```
Applying explicit migrations: [202005081800514_TestMigration].
Applying explicit migration: 202005081800514_TestMigration.
INSERT INTO [Tests] ([Name]) VALUES ('Test 2');
INSERT INTO [Tests] ([Name]) VALUES ('Test 3');
```

// Notice that only the 1st INSERT statement got into the SqlQuery_1.sql file and
// the 2nd and 3rd INSERT statements got into the Package Manager Console window
// output.  Also note that the table creation and insert into the __MigrationHistory
// table did not get written to the Package Manager Console window.

// If you then go in and switch the line endings of the DbMigration file to CRLF, then
// all of the output goes to the SqlQuery_1.sql file and all is right with the world.

### Further technical details
EF version: 6.4.0
Database Provider: System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer
Operating system: Windows 10
IDE: Microsoft Visual Studio Enterprise 2019 Version 16.5.4

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
