### ISSUE TITLE
How to programmatically apply migrations with multiple DBContexts with different schemas

### ISSUE THREAD

**Issue by cargt3** [dotnet/ef6#1669]
For testing purposes i need to programmatically update local db to newest migrations. Problem is that i have 2 DBContexts with different schemas. When i try to use :

```
        var databaseMigrator = new DbMigrator(customMigrationConfiguration);

        databaseMigrator.Update();
```

I have error:

> Automatic migrations that affect the location of the migrations history system table (such as default schema changes) are not supported. Please use code-based migrations for operations that affect the location of the migrations history system table

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
