### ISSUE TITLE
When an AutomaticMigration is the final Migration of an update the Migration is timestamped which causes problems with later Explicit Migrations.

### ISSUE THREAD

**Issue by MichaelIRIS** [dotnet/ef6#1671]
In [DbMigrator.cs at line 590](https://github.com/dotnet/ef6/blob/master/src/EntityFramework/Migrations/DbMigrator.cs#L590-L609) there is a block of code that checks if the model is of date after applying the Explicit Migrations and if it is still Out of date it then creates an AutomaticMigration. This AutomaticMigration is named in MigrationAssembly.CreateMigrationId ([MigrationAssembly.cs line 14](https://github.com/dotnet/ef6/blob/master/src/EntityFramework/Migrations/Infrastructure/MigrationAssembly.cs#L14-L19)) with the current Date and Time.

The problem with this logic is that if a client installs a copy of the software in the future then this record will be timestamped with the current date and time. If another version of the software is installed in the future but there have been explicit migrations created in the meantime then the explicit migrations will be dated earlier then this automatic migration. The migration completes but the next time the system is restarted the migration code is confused as the AutomaticMigration is out of sequence and the update is repeated. This fails with a SQL Server generated error message relating to the update as it tries to reapply the migration. ( EG Column names in each table must be unique etc.)

A Worked Example

Version 1 is (finally) installed today at a client site with an AutomaticMigration as the final Migration. This is timestamped on 2020-05-13

Version 2 was under development while this was going on and in the meantime an Explicit Migration were added on 2020-04-13. When version 2 is finally installed the MigrationHistory will look as follows

[Other Migrations]
20200413ExplicitMigration
20200513AutomaticMigration 

instead of the correct sequence of 

[Other Migrations]
<MigrationTimeStamp>AutomaticMigration
20200413ExplicitMigration

What should happen is a variant of the logic in StringExtensions.ToAutomaticMigrationId ([StringExtension.cs line 82](https://github.com/dotnet/ef6/blob/master/src/Common/StringExtensions.cs#L82-L89)) so that the previous MigrationId has +1 added as opposed to ToAutomaticMigrationId's -1. This will ensure that the MigrationId is predictable as opposed to the current situation where the MigrationId Automatic Migrations is unpredicatable.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by MichaelIRIS** [comment]
Thanks for getting back to me but I'm really quite disappointed that you sat on this quite significant bug for 2 years when you had the precise lines of code where it occurred, and then closed it off because you are focussing on "stability". Surely a bug where the migrations will run in the wrong order is something that can significantly affect stability.
