### ISSUE TITLE
Changelog for EntityFramework 6.4.4?

### ISSUE THREAD

**Issue by MagicAndre1981** [dotnet/ef6#1672]
I can't find a changelog for [EntityFramework 6.4.4](https://www.nuget.org/packages/EntityFramework/6.4.4). What is new/fixed?

**Comment by ajcvickers** [comment]
@MagicAndre1981 Nothing. The new package was pushed in error by the build system. It has the same code as 6.4.0.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 Nothing. The new package was pushed in error by the build system. 

ok, thanks. Will this update be unpublished? Should we update to 6.4.4 (as there is no way to ignore the update in nuget UI in VS)?

**Comment by ajcvickers** [comment]
@MagicAndre1981 Updating should be fine if unnecessary.

**Comment by MagicAndre1981** [comment]
because [PackageReference misses the allowedVersions entry from packages.config](https://github.com/NuGet/Home/issues/6566), I've updated to 6.4.4 to get rid of the offered update.
