### ISSUE TITLE
HasChanges return true when the changed property values are reverted back to original values.

### ISSUE THREAD

**Issue by Hashira94** [dotnet/ef6#1674]
As describe in the title, when i revert the changed property values to the original ones, ChangeTracker.HasChanges doesn't return false but return true. 
EF Version: 6.4.0

**Comment by grammophone** [comment]
Confirmed with versions 6.2.0 and 6.4.4. The `PropertyEntry.IsModified` is true, but `OriginalValue` and `CurrentValue` are the same. Before 6.2.0 this wasn't the case; our code relying on `IsModified` broke later on.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
