### ISSUE TITLE
CreateDatabaseExistsScript fails for user without VIEW ANY DATABASE

### ISSUE THREAD

**Issue by dbrownems** [dotnet/ef6#1675]
Describe what is not working as expected.

When connecting to SQL Server with EF6 an initial connection is made to Master and the following query is run

```
IF db_id(N'ef6test') IS NOT NULL SELECT 1 ELSE SELECT Count(*) FROM sys.databases WHERE [name]=N'ef6test'
```
This query fails if the application is connected with a login that lacks VIEW ANY DATABASE unless that login is the owner of the database.  If the login is merely a member of DB_OWNER or has CONTROL in the target database this query will fail to reveal the existence of the database, because

```
db_id(N'ef6test')
```

will return NULL.  There is, in fact, no difference between the `db_id()` function and the metadata security applied in the `sys.databases` catalog view.  They will both reveal the existence of a database only when:

1) The login has VIEW ANY DATABASE
or
2) The login is the owner of the database
or
3) The database is Master or TempDb
or
4) The database is the current database

And option 4) is the only way for a non-owner without VIEW ANY DATABASE to discover the existence of a database.  

This is the code that generates the query, and the incorrect statement about `db_id()` is right there in the comments.
```
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "dbid")]
        [SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters",
            MessageId = "System.Data.Entity.SqlServer.SqlDdlBuilder.AppendSql(System.String)")]
        internal static string CreateDatabaseExistsScript(string databaseName)
        {
            // This handles non-SQL Azure servers by using db_id() which will return a non null value for
            // a database on the server even if the login doesn't have "view any database" permission.
            // On SQL Azure db_id() only works for the current database, which means it will never work here
            // because the current database is master. In this case we fall back to the query from sys.databases.
            // This doesn't work for non-SQL Azure if the login does not have 'view any database'
            // permission, but that case was covered by db_id(). On SQL Azure there are no server class
            // securables, which means it is not possible to deny the login 'view any database' so in theory
            // if the user can connect to master then the sys.databases query will work.

            var builder = new SqlDdlBuilder();
            builder.AppendSql("IF db_id(");
            builder.AppendStringLiteral(databaseName);
            builder.AppendSql(") IS NOT NULL SELECT 1 ELSE SELECT Count(*) FROM sys.databases WHERE [name]=");
            builder.AppendStringLiteral(databaseName);
            return builder.unencodedStringBuilder.ToString();
        }
```

### Steps to reproduce
Here's a TSQL script to demonstrate the behavior
```
use master
alter authorization on database::ef6test to sa
drop login appuser 
go
use master 

create login AppUser with password= 'a(*&908sd7f8d70897s341'
deny view any database to appuser
go
use ef6test
create user AppUser for login AppUser 
grant control to AppUser
go
use master
execute as login='appuser'
 select db_id(N'ef6test')  --null
revert

go
use ef6test
drop user appuser 
go
use master
alter authorization on database::ef6test to Appuser
go
use master
execute as login='appuser'
 select db_id(N'ef6test')  --works
revert

```

And the workaround is to make the app user the owner of the database

```
alter authorization on database::ef6test to Appuser
```

And here's an idea for how to detect the existence of a database that the connected login has access to, but is not the owner of without VIEW ANY DATABASE

```
if ServerProperty('EngineEdition') in (5,6) --Synapse SQL Pool or Azure SQL Database
begin
   SELECT Count(*) FROM sys.databases WHERE [name]=N'ef6test'
end
else
begin try
   exec ('use ef6test; select 1;')
end try
begin catch
  if error_number() = 911 --database does not exist
  begin
     select 0
     return;
  end;
  throw;
end catch

```

### Further technical details
EF version: (6.4)
Database Provider: (. EntityFramework.SqlServer)
Operating system: ( Windows 10) 
IDE: (. Visual Studio 2017 15.6)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
