### ISSUE TITLE
Copyright not included in the Apache 2 license file

### ISSUE THREAD

**Issue by delsolcrx1** [dotnet/ef6#1685]
Copyright not included in the license file. Line 189 is just the apache template.

https://github.com/dotnet/ef6/blob/master/LICENSE.txt

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
