### ISSUE TITLE
How to update nested object with relationships

### ISSUE THREAD

**Issue by tlucas1969** [dotnet/ef6#1686]
@Jenan Fundamentally, the issue is what the exception message says. The code creates multiple instances of Client and ClientScope with the same key values. Instead, the code needs to determine whether or not an instance already exists, and then use it if it does. A common way to do this is to query the database for entities and then make updates to the entities returned before calling SaveChanges.

Looking specifically at your test code, if I stop creating new instances for the same entity:
```C#
//Try add Client
var newClient = new Client() { ClientId = "Test", ClientName = "Test" }; //Primary key is Id, not ClientId
dbContext.Clients.Add(newClient);
dbContext.SaveChanges();

//Try add ClientScope for this client Id = 1
var newClientScope = new ClientScope() { Client = newClient, Scope = "Test Scope" };
dbContext.ClientScopes.Add(newClientScope);

dbContext.SaveChanges();

//Try update ClientScope name
newClientScope.Scope = "Test Scope 2";
dbContext.SaveChanges();
```
then it works as expected.

_Originally posted by @ajcvickers in https://github.com/dotnet/efcore/issues/9819#issuecomment-330926889_

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
