### ISSUE TITLE
Complex Types when all properties are optional cannot be null

### ISSUE THREAD

**Issue by junalmeida** [dotnet/ef6#1687]
Provided the following domain model:
```c#
public class Entity {
      public ComplexType ComplexType { get; set; }
}

public class ComplexType { 
     public int InnerProperty { get; set; } 
}
```

When adding a new instance of `Entity`, provided that `ComplexType` has all its inner properties as `Optional`, when `ComplextType` is `null` I get the following exception.

```
Exception message: System.Data.Entity.Core.UpdateException: 'Null value for non-nullable member. Member: 'ComplexType'.'
Stack trace:    at System.Data.Entity.Core.Mapping.Update.Internal.ExtractorMetadata.RetrieveMember(IEntityStateEntry stateEntry, IExtendedDataRecord record, Boolean useCurrentValues, EntityKey key, Int32 ordinal, ModifiedPropertiesBehavior modifiedPropertiesBehavior) in /_/src/EntityFramework/Core/Mapping/Update/Internal/ExtractorMetadata.cs:line 181
```
It seems to be very straightforward to assume that if the ComplexType property is null, than all mapped inner properties are also null (and then enforcing eventual Required properties if mapped as required). 

On the other way, when hydrating entities after selecting from the database, if all inner properties of a complex type are null, it makes sense to set the ComplexType itself to null. 

I believe that this is a good change on EF, since if implemented will avoid unnecessary changes to the domain. Changing the domain because of limitations on ORM is not good. A possible workaround would be a value converter (like EFCore has), so that we can convert primitive values into complex types or even simple enums. 

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
