### ISSUE TITLE
Running ef6 in an Azure DevOps task doesn't return error when stopped due to pending changes

### ISSUE THREAD

**Issue by arfmach** [dotnet/ef6#1692]
When using a release pipeline in Azure DevOps to deploy updates and having a "Command line" task to run `ef6.exe database update`, if there are any pending changes and automatic migration is disabled, ef6 issues a message to show that the error occurred but the return is successful, making the pipeline task succeed and the deploy keep executing until the end. It should return an error so that the deployment could be interrupted and the overall result marked as failed.

### Steps to reproduce
1. Create two EF migrations from the same point and put them into the project (can be done through two different git branches merged into master);
1. Define a release pipeline to deploy your build, containing a task that calls ef6.exe to update the database (marking the checkbox "Fail on Standard Error" doesn't help since ef6.exe seems to echo the error message on Standard Output);
1. Create a release and deploy your artifact to a target;
1. When reaching the migrate task, ef6 will output the error message, but the task will end as succeeded.

I've added an `echo ef6.exe errorlevel %ERRORLEVEL%` to the script to be sure ef6 was returning 0.
![image](https://user-images.githubusercontent.com/7331118/85180233-4e142d00-b259-11ea-9061-901767bf012c.png)

This is how the task is configured in the pipeline:
![image](https://user-images.githubusercontent.com/7331118/85180663-6173c800-b25a-11ea-963a-75594d7876ac.png)

### Further technical details
EF version: (6.4.4)
Database Provider: (EntityFramework.SqlServer)
Operating system: (Windows 10) 
IDE: (Visual Studio 2019)

**Comment by ErikEJ** [comment]
Add a unit test to avoid pending changes.

**Comment by arfmach** [comment]
> 
> 
> Add a unit test to avoid pending changes.

Ok, that may be a workaround, but ef6 should fail under that condition.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
