### ISSUE TITLE
Milestone 6.4.3 is not closed

### ISSUE THREAD

**Issue by martijnhoekstra** [dotnet/ef6#1694]
In this repository, version milestones tend to get closed when they are delivered. However, the milestone for 6.4.3 is not closed. This makes finding the closed tickets for closed milestones more difficult.

### Steps to reproduce

Go to https://github.com/dotnet/ef6/milestone/16

Observe it's not closed

### Further technical details
N/A

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
