### ISSUE TITLE
Can't get DbMappingViewCache to cache my views

### ISSUE THREAD

**Issue by McDoit** [dotnet/ef6#1695]
I'm building a AWS Lambda with dotnet core 3.1 and testing it out locally
To improve performance i wanted to precompile the views following this guide:
https://docs.microsoft.com/en-us/ef/ef6/fundamentals/performance/pre-generated-views

I have created my own `DbMappingViewCache` called `DbMappingViewCacheImp` and hooked it up with `[assembly: DbMappingViewCacheType(typeof(MyContext), typeof(AWSLambda1.DbMappingViewCacheImp))]`

But when im debugging and trying to see what happens, the code in `public override DbMappingView GetView(EntitySetBase extent)` never fire and i can see on the execution time that it builds the views on the first query

Am I missing something here?

### Steps to reproduce
Add this class in your AWS Lambda function with `[assembly: DbMappingViewCacheType(typeof(MyContext), typeof(AWSLambda1.DbMappingViewCacheImp))]`

Breakpoints in `MappingHashValue` and `GetView` but neither will get hit

```c#
    public class DbMappingViewCacheImp : DbMappingViewCache
    {
        public override string MappingHashValue => "";

        public override DbMappingView GetView(EntitySetBase extent)
        {
            return null;
        }
    }
```

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework6.Npgsql
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
