### ISSUE TITLE
InitializeDatabase Example

### ISSUE THREAD

**Issue by martingbrown** [dotnet/ef6#1697]
This is a virtual method that developers have to override to do what they want. It would be handy if there was a bit more instruction about what the caller is expecting from the code, which parts of the DB need to be initialised. Maybe an example of an overridden version might help. This may be described somewhere else in the documentation as a how-to, if so I can't find it and a link in the 'see also' section would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1ba973-5471-9563-d145-81ba863e5b49
* Version Independent ID: 1aea9174-9255-ca1c-c7df-a235786b623f
* Content: [DropCreateDatabaseAlways&lt;TContext&gt;.InitializeDatabase(TContext) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dropcreatedatabasealways-1.initializedatabase?view=entity-framework-6.2.0#System_Data_Entity_DropCreateDatabaseAlways_1_InitializeDatabase__0_)
* Content Source: [EF/xml/System.Data.Entity/DropCreateDatabaseAlways`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DropCreateDatabaseAlways`1.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
