### ISSUE TITLE
Updating database via Update-Package command with "lf" line endings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1699]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1082137/updating-database-via-update-package-command-with.html)._

---
Hello

We recently updated our project to Entity Framework 6.4.4 (was 6.2) and noticed that the Update-Database command changed its output, which should be ok since it still does its job.

However, we are importing SQL files on some migrations. When we launch the Update-Database command during development, the content of theses SQL is shown in the output (without using -Verbose), and the fact that the content is displayed in the console is slowing drastically the update process and prevents us from adding migrations. It has gone from around the 30s to almost 15mins to update in development.
Theses SQL files are currently encoded with lf line endings, and we noticed that when they are encoded with crlf line endings, the content is not updated and the issue is not occurring.

We are currently looking for a solution to force crlf on SQL file to our git repo, but is there any solution at Visual Studio side to prevent the output ?

Thanks for the help,
Jules

---
#### Visual Studio Feedback System on 6/18/2020, 03:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
