### ISSUE TITLE
EF EDMX From Database "Object reference not set..."

### ISSUE THREAD

**Issue by Ya-Wang** [dotnet/ef6#1701]
Using Add > ADO.NET Entity Data Model

Microsoft Visual Studio Enterprise 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752 

Please see included screen shot.
 
![Capture](https://user-images.githubusercontent.com/3073708/86125061-0dfb4880-baaa-11ea-9027-d8a3b9f5866d.PNG)

Any ideas?

Works fully in VS2017. And is fully fuctional (can update) after creation using VS2017.

**Comment by ErikEJ** [comment]
When in the process do you get this error - in other words, more detailed repro steps, please.

**Comment by Ya-Wang** [comment]
Reproduce by,

1. Right clicking on project 
![image](https://user-images.githubusercontent.com/3073708/86139424-b6ff6e80-babd-11ea-9ae5-adaf5c64d55f.png)


2. Add ADO.NET Entity Data Model 
![image](https://user-images.githubusercontent.com/3073708/86139511-d5fe0080-babd-11ea-87a2-98165dac3b29.png)

3. EF Designer from Database 
![image](https://user-images.githubusercontent.com/3073708/86139593-edd58480-babd-11ea-9ccd-5c3a21fbbc3f.png)

4. Just pick a sql server and next 
![image](https://user-images.githubusercontent.com/3073708/86139768-1eb5b980-babe-11ea-871b-d22cef956d74.png)

5. Pick any table. 

6. Error, emdx files empty but created.

**Comment by SSDiver2112** [comment]
I have been working on this and searching for an answer the past couple of days. I have deleted and recreated the edmx files many times rebuilding and restarting etc. trying to find a magic combination. The files below are created, but not the .tt files.

![image](https://user-images.githubusercontent.com/26187611/86142855-afda5f80-bac1-11ea-8f8d-c3ed77cc6843.png)

Double clicking the edmx file returns one of these two messages. 

![image](https://user-images.githubusercontent.com/26187611/86142915-c385c600-bac1-11ea-88bf-e82575378cd6.png)
or
![image](https://user-images.githubusercontent.com/26187611/86143005-e3b58500-bac1-11ea-8e52-04e0f9cd14af.png)
 
The .tt files can be made, but only from the designer, which won't open. I did this last week and everything was working Friday. Monday I needed to make some changes and now the edmx is incomplete and nothing will work anymore.

-----------------------------------------------------------------------------

Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 3.1
VisualStudio.16.Preview/16.7.0-pre.3.1+30223.230
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.392.237
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2030908+50b4350fabebe02aa08844cd3c1fa2a490107f5f
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.392.237
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.392.237
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.7.392.237
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.7.0-3.20312.3+ec4841263590f5456e32728d98097e97c1605e22
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Code alignment   14.1.107.0
Code alignment helps you present your code beautifully, enhancing clarity and readability.

CodeRush for Roslyn   20.1.4.0
DevExpress CodeRush for Roslyn package.

CodeRush for Roslyn Tool Windows   20.1.4.0
DevExpress CodeRush for Roslyn Tool Windows package.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework 6 Power Tools   0.9.2
Preview of useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a file containing a derived DbContext class, the following context menu functions are supported:
1) View Entity Data Model (Read-only) - Displays a read-only view of the Code First model in the Entity Model Designer.
2) View Entity Data Model XML - Displays the EDMX XML representing the underlying Code First model.
3) View Entity Data Model DDL SQL - Displays the DDL SQL corresponding to the SSDL in the underlying EDM Model.
4) Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

When right-clicking on an Entity Data Model (*.edmx) file, the following context menu function is supported:
Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 3.1

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

KnownMonikers Explorer   1.1.28
A tool window for Visual Studio extension authors to explore the KnownMonikers image collection

Microsoft Azure HDInsight Azure Node   2.4.6000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30415.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.04220
Microsoft SQL Server Data Tools

Swap Selection   1.2
 Using Multi-Selection to select two pieces of text and then swap them.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20610.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-3.20312.3+ec4841263590f5456e32728d98097e97c1605e22
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20304.1+7673d5e78eca5bccb77a7e4561c9d9429bdc5f35
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by SSDiver2112** [comment]
Hoped for some response this morning. This is occurring on my work and home computer. To eliminate any conflict with my working solution I started a brand new empty Solution added EF6, added new ADO.NET Entity Data Model, and same result. 
Please help as soon as possible.

**Comment by ErikEJ** [comment]
@SSDiver2112 Have you tried a non preview VS version?

**Comment by SSDiver2112** [comment]
Erik,
OK good call. I un-installed Preview and Installed Production and works fine now. Didn't want to have to rebuild my comfy IDE environment, but now it works so thank you for the suggestion. Off to the extensions and options windows...

**Comment by ErikEJ** [comment]
@lajones FYI

**Comment by lajones** [comment]
We have a developer community report on "The extender provider failed to return an extender" - see [this link](https://developercommunity.visualstudio.com/content/problem/1090865/error-while-trying-to-open-edmx-the-extender-provi.html) (for my reference this maps to internal ticket 1146365). We are trying but unfortunately we're having difficulty finding an owner for the code that throws that exception.

I've also heard that 16.7.0 Preview 3.1 is a bit flaky and they are issuing a new preview.

All of that said, I can't repro the above at the moment. @Ya-Wang can we try to narrow it down a bit? Could you try to download a simple database such as Northwind [see directions here](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/downloading-sample-databases) and see if creating an EDMX from a well-known database works. If that works then we've narrowed it down to something specific to that database.

**Comment by lajones** [comment]
Also @SSDiver2112 - can you post the contents of the .edmx file? Or at least say whether it's empty or almost empty, compared to a normal .edmx file which will have lots of XML about your entities and tables etc.

**Comment by SSDiver2112** [comment]
Doing a comparison of the .edmx files, the only difference is the DateTime types have Precision values in the correct working file
and One extra DesignerProperty present in the Good file. otherwise they are identical.

![image](https://user-images.githubusercontent.com/26187611/86291769-7f77eb80-bbbd-11ea-8633-747b6cc9eb21.png)

![image](https://user-images.githubusercontent.com/26187611/86291874-b0582080-bbbd-11ea-8b70-ec872dff7b37.png)

**Comment by lajones** [comment]
@SSDiver2112 Thanks. Could you tell me what version of EntityFramework were you using in the 2 cases?

**Comment by SSDiver2112** [comment]
both 6.4.4

**Comment by Ya-Wang** [comment]
I took  AdventureWorks2014.bak and restored it to my 12.0.6108.1 sql server. 

Created a new consoleApp project using .net framework 4.7.2 and followed the steps I initially posted and it work. 

Below is the packages in the web api project that is throwing the error. The project is currently 4.6.1 net framework. Is that not supported ? 

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="4.6.2" targetFramework="net461" />
  <package id="Autofac.Extensions.DependencyInjection" version="4.2.0" targetFramework="net461" />
  <package id="Autofac.WebApi2" version="4.1.0" targetFramework="net461" />
  <package id="EntityFramework" version="6.4.4" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights" version="2.4.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.4.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.4.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.4.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.4.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.4.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.TelemetryCorrelation" version="1.0.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Extensions.Compression.Server" version="2.0.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.HelpPage" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net461" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.7" targetFramework="net461" />
  <package id="Microsoft.DotNet.PlatformAbstractions" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyModel" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.ObjectPool" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.IO.RecyclableMemoryStream" version="1.1.0.0" targetFramework="net461" />
  <package id="Microsoft.Net.Compilers" version="2.3.2" targetFramework="net461" developmentDependency="true" />
  <package id="Microsoft.Net.Http.Headers" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net461" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net461" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net461" />
  <package id="System.Collections" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net461" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net461" />
  <package id="System.ComponentModel.Annotations" version="4.5.0" targetFramework="net461" />
  <package id="System.Console" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.5.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net461" />
  <package id="System.IO" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Memory" version="4.5.1" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net461" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net461" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.1" targetFramework="net461" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encodings.Web" version="4.5.0" targetFramework="net461" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.1" targetFramework="net461" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net461" />
</packages>`

**Comment by lajones** [comment]
@Ya-Wang If you do a _new_ web api .net 4.6.1 project and try to create an EDMX in there does that work?

**Comment by Ya-Wang** [comment]
It seems to be a project issue.

Can you point me to any debugging tips for an issue like this?

**Comment by joeruder** [comment]
This is still happening today, in both 2019 and 2022.
It happens on a 100% fresh VM created from a Azure image and a brand new project.
New database server setup, single table.

what is going on?

**Comment by heerhaan** [comment]
I encountered this exact problem, where it comes from seems pretty clear. Which is the code generator generating an incredibly outdated template which isn't supported anymore, mostly by using references to deprecated assemblies. As said by Joeruder this happens on both VS 2019 and 2022

Gods know why this happens though.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by Telavian** [comment]
To anyone still having this issue. I just tried to add an edmx file to a legacy code base and had this problem in a new project.
Using the newer style of csproj failed for me, however the older csproj style worked. I have no idea why.
