### ISSUE TITLE
Generating script with ef6 renders an sql with syntax errors due to truncating __MigrationHistory's Model field

### ISSUE THREAD

**Issue by arfmach** [dotnet/ef6#1703]
Generating database update script through `ef6.exe --script` renders an invalid SQL script.

### Steps to reproduce
1. Have a project with several migrations. The more migrations it has, the bigger will the scaffolding be
1. Export the whole migrations script using `ef6.exe database update --source Initial --script` (add any other parameters as needed)
1. Examine the generated script. Each migration finishes with an `INSERT [dbo].[__MigrationHistory]` command, and maybe the first migrations have a relatively small "Model" field value, but eventually some migration will have a Model whose hexadecimal representation has more than 4000 characters. When reaching this point, the script has a Model value truncated at 4000 characters (plus 2 from `0x` prefix) and without the remaining of the line: `, N'6.4.4')`
1. That result didn't happen with `migrate.exe` tool (EF versions prior to 6.3), nor happen using `Update-Database -Script` command in Package Manager Console.

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.3

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
