### ISSUE TITLE
Guid.CompareTo(Guid) generates an inefficient SQL on SQL Server

### ISSUE THREAD

**Issue by skurik** [dotnet/ef6#1708]
`Guid.CompareTo(Guid)` generates a suboptimal SQL. We need to compare a GUID column against a GUID variable in the query and because the `<` operator is not defined for the `Guid` .NET type, we have to use `column.CompareTo(value) == 1`.

However, the generated SQL condition is

```
(1 = 
  (CASE
     WHEN ([Extent1].[Id] = 'guid_literal') THEN 0
     WHEN ([Extent1].[Id] > 'guid_literal') THEN 1
     ELSE -1
   END)
)
```

This is unnecessarily ineffective:

```
[Extent1].[Id] > 'guid_literal'
```

works just fine and unlike the generated SQL, can utilize the index on `[Id]`.

We are migrating a table of about 500 million records and are using `[Id]` as the pointer to where the next iteration should start. Due to the `CASE` expression, the entire query gets progressively slower and slower as it has to process larger and larger portion of the table.

With simple `[Id] > 'guid_literal'`, the query is very fast.

### Further technical details
EF version: 6.4.0
Database: Azure SQL Database
Database Provider: EntityFramework.SqlServer

**Comment by skurik** [comment]
Also please note that EF Core (I tested `Microsoft.EntityFrameworkCore.SqlServer/v5.0.0-preview.7.20365.15`) generates a correct SQL using a simple comparison. Would it be possible to backport this behavior?

**Comment by skurik** [comment]
Update: `column.CompareTo(value) > 0` seems to yield the correct SQL, so that's great!

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
