### ISSUE TITLE
database first entity framework not loading a table

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1709]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1103638/database-first-entity-framework-not-loading-a-tabl.html)._

---
I recently created a table with two fields.  Both of them are foreign keys to the same field.  This table relates contact_id to alternate_contact_id.  When I created a new model in Entity Framework, it would not load this table.  No error message or any indication that there was a problem.  I eliminated one of the foreign keys and it worked.  

I don't expect Entity Framework to handle every situation, but it should return an error message, and not simply ignore a table without warning.

---
#### Feedback Bot on 7/7/2020, 00:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Lawrence Jones [MSFT] on 7/7/2020, 00:43 PM: 

<p>Hi. Could you let us have more information please?</p>
<p>When you say “created a new model in EntityFramework” were you using EFCore or EF6? What command did you use to create it - the scaffold-dbcontext command in EFCore or its matching Package Manager Console command, or maybe you meant the Add New Item wizard for EF6?</p>
<p>When you say “it would not load this table” what exactly happened? Did an EFCore command return without error but without creating anything? Did the Add New Item wizard create a file but not open it etc? As many details as you can provide please.</p>

#### Roland Wales on 7/8/2020, 03:54 AM: 

<p>I was using .net standard and EF6.  The command was Add -&gt; ADO.NET Entity Data model.  All tables were selected in the schema I wanted to create.  One of the tables was ignored because it had two foreign keys to the same field.  The key reason I am reporting this is because it did not give any warning or error message.</p>

#### Feedback Bot on 7/8/2020, 07:09 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Lawrence Jones [MSFT] on 7/8/2020, 02:50 PM: 

<p>The EF6 tools are only supported in .NET Framework projects. In a .NET Fwk 4.7.2 Console project I’m unable to repro what you see - it pulled in both FKs fine. Here is some SQL that can create the tables. Can you try this and let me know what you see?</p>
<p>CREATE TABLE [dbo].[TargetOfFKs](<br>
[Id] [int] NOT NULL,<br>
[Other] nchar NULL,<br>
CONSTRAINT [PK_TargetOfFKs] PRIMARY KEY CLUSTERED<br>
(<br>
[Id] ASC<br>
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]<br>
) ON [PRIMARY]<br>
GO</p>
<p>CREATE TABLE [dbo].[TableWith2FKs](<br>
[Id] [int] NOT NULL,<br>
[Name] nvarchar NULL,<br>
[FirstFK] [int] NOT NULL,<br>
[SecondFK] [int] NOT NULL,<br>
CONSTRAINT [PK_TableWith2FKs] PRIMARY KEY CLUSTERED<br>
(<br>
[Id] ASC<br>
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]<br>
) ON [PRIMARY]<br>
GO</p>
<p>ALTER TABLE [dbo].[TableWith2FKs]  WITH CHECK ADD  CONSTRAINT [FKFirst] FOREIGN KEY([FirstFK])<br>
REFERENCES [dbo].[TargetOfFKs] ([Id])<br>
GO</p>
<p>ALTER TABLE [dbo].[TableWith2FKs] CHECK CONSTRAINT [FKFirst]<br>
GO</p>
<p>ALTER TABLE [dbo].[TableWith2FKs]  WITH CHECK ADD  CONSTRAINT [FKSecond] FOREIGN KEY([SecondFK])<br>
REFERENCES [dbo].[TargetOfFKs] ([Id])<br>
GO</p>

#### Roland Wales on 7/13/2020, 09:39 AM: 

<p>I tried your tables, and they did work.  One difference between mine and yours is that one of my FKs is also a PK. I revised your table definitions to do this and it still worked.  So following are two tables which illustrate the problem.  (I am using EF6 and framework 4.7.2).  Eliminate FK_hemp_alternate1, and both tables will load in EF.</p><p>USE [ACF_FarmShare]
GO
/****** Object:  Table [dbo].[Alternate_Contacts]    Script Date: 7/13/2020 12:14:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alternate_Contacts](
[Contact_Id] [int] NOT NULL,
[Alternate_Contact_Id] [int] NOT NULL,
 CONSTRAINT [PK_hemp_alternateContacts] PRIMARY KEY CLUSTERED 
(
[Contact_Id] ASC,
[Alternate_Contact_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contacts]    Script Date: 7/13/2020 12:14:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
[Contact_Id] [int] IDENTITY(1,1) NOT NULL,
[Last_Name] [varchar](50) NULL,
[First_Name] [varchar](50) NULL,
[MI] [varchar](2) NULL,
[Company_Name] [varchar](50) NULL,
[Address] [varchar](50) NULL,
[Address2] [varchar](50) NULL,
[City] [varchar](50) NULL,
[State] [varchar](3) NULL,
[Zip_Code] [varchar](10) NULL,
[phone] [varchar](15) NULL,
[phone2] [varchar](15) NULL,
[email] [varchar](80) NULL,
[email2] [varchar](80) NULL,
[website] [varchar](100) NULL,
[Business_Entity_Type] [varchar](50) NULL,
[Title] [varchar](50) NULL,
 CONSTRAINT [PK_hemp_contacts] PRIMARY KEY CLUSTERED 
(
[Contact_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Alternate_Contacts]  WITH CHECK ADD  CONSTRAINT [FK_hemp_alternate1] FOREIGN KEY([Contact_Id])
REFERENCES [dbo].[Contacts] ([Contact_Id])
GO
ALTER TABLE [dbo].[Alternate_Contacts] CHECK CONSTRAINT [FK_hemp_alternate1]
GO
ALTER TABLE [dbo].[Alternate_Contacts]  WITH CHECK ADD  CONSTRAINT [FK_hemp_alternate2] FOREIGN KEY([Alternate_Contact_Id])
REFERENCES [dbo].[Contacts] ([Contact_Id])
GO
ALTER TABLE [dbo].[Alternate_Contacts] CHECK CONSTRAINT [FK_hemp_alternate2]
GO<br></p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
