### ISSUE TITLE
multiple contexts against the same db results in both trying to create __MigrationHistory

### ISSUE THREAD

**Issue by divega** [dotnet/ef6#171]
_From @MichaelMcKechnie on December 16, 2016 13:28_

I have two DbContext subclasses for the two different contexts I want to use in my solution. Each is defined in their own project, with their own configuration class and contextKey.

With a new database, the second context throws an exception ("name is already used") because it tries to create the __MigrationHistory table - which already exists because it was created by the first context.

In System.Data.Entity.Migrations.History.HistoryRepository.QueryExists I see that the code first checks for any migrations that match the context key, then it checks for the existence of the __MigrationHistory table. Unfortunately, the second check doesn't happen because it's wrapped in an if (!_contextKeyColumnExists). 

I think the  if (!_contextKeyColumnExists) should be removed - the HistoryRepository.QueryExists() method should return true for a database that has a  _MigrationHistory table but does not have any migrations in it yet.

See ~line 462 in ([https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Migrations/History/HistoryRepository.cs]...)
```C#
    foreach (var schema in _schemas.Reverse())
    {
        using (var context = CreateContext(connection, schema))
        {
            _currentSchema = schema;
            _contextKeyColumnExists = true;

            // Do the context-key specific query first, since if it succeeds we can avoid
            // doing the more general query.
            try
            {
                using (new TransactionScope(TransactionScopeOption.Suppress))
                {
                    contextKey = contextKey.RestrictTo(_contextKeyMaxLength);

                    if (context.History.Count(hr => hr.ContextKey == contextKey) > 0)
                    {
                        return true;
                    }
                }
            }
            catch (EntityException)
            {
                _contextKeyColumnExists = false;
            }

            // If the context-key specific query failed, then try the general query to see
            // if there is a history table in this schema at all
            if (!_contextKeyColumnExists)
            {
                try
                {
                    using (new TransactionScope(TransactionScopeOption.Suppress))
                    {
                        context.History.Count();
                    }
                }
                catch (EntityException)
                {
                    _currentSchema = null;
                }
            }
        }
    }
}
finally
{
    DisposeConnection(connection);
}

return !string.IsNullOrWhiteSpace(_currentSchema);
```

_Copied from original issue: aspnet/EntityFramework#7260_

**Comment by divega** [comment]
@MichaelMcKechnie would it be possible for you to provide a repro project?

**Comment by MichaelMcKechnie** [comment]
I can give it a shot, sure. Where would you lke me to post it?

fyi in my own case I ended up creating a custom HistoryContext with a custom TableName for one DbContext - so my two database schemas are managed via two different migration history tables in the same single database.

**Comment by divega** [comment]
@MichaelMcKechnie anything from attaching a zip file to point to a repository would work. If you cannot share it publically but would still want to share it with as for the purpose of debugging it you can use email. I have the same alias in my Microsoft email account.

**Comment by MichaelMcKechnie** [comment]
OK, the console app at https://github.com/MichaelMcKechnie/TwoDbContexts tries to create two DbContext subclasses in the same database, using different context keys. WHichever one goes first, succeeds. The console app is set to randomly choose one or the other to go first.

**Comment by montyclt** [comment]
Whats about using different schema in each DbContext?

**Comment by NikolaR** [comment]
It appears that this happens if schema used is not named dbo.
I have same situation using Oracle. Upon applying migrations EF checks for configured schema, but then also checks for __MigrationHistory in dbo schema, and this basically leads it to attempt to create it.

My workaround is:

1. Create dbo user (in oracle user is roughly equivalent to schema)
2. Create __MigrationHistory table in dbo user database
3. Beyond applying migrations dbo schema is not used, nor are migrations tracked in dbo.__MigrationHistory

It would be really nice to fix couple of bugs and release a SP at least. This is really preventing any large enterprise application from being developed against Oracle.

**Comment by NikolaR** [comment]
Actually, just found quite clean solution. Instead of workaround above, it's possible to set DefaultSchema for EF HistoryContext table. If set to correct schema, it will not go to _dbo_ context.

More details [I wrote here](http://nikolar.com/2019/01/23/multiple-entityframework-contexts-with-code-first-migrations/).

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
