### ISSUE TITLE
Project X targets framework '. NETStandard'. The Entity Framework Package Manager Console Tools don't support this framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1710]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1111451/project-x-targets-framework-netstandard-the-entity.html)._

---
Original post on SO: https://stackoverflow.com/questions/62702529/project-x-targets-framework-netstandard-the-entity-framework-package-manager

I'm trying to create a EF 6.4 migration in my solution which has net472 projects and netstandard projects, and I'm getting the following error:

> Project 'ESP. Console' targets framework '. NETStandard'. The Entity Framework Package Manager Console Tools don't support this framework.

However, the 'ESP. Console' app doesn't target . NETStandard, it's targetting net472:

<PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>7.3</LangVersion>
        <OutputType>Exe</OutputType>
      </PropertyGroup>

I have `ESP. Console` console app set as my startup project, and I have the `ESP. Data` project as my default project in the Package Manager console.

This is the setup for `ESP. Data.csproj`:

<PropertyGroup>
        <TargetFrameworks>netstandard2.1;net472</TargetFrameworks>
        <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
      </PropertyGroup>

I need this to target both netstandard and net472 while I am in the process of converting other applications in the solution to run on .net core.

Why am I getting this error? Is there another command like `dotnet ef` I can use that will work with my EF 6.4 project?

We've used EF migrations on this solution hundreds of times, but since the last time I needed to run a migration we've done two major changes to the solution- converted all the csproj files to use the new format (with PackageReference, etc) and converted the core projects to target either .net standard 2.0 or 2.1 where needed. So I think the issue is related to that.

Attempting to change ESP. Console application to run as `netcoreapp3.1` gave the same error.

/End of question

Workaround I was able to find:

I have found a solution to my problem, though it is a bit messy since I will need to make a temporary change to a csproj file in order to get this to run.

In my case, the ESP. Data (the project housing my DbContext) was targeting both net472 and netstandard2.1, I altered the Data project to remove the netstandard2.1 target framework. It seems there is a bug in VS that is saying that the StartupProject targets NetStandard instead of saying that the Target project does. After I create the migration, I can add the target back again.

I will be moving to .net core compilation soon, and will therefore need that netstandard 2.1 target at some point, so I'm not sure what I'll do when that comes. I may need to preserve a net472 console application to use in the future and continue targeting net472 in my data project after that migration is done in order to continue to create migrations.

/End of workaround

In my opinion this is buggy behavior by VS 2019. These are the bugs and concerns that I see with this:

a) It is reporting ESP. Console (StartupProject, not Target Project) as targeting .net standard, so the error reporting is incorrect
b) Package Manager Console should be able to handle this. There is a net472 target framework on the Data project which it should be able to find and use without issue.
c) I'm concerned that when I move to netcoreapp3.1 or .NET 5 that I will have no avenue to run migrations with EF 6 if .net standard projects are not supported. From my understanding, EF 6.3 (and 6.4) have been ported to run with .net core, but if that is true than there much be support for it to run against .net standard libraries.

Thanks, hope you're able to improve this for the future.
-Devon

---
#### Feedback Bot on 7/14/2020, 02:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by DrLeh** [comment]
Original Poster chiming in. Let me know if there's anything I can clarify.

**Comment by RudeySH** [comment]
I'm having the exact same issue. My startup project targets .NET Framework 4.8, yet the EF Tools fail on every command the error message incorrectly states that my startup project targets .NETStandard. I tried using a .NET Core 3.1 and .NET 5.0 startup project, but those also don't work.

**Comment by lehne** [comment]
I'm having this same issue. EF6 will work nicely at runtime on my net5.0 project, but I get this error at runtime. I was able to get it further along by modifying the EntityFramework6.psm1 file located in the nuget package. I change this line:
`$targetFrameworkIdentifier -eq '.NETCoreApp' `
to 
`$targetFrameworkIdentifier -eq '.NETCoreApp' -or $targetFrameworkIdentifier -eq '.NETStandard'`
and then it seems to actually run until I get the error 'System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.' with a stack trace:
 ```
  at System.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at System.Data.Entity.Infrastructure.SqlConnectionFactory.CreateConnection(String nameOrConnectionString)
   at System.Data.Entity.Infrastructure.LocalDbConnectionFactory.CreateConnection(String nameOrConnectionString)
   at System.Data.Entity.Internal.LazyInternalConnection.Initialize()
   at System.Data.Entity.Internal.LazyInternalConnection.get_Connection()
   at System.Data.Entity.Internal.LazyInternalContext.get_Connection()
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, Func`1 resolver)
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Infrastructure.Design.Executor.CreateMigrationScaffolder(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Infrastructure.Design.Executor.ScaffoldInternal(String name, DbConnectionInfo connectionInfo, String migrationsConfigurationName, Boolean ignoreChanges)
   at System.Data.Entity.Infrastructure.Design.Executor.Scaffold.<>c__DisplayClass0_0.<.ctor>b__0()
   at System.Data.Entity.Infrastructure.Design.Executor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
```
It would be nice if there was a workaround for this as all of my libraries are .NETStandard2.1 so I cannot switch them to Full Framework.

**Comment by ErikEJ** [comment]
Multi targeting?

**Comment by lehne** [comment]
Thanks @ErikEJ I was able to use multi-targeting. I had to change a lot of projects to multitarget in order to make it work. I also had to make sure that  net472 was first in the TargetFramework attribute for my migrations project or ef6.exe would use the wrong binaries.
`<TargetFrameworks>net472;netstandard2.1</TargetFrameworks>`

**Comment by lehne** [comment]
Now I am getting a new error when applying the migrations:

> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "MyAssembly.Migrations.myMigration.resources" was correctly embedded or linked into assembly "MyAssembly" at compile time, or that all the satellite assemblies required are loadable and fully signed.

What is strange is that the resource is embedded into the assembly as "MyAssembly.Migrations.**202107221410581_**myMigration.resources" and not "MyAssembly.Migrations.myMigration.resources"

**Comment by lehne** [comment]
And I got the migration to work by renaming both:
- 202107221410581_myMigration.Designer.cs
- 202107221410581_myMigration.resx
to
- myMigration.Designer.cs
- myMigration.resx

With that change it works, but very much messes up the project organization.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
