### ISSUE TITLE
Entity Framework migration commands hang the process

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1712]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1120668/entity-framework-migration-commands-hang-the-proce.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice] [regression] [worked-in:16.6.2?]
Any time I run add-migration or update-database in the package manager console the command hangs at the end and doesn't return control. It also locks the project binary files so I can no longer build. If I run it with -verbose I can at least see that it completes the requested task.

In order to clear the problem and build the system again I have to use taskkill to stop the process by PID. Restarting Visual Studio is not sufficient, the .Net task will survive the Visual Studio restart.

---
#### Feedback Bot on 7/21/2020, 11:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by stevenhiner** [comment]
This continues to happen to me consistently in Visual Studio 16.7.6 which just released.

**Comment by Skybladev2** [comment]
Same for me. VS 2019 16.8.3. Extremely annoying.
It also happens when running Entity Framework Core via NET CLI.

**Comment by DanielLauridsenSV** [comment]
Happens in current version of vs2022 as well, is there any way to get passed it?

**Comment by iamakiraa** [comment]
Happens also in version vs2019

**Comment by JadaVonRuth** [comment]
happens during adding of almost every second migration in vs2022 professional

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
