### ISSUE TITLE
Smallint in edmx file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1716]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1126005/smallint-in-edmx-file.html)._

---
Field type smallint in sql server is converted to short in edmx file. Resulting in losing the ability for negative numbers.

---
#### Feedback Bot on 7/26/2020, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
