### ISSUE TITLE
More verbose output from Add-Migration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1724]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1016886/more-verbose-output-from-add-migration.html)._

---
When trying to Add-Migration and it fails.. all it says is that it fails - there is no explanation why it fails (even with -Verbose flag). It would **so** nice with at more verbose output.

---
#### Feedback Bot on 5/6/2020, 05:04 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
