### ISSUE TITLE
How do I access the resource-file version of an EF model's MSL mapping data WHEN USING .NET 4.6.1 (NOT .NET 4.7)??

### ISSUE THREAD

**Issue by RobertAlanGustafsonII** [dotnet/ef6#1731]
**WHAT I HAVE:**
**_Visual Basic_** 2019, .NET **_4.6.1_**, Entity Framework

**MY PROBLEM:**
I've developed code that can parse the XML of an Entity Framework model's MSL metadata file in order to convert entity-and-property information of the conceptual model to table-and-column info of the store at run-time.  Its only shortcoming is that _it only works when the metadata files are copied to the "output directory"_. I need to be able to find the XML embedded in an app's resource-assemly (once again, at run-time), and it needs to work for **_pre-.NET 4.7_** platforms!

_[MetadataArtifactLoader]_(https://github.com/dotnet/ef6/blob/master/src/EntityFramework/Core/Metadata/Edm/MetadataArtifactLoader.cs) only works for **.NET 4.7+.** (Some of the namespaces don't exist in 4.6.1; other components aren't Public in that version.)  My app uses some components that don't function quite right in  .NET 4.7 (why isn't important right now), so I need a version that works with a pre-.NET 4.7 platform--even if it's less elegant or refined than the aforementioned tool.

It would also be nice if a tool could be provided in VB code, as that's the language I'm using for my app (and most other apps) and its components. (I have the _Instant VB_ converter tool, but I don't want to have to use it.) Also, there should be an explanation of how to use the tool in host code. (It's a little hard to infer from _MetadataArtifactLoader_ what method[s] a host app should invoke.)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
