### ISSUE TITLE
private static string IntArrayToStirng should read "IntArrayToString".

### ISSUE THREAD

**Issue by jasonrichardcraig** [dotnet/ef6#1732]
https://github.com/dotnet/ef6/blob/8cb6740fe3f7810dc7eb8bf715f99f49753fef78/src/EntityFramework/Hierarchy/HierarchyId.cs#L303

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
