### ISSUE TITLE
How do I, when using a pre-.NET 4.7 platform, programmatically access the MSL XML for an EF model's metadata mapping?

### ISSUE THREAD

**Issue by RobertAlanGustafsonII** [dotnet/ef6#1733]
**WHAT I HAVE:**
_Visual Basic_ 2019, .NET _4.6.1_, Entity Framework

**MY PROBLEM:**
I can parse the XML of an EF model's MSL file in order for an application to convert conceptual-model info like entity/property into store-model info like table/column at run-time. But that currently depends on the metadata files being copied to the "output directory". I need to also be able to programmatically make that conversion when the metadata XML is stored in the assembly's _resources_.

Unfortunately, _MetadataArtifactLoader_ only works with .NET 4.7+, and I need a version that can be used with an app targeted at _**pre-.NET 4.7 platform**_, as some of my program's components only work right when targeted at a lower platform. I also would like the code for the tool to be in VB.NET, as that's the language I'm using for most of my apps and components. (NOTE: I can convert from C# to VB using _InstantVB_, but I _can't_ readily retrofit MetadataArtifactLoader for .NET 4.6.1!)

Please give me an answer ASAP. Remember, pre-.NET 4.7, and--preferably--VB! Also, be sure to make it clear how to invoke the conversion code from a host app.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
