### ISSUE TITLE
Entity Framework 6 - Generate Model from Database - Disable navigation properties / associations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1147030/entity-framework-6-generate-model-from-database-di.html)._

---
If I manually delete associations/navigation properties from my model and then do an update from model, all associations/navigation properties return.  I would like to have a flat model with no relationships.

---
#### Nicholas.Leuchtenberg on 8/12/2020, 00:11 PM: 

<p>Or alternatively, it would be acceptable if I could delete all associations quickly from the Model Browser by selecting them all and deleting them, but they can only be deleted from the designer by individually selecting them.</p>

#### Feedback Bot on 8/13/2020, 00:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
