### ISSUE TITLE
Migrations for multiple contexts in same project

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/ef6#1736]
After adding 2nd context to the project and enableing migrations, I added 1st migration by specifying ConfigurationTypeName and that all worked fine. Issue is that when update-databse was called with same parameters as add-migration we get an error in package manager console

```
Exception message: More than one migrations configuration type was found in the assembly 'Project.Data'. Specify the name of the one to use.
```

Works (migration is added) : 
```
EntityFramework6\add-migration -ConnectionStringName ProjectContext -StartUpProjectName Project.Data -ProjectName Project.Data -ConfigurationTypeName Project.Data.Migrations.ProjectContext.Configuration Initial
```

Doesn't work (exception message is thrown) :
```
EntityFramework6\update-database -ConnectionStringName ProjectContext -StartUpProjectName Project.Data -ProjectName Project.Data -ConfigurationTypeName Project.Data.Migrations.ProjectContext.Configuration
```

1st contexts Configuration.cs is in migrations folder and 2nd contexts Configuration.cs is in migrations/ProjectContext folder. 

### Further technical details
EF version: 6.3.0
Database Provider:  EntityFramework.SqlServer
Operating system:  Windows 10
IDE: Visual Studio 2019 16.7.1

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
