### ISSUE TITLE
How do I get the conceptual-to-store mapping data for an EF model at run-time when  using .NET 4.6.1 (or other pre-4.7 platforms)?

### ISSUE THREAD

**Issue by RobertAlanGustafsonII** [dotnet/ef6#1739]
**WHAT I HAVE:**
_Visual Basic_ 2019, .NET _4.6.1_, Entity Framework
**MY PROBLEM:**
Sometimes it's useful to have a program that an convert conceptual-model info (like entity/property) into corresponding store-model info (like table/column) at run-time. Most versions of EF don't directly provide the mapping data, although one can parse the XML in the MSL metadata file to resolve these relationships. My own self-made tools only work when the MSL file is a separate file copied to the "output directory", and it would nice to be able to find the necessary metadata when it's stored as a resource in the program's exe _assembly_. What's more, while objects exist in .NET 4.7 to recover the XML for the appropriate metadata, these objects and methods are absent in earlier .NET versions like 4.6.1--which my program needs to be built using (for reasons that aren't important here).

I need to be able to get the resource-file info for the program's assembly (once again, at run-time), and be able to _find_ the appropriate MSL metadata--even when my platform is _pre-4.7._

Any stuff for parsing resources in a running app's assembly--as well as stuff for extracting EF metadata from the resources--would be nice. I prefer the code examples clearly show which members should be invoked (and how) to obtain the needed info, and be written in VB.NET. Whatever is given **_MUST_** be (source-code) compatible with .NET 4.6.1 (!) and possibly lower (ideally, anything between versions 4.5 and 4.6.1 inclusive).

Please give me a response ASAP. I've asked about this on several post and still haven't gotten a reply. (Once again, it has to a solution that can be invoked at trun-time in a project configured for .NET 4.6.1!)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
