### ISSUE TITLE
EF6 - Incorrect query parentheses

### ISSUE THREAD

**Issue by gianlucacarlesso** [dotnet/ef6#1748]
Hi,
I have a program that uses EF6 with Informix as database. I run the program in two different PC:
- first pc: program running correct
- second pc: an exception is raised. If I rename the folder of the program, It works.

The exception is raised because the syntax of query is wrong :
```
SELECT 
GroupBy1.A1 AS C1
FROM ( SELECT 
	COUNT(Extent1.A1) AS int) AS A1
	FROM ( SELECT 
		CAST(1 AS int) AS A1
		FROM erg.anaforn AS Extent1
	)  AS Extent1
)  AS GroupBy1
```

In another pc, the query is:
```
SELECT 
GroupBy1.A1 AS C1
FROM ( SELECT 
	Count(Extent1.A1) AS A1
	FROM ( SELECT 
		CAST(1 AS int) AS A1
		FROM erg.anaforn AS Extent1
	)  AS Extent1
)  AS GroupBy1
```
### Steps to reproduce
```vb.net
    Sub EntityInstantFeedbackSource1_GetQueryable(sender As Object, e As DevExpress.Data.Linq.GetQueryableEventArgs)
        Dim dataContext As db.ergdisEntities = New db.ergdisEntities(myApp.AppInfo.EFConnection)
        dataContext.Database.Log = Sub(s) Console.WriteLine(s) '***
        e.QueryableSource = dataContext.anaforns
        e.Tag = dataContext
    End Sub
```

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.IBM.DB2
Operating system:  Windows 10
IDE: Visual Studio 2019 

packages.config:
```
<packages>
  <package id="EntityFramework" version="6.2.0" targetFramework="net48" />
  <package id="EntityFramework.IBM.DB2" version="6.1.2" targetFramework="net48" />
  <package id="EntityFramework.it" version="6.2.0" targetFramework="net48" />
</packages>
```

**Comment by gianlucacarlesso** [comment]
Hi,
Isn't there support for this ticket?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
