### ISSUE TITLE
EF6 Package Manager Console commands use startup project, rather than "default" project

### ISSUE THREAD

**Issue by zivkan** [dotnet/ef6#1750]
@BrianBu01 created this issue, which I copied below: https://github.com/dotnet/roslyn/issues/42137

Version Used:

VS Professional 2019 v 16.4.5

Steps to Reproduce:

Select a start up project
In Package Manager Console, select a default project different from startup
Run a command that depends on building of projects or even code with in such as Scaffold-DbContext.
Expected Behavior:

The command runs in context of the default project

Actual Behavior:

The command run on the default project but in the context of the start-up project
Notes

Not really sure that this is a bug, but it is a confusing coupling between two different concepts.

**Comment by zivkan** [comment]
EF6's powershell module [explicitly gets the startup project](https://github.com/dotnet/ef6/blob/04a6ae5556f38fb3ba622dcb142a6c6b37101dd9/src/EntityFramework.NuGet/tools/EntityFramework6.psm1#L689) when no project name is given.

If NuGet's "Get-Project" command is used (with no arguments), it will get NuGet's Package Manager Console's default project, so it's possible if the implementation is going to be changed.

**Comment by BrianBu01** [comment]
Thanks @zivkan  for you diligence.
