### ISSUE TITLE
RemoveRedundantDefaultDiscriminators() adds almost 10 minutes to InitializeContext

### ISSUE THREAD

**Issue by jberent** [dotnet/ef6#1752]
*Code-first* solution takes almost 10 minutes to initialize the ObjectContext on first use, all but about 6 seconds of this time is spent in  `RemoveRedundantDefaultDiscriminators(tableMapping);`  It takes **way** too long. It finds one 'Discriminator' to remove after searching for 7-10 minutes, (The TPC table hierarchy doesn't even actually use a 'Discriminator' column).

To test, I modified `System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingService.Transform()` to skip that call (except when needed for this specific project).  Now the objectContext spins up in a few seconds...

### Steps to reproduce
The project includes around 70 simple tables, one TPC with three concrete classes, and one TPH with about 250 classes.
Simply make any query or try to Add-Migration, Update-Database (these will timeout/fail).
This has been an issue since (possibly) EF4 and the remedy has been to create metadata files like you would with EF-designer (EDMX) and not use normal code-first connection string and migrations....

This loop (called from within three nested loops within `Transform()`) seems to be the slowest part:
```c#
        private static void RemoveRedundantDefaultDiscriminators(TableMapping tableMapping)
        {
            foreach (var entitySet in tableMapping.EntityTypes.GetEntitySets())
            {
                (from cm in tableMapping.ColumnMappings
                 from pm in cm.PropertyMappings
                 where cm.PropertyMappings
                         .Where(pm1 => tableMapping.EntityTypes.GetEntityTypes(entitySet).Contains(pm1.EntityType))
                         .Count(pms => pms.IsDefaultDiscriminatorCondition) == 1

```
If I just skip the _one_ big TPH entity-type (class-hierarchy), but do all the rest, it takes mere seconds.
The classes all exist in the same domain assembly, but the DbContext and Entity-configs are together in another.

### Further technical details
EF version: 6.4.4
Database Provider: System.Data.SqlClient
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.6

**Comment by McDoit** [comment]
Has it ever been fast?
I have found that TPH reaches its limit after about 10 classes, after that the queries just becomes to bloated
Cant imagine how it must struggle with 250...

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
