### ISSUE TITLE
Migration drops second fk column index after creating composite index

### ISSUE THREAD

**Issue by xklonx** [dotnet/ef6#1755]
For example i have
```
public class DependentEntry
	{
		public int Id { get; set; }

		public int OneEntryId { get; set; }
		public virtual OneEntry OneEntry { get; set; }
		public int AnotherEntryId { get; set; }
		public virtual AnotherEntry AnotherEntry { get; set; }
	}
```
it creates indexes for OneEntryId and AnotherEntryId 
then i create modelBuilder.Entity<DependentEntry>().HasIndex(x => new {x.OneEntryId, x.AnotherEntryId});
and i get
```
DropIndex("dbo.DependentEntries", new[] { "OneEntryId" });
DropIndex("dbo.DependentEntries", new[] { "AnotherEntryId" });
```
Its ok that it drops first column index but second one must be preserved as new one index cannot replace it.
Example project
[CompositeKey.zip](https://github.com/dotnet/ef6/files/5418383/CompositeKey.zip)
### Further technical details
EF version: 6.4.4 and 6.2.0 too
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: vs 2019 16.7.2

**Comment by xklonx** [comment]
I configured AnotherEntryId index by myself and now it wont be dropped, but then i found another problem with rename index #1756

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
