### ISSUE TITLE
Migration rename index ignores previosly specified index name

### ISSUE THREAD

**Issue by xklonx** [dotnet/ef6#1756]
First, index was created with
```
.Index(t => t.AnotherEntryId, name: "idx_DependentEntries_AnotherEntryId");
```
_I think that one of the previous versions of ef always indicated the name of the index when creating the migration, because I myself did not specify these names, nevertheless they are indicated everywhere_
then i rename index
```
modelBuilder.Entity<DependentEntry>().Property(x=>x.AnotherEntryId).HasColumnAnnotation(IndexAnnotation.AnnotationName,
				new IndexAnnotation(new[] { new IndexAttribute("idx_DependentEntry_AnotherEntryId") }));
```
and I get a nonexistent index name in the rename operation
```
RenameIndex(table: "dbo.DependentEntries", name: "IX_AnotherEntryId", newName: "idx_DependentEntry_AnotherEntryId");
```
example project
[CompositeKey.zip](https://github.com/dotnet/ef6/files/5418530/CompositeKey.zip)

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: vs 2019 16.7.2

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
