### ISSUE TITLE
Using EF Core and DB Migration

### ISSUE THREAD

**Issue by rrvenki** [dotnet/ef6#1762]
In the Code first approach in EF Core and related technologies no matter how much is the innovation and ease of usefullness, the absence of UI to create and maintain the EF model is a very big minus. Almost all development members have either come from VB programming area or non Microsoft platforms.

Forcing everyone to adopt C# and do everything from prompt without UI has very high maintenance index. Due to this we've decided all future projects to abandon EF and move to regular ADO.NET. We are tiny spec in front of Microsoft but being loyal all these years we want to bring this to their notice. Thanks.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
