### ISSUE TITLE
Error: "Identifier is null or empty!"

### ISSUE THREAD

**Issue by blackboxlogic** [dotnet/ef6#1767]
I'm trying to use EntityFramework to generate an ADO.NET Entity Data Model of my stored procedures from a SqlServer DB. I get through the wizard, succeed through the progress bar saying "Retrieving stored procedure or function return type information", it starts generating files in the project. Then, it pops up a dialog which says `Identifier is null or empty!`. It then returns me to the first "Add New Item" screen as if to suggesting that I try (and fail) again. The process adds some files to my project (see image).
![image](https://user-images.githubusercontent.com/31355456/98298982-ebf86200-1f84-11eb-9ce1-1686b497ef51.png)
Looking at the files that are generated before the failure, I can tell that it gets through all of my "SQL table-valued-functions", and "SQL inline table-valued functions", but then generates nothing else.

I also tried modeling my stored procedures with EntityFramework 5.0.0 and got the same failure. I tried modeling my tables (_without_ stored procedures) and it _succeeds_. I'm sure my database has some odd stored procedures, but there is no way for me to know which one is causing a problem, or what the problem is.

**Could the error message to be improved** to indicate _which_ stored procedure(s) causes the problem, and can you give me any guidance for what might be wrong with the SP, or how to work around it. Is it possible for me to debug through the entity generation process? I looked through this repo for hints but didn't find any strings matching the error message.

I'm also seeing warning in the 'Error List' panel in VS like "The function 'functionName' has parameter 'paramterName' that has data type 'table type' which is currently not supported. The function was excluded." **Could stored procedures with "Identifier is null or empty!" errors just be excluded** in the same way?

### Steps to reproduce
I'm following directions [here](https://www.c-sharpcorner.com/blogs/implement-database-first-approach-with-entity-framework), and specifying stored procedures and functions only. I'm pointing it at my database, which has a few "odd-ball" stored procedures.

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprise 2019 (v16.7.5)

**Comment by GGLabCenter** [comment]
Hi, it seems that the error happens only when you try to create a model with stored procedures that do not return any value.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
