### ISSUE TITLE
Support Stored Procedures with User Defined Table Types

### ISSUE THREAD

**Issue by blackboxlogic** [dotnet/ef6#1771]
I'm having an issue with Store Procedures (SPs) which take User-Defined Table Types (UDTTs) as parameters. When I use the ADO.NET Entity Data Model wizard in Visual Studio 2019 to generate the .edmx file and c# classes from my database, the model that is generated isn't correct. It produced a c# function for the SP, but the generated function takes is missing the UDTT parameter.

I expect the signature of a generated function to match the signature or the SP, even when the SP takes UDTTs as a parameter.

I encountered no exceptions, error messages or warning while using the ADO.NET EDM wizard.

### Steps to reproduce

- Create a database with a User-Define Table Type `CREATE TYPE IntegerListType AS TABLE( Id int NULL )`
- Create a stored procedure which takes that as a parameter
```
CREATE PROCEDURE ProcTakesUDTT ( @UDTT IntegerListType READONLY )
AS BEGIN
	SELECT Id FROM @UDTT
END
```
- Use VS2019 ADO.NET EDM wizard, specifying stored procedures
- See the resulting generated function in `*.Context.cs` for that stored procedure takes no parameters
```
public virtual int ProcTakesUDTT ()
{
    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcTakesUDTT");
}
```
### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 v16.8.0

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
