### ISSUE TITLE
ObjectStateManager does not honor entities' GetHashCode() override.

### ISSUE THREAD

**Issue by jberent** [dotnet/ef6#1779]
Using entities with key of GUID and a `GetHashCode()` override, so Guid identifies identical objects (as it is intended to do). The ObjectStateManager _keylessEntityStore overrides this choice and treats identical (by definition) entities as multiple copies and throws errors when they occur in object graphs.

Expected: When using EF4, multiple references to the same entity would _not_ show up in the ChangeTracker.
Error: Now they do -- and cannot be processed without throwing.
Not a bug, I guess, since it was intentional, but a breaking change I cannot see how to work around.

For example:
```
Exception message:
Attaching an entity of type 'SMEPS.Domain.Aggregates.Users.User' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
Stack trace:
  at System.Data.Entity.Core.Objects.ObjectContext.AttachSingleObject(IEntityWrapper wrappedEntity, EntitySet entitySet)
```

### Steps to reproduce
Try to add disconnected entities to EF6 where (e.g., a new Document<Guid> entity has a originator User<Guid> and an editor User<Guid> where it is the same unchanged user). This document cannot be added to the ObjectContext without putting three entities in the change tracker when there should be only two.

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 / 2019

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
