### ISSUE TITLE
Issue with Entity Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1781]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Issue-with-Entity-Framework/1273810)._

---
Hi,
There is an issue in entity framework (EDM) relations. We have two tables (Orders, Users) and there are 10 relationships between the two tables where Orders table have the 10 foreign keys. So Entity Framework gave names similar to SQL realationship names:
User (Foreign Key: AddedBy)
User1 (Foreign Key: ModifiedBy)
User2 (Foreign Key: InvoicedBy)
......
User9

Lately, we had to add a new relationship between the two tables (Foreign Key: CancelledBy). It took the name User10 in SQL.

When we update the entity framework, the relations now get messed up. It assumed the User10 as the 3rd relation:
User (Foreign Key: AddedBy)
User1 (Foreign Key: ModifiedBy)
User2 (Foreign Key: CancelledBy)  --- this is where it shifted all the other relations
......
User9
User 10

So Entity Framework sorted the relations as User, User1, User10, User2 .... it assumed user10 comes before user2 relation which makes all our references to relations in our code wrong. The correct sequence should be User, User1, User2,..., User9, User10

Please have this fixed.

---
#### Feedback Bot on 12/1/2020, 06:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
