### ISSUE TITLE
Can't build ef6 project. Missing Microsoft.DotNet.Arcade.Sdk

### ISSUE THREAD

**Issue by ImGonaRot** [dotnet/ef6#1784]
I have the latest version of .NET sdk 5.0.101 installed but inside the folder "C:\Program Files\dotnet\skd\5.0.101\Sdks\" there is no folder called "Microsoft.DotNet.Arcade.Sdk".
The ef6 project will not build because it can't find that folder.

> C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.

I went to https://github.com/dotnet/arcade but they don't have an installer for the SDK/
I also downloaded the entire arcade solution and ran the build.cmd without any errors but still ef6 will not build.

What am I missing? How do I install "arcade"?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
