### ISSUE TITLE
EF Core Add UseScopeIdentity property to change scope_identity() to MERGE for SEQUENCE PK

### ISSUE THREAD

**Issue by UltimateVenom** [dotnet/ef6#1787]
Hi.

When I use EF 4.6 and above I have the option to use the _SqlProviderServices.UseScopeIdentity_ property to **false** when inserting a row in a table where PK is a SEQUENCE. Using NET CORE 3.1 I don't have any issues because the created script uses MERGE over SCOPE_IDENTITY method.

Using NET CORE 5 and EF 5.0 I can't get this working because the generated script uses SCOPE_IDENTITY. Searching over and over the internet and docs I can't find an _UseScopeIdentity_ property to set generated script to MERGE.

### Generated EF SQL code using EF 4.6 and above using **_SqlProviderServices.UseScopeIdentity = false_** and NET CORE 3.1
```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [dbo].[Usuario] ([Active], [UserCode], [CreatedUser], [FullName])
VALUES (@p0, @p1, @p2, @p3);
SELECT [UserId], [CreatedDate], [GuidId]
FROM [dbo].[Usuario]
WHERE @@ROWCOUNT = 1 AND [UserId] = scope_identity();
',N'@p0 bit,@p1 varchar(50),@p2 varchar(100),@p3 varchar(100)',@p0=1,@p1='user1',@p2='admin',@p3=NULL
```

### Generated EF SQL code using NET CORE 5.0

```
exec sp_executesql N'SET NOCOUNT ON;
DECLARE @inserted0 TABLE ([UserId] smallint, [_Position] [int]);
**MERGE** [dbo].[Usuario] USING (
VALUES (@p0, @p1, @p2, @p3, 0)) AS i ([Active], [UserCod], [CreatedUser], [FullName], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([Active], [UserCod], [CreatedUser], [FullName])
VALUES (i.[Active], i.[UserCod], i.[CreatedUser], i.[FullName])
OUTPUT INSERTED.[UserId], i._Position
INTO @inserted0;

SELECT [t].[UserId], [t].[CreatedDate], [t].[GuidId] FROM [dbo].[Usuario] t
INNER JOIN @inserted0 i ON ([t].[UserId] = [i].[UserId])
ORDER BY [i].[_Position];
',N'@p0 bit,@p1 varchar(50),@p2 varchar(100),@p3 varchar(100)',@p0=1,@p1='user1',@p2='admin',@p3=NULL
```

### Further technical details
EF version: NET CORE 5.0
Database Provider: EntityFramework.SqlServer
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
