### ISSUE TITLE
entity framework 6.4.4 no connection

### ISSUE THREAD

**Issue by luismk** [dotnet/ef6#1791]
I'm not able to connect to the sql server database

the App.config settings is correct

**Comment by magork** [comment]
I have almost the same issue. I can't run the command of update database and add migration.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
