### ISSUE TITLE
GUIDs and Endians

### ISSUE THREAD

**Issue by martinRocks** [dotnet/ef6#1792]
Hello all,
I have a very interesting problem.  I have been tasked with updating an old application that has a ton of oracle stored procedures to get data.  One of the things that I'm doing is adding entity framework 6.4.4 to the app to get data instead of calling the stored procedures.  My problem is that when the oracle stored procedure returns a GUID stored in a RAW(16) field, it isn't the same as when entity framework returns the same GUID.  From my understanding, the difference is entity frameworks converts the byte array of the GUID into a mixed endian GUID.

I have found code that converts the GUIDs back and forth so one call can get data from a stored procedure and pass that data to entity framework to do another call.  I'm just worried that it is going to get crazy flipping the endians all over the place.

Is there a way to tell entity framework to not re-order the bytes?

The application server is Windows 2012r2
The database server is Windows 2012r2 running Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production Version 18.12.0.0.0

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
