### ISSUE TITLE
Why does code first with existing database put usings within the class?

### ISSUE THREAD

**Issue by rfalanga** [dotnet/ef6#1799]
When I use Entity Framework's 6 Code First with Existing Database, all the model classes it creates puts the `using` statements inside of the class, before any properties. Why EF put the usings before the class declaration?

### Steps to reproduce
I get into Visual Studio, right click on a project, select Add, then New Item, then Data, then "ADO.NET Entity Data Model". I named it and then select "Code First from database". I name the model and save it. All the class files that are created puts the `using` in the class declaration, rather than above the class declaration.

### Further technical details
EF version: 6
Database Provider: System.Data.SqlClient
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
