### ISSUE TITLE
Lazy loaded entites with DateTime values can return different results compared to eager loaded entites when query is complex enough

### ISSUE THREAD

**Issue by gregleon** [dotnet/ef6#1806]
### Steps to reproduce

I've created an example console program that allows for the bug reproduction [here](https://github.com/gregleon/EntityFrameworkTest/blob/master/EntityFrameworkTest.Console/Program.cs).

Program summary:

## The bug reproduction requires lazy loading which means DbContext has to have it enabled
```
Configuration.ProxyCreationEnabled = true;
Configuration.LazyLoadingEnabled = true;
```

## Create root entity with date that is prone to cause the bug and save it to database. Save only happens once then bug can reproduced as many times needed. 

```
var root = new Root()
{
    DateChildren = new List<DateChild>()
    {
        new DateChild()
        {
            // This doesn't have to be this exact date, it's just the one that allows bug reproduction
            CreateDate = new DateTime(637480200495470000)
        }
    },
    AnyEntity = new AnyEntity()
    {
        AnyEntityParent = new AnyEntityParent()
        {
        }
    }
};
```
## Define logic where entities are sometimes lazy loaded and sometimes eager loaded to allow compassion
```
var queryRoots = context.Roots.AsQueryable();

if (includeNonDateEntities)
{
    queryRoots = queryRoots
        .Include(o => o.AnyEntity.AnyEntityParent)
        .Include(o => o.ParentRoot)
        .Include(o => o.ParentRoot.AnyChildren)
        .Include(o => o.AnyChildren);
}

// if the values are not included they will be lazy loaded
if (includeDateEntities)
{
    queryRoots = queryRoots.Include(o => o.DateChildren);
}

return queryRoots.First();
```
## Compare values
```
var rootWithEagerLoadedDateEntities = GetRoot(includeNonDateEntities: includeUnrelatedEntities, includeDateEntities: true);
var eagerLoadedTicks = GetDateChildrenDateTicks(rootWithEagerLoadedDateEntities);

var rootWithLazyLoadedDateEntities = GetRoot(includeNonDateEntities: includeUnrelatedEntities, includeDateEntities: false);
var lazyLoadedTicks = GetDateChildrenDateTicks(rootWithLazyLoadedDateEntities);

if (!lazyLoadedTicks.SequenceEqual(eagerLoadedTicks))
{
    var tickValues = lazyLoadedTicks.Concat(eagerLoadedTicks).Distinct();
    System.Console.WriteLine($@"Dates had different values and they were: {string.Join(", ", tickValues)}");
}
else
{
    var tickValue = lazyLoadedTicks.Concat(eagerLoadedTicks).Distinct().Single();
    System.Console.WriteLine($@"Dates had a single value and it was: {tickValue}");
}
```
## Run test:

If the query is simple (does not contains unrelated includes) then everything works fine:
```
// Test console output: Dates had a single value and it was: 637480200495470000
TestLazyLoading(includeUnrelatedEntities: false);
```

but if we include unrelated entities then eager loading and lazy loading start to return different values:
```
// Test console output: Dates had different values and they were: 637480200495470000, 637480200495466667
TestLazyLoading(includeUnrelatedEntities: true);
```

### Further technical details
EF version: tested on 6.2.0 and 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual studio 2019

**Comment by gregleon** [comment]
Bump. Is anyone looking at these?

**Comment by gregleon** [comment]
Still nothing?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
