### ISSUE TITLE
When using Records with EF6 & lazy loading, 'with' does not load references

### ISSUE THREAD

**Issue by richardpawson** [dotnet/ef6#1811]
We are using EF6 with Record types, trying to follow pure functional programming patterns as much as possible.

When updating a record we are following the standard pattern of using `with ` to clone a record ( `with `will be applicable to classes from C#10) , with just the specified differences. 

For good reasons (nothing to do with this issue) we do not explicitly eagerly load references, relying on the the lazy loading pattern  (where entities are proxied by EF), which has served us well for years.

It seems these two patterns - records and lazy loading - do not play well together in the context of EF6 (and, I am guessing, EF Core too).  When the object is being cloned (under the covers by the `with `statement) it, presumably, does not go through the property getter and so is not causing any lazily-loaded references to be resolved - resulting in them being null in the  clone.

While I am aware than many people favour explicit eager loading in queries, this is not an answer for us. At the moment we are having to write our own 'Resolve' method that loops over all reference properties, reflectively, and access them to ensure loading.  This duplicates work that it normally done by EF and also duplicates much of the work of `with`.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
