### ISSUE TITLE
Migration scripts with multiple contexts fail to create a database

### ISSUE THREAD

**Issue by PilotBob** [dotnet/ef6#1815]
###Describe what is not working as expected.
If I have more than one context in a database, and I generate an idempotnent migration scripts, the second script to run on a new database fails.

###If you are seeing an exception, include the full exceptions details (message and stack trace).
SQL Server Table Exists Error occurs on attempt to create __MigrationHistory table by the second context's script.

### Steps to reproduce
Create a db context with a test table - enable migrations, create a migration.
Script an idempotnent migration with update-database or ef6.exe
Create a 2nd db context with a test table - enable migrations, create a migration.
Script an idempotent migration with update-database or ef6.exe

Create an empty database.
Run the first migration script into the database.
Run the second migration script into the database. Error occurs.

You can observe that the generated script assumes that since there is no migration for the context in question that there is also no migration table. The create table should be wrapped with an IF NOT EXISTS check. 

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
