### ISSUE TITLE
EF will load varying DateTime values

### ISSUE THREAD

**Issue by stigc** [dotnet/ef6#1822]
My domain model DateTime properties will not hold the same value, when loaded direct vs an aggregated root. I am using SQL Server with data type datetime (not datetime2)

Direct load

```
_dbcontext.Set<OrderLine>()
  .ToList()
```

Load via aggregate root in a 1:m collection

```
_dbcontext.Set<Order>()
  .Include(x => x.OrderLine)
  .ToList()
```

The problem is, when EF is loading a graph, it will join different entities together in a single SQL. The OrderLine datetime columns will be defined as NULL datetime2

`CAST(NULL AS datetime2)`

These casts are not happening when loading the OrderLines alone (and they shouldn't)

Since the datetime is casted to datetime2 in the database, the EF framework will convert it to a DateTime with higher precession. Here is a screenshot of OrderLine.OrderDate when loaded with the two different approaches.

![image](https://user-images.githubusercontent.com/10206897/109425821-97249f80-79ea-11eb-8b62-ec3f95e803c2.png)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
