### ISSUE TITLE
Extend with new mapping logic

### ISSUE THREAD

**Issue by stigc** [dotnet/ef6#1825]
NHibernate can be extended with new implementations of IUserType, so I can customize how a mapped property is read and stored to/from the database.

An example. If I want DB null varchar to load as "n/a" string, and "n/a" string to be stored as null.

How is this possible with EF 6.2?

I am looking for a solution that doesn't break the change-tracker.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
