### ISSUE TITLE
FK with Different DataType than PK Ask Question

### ISSUE THREAD

**Issue by walter-silveira** [dotnet/ef6#1828]
I'm working with an old database and on table 1 the PK is int and the table 2 the equivalent field as FK (it actually isn't fk) is bigint. I need to link them so i map my classes like bellow.

```
[Table("PR_BLOG")]
public class Blog
{
    [Key]
    public int Id { get; set; } //in data base this column is int
    public string Name { get; set; }
    
    public ICollection<Post> Posts { get; set; }
}

[Table("PR_POST")]
public class Post
{
    [Key]
    public int Id { get; set; }
    public string Content { get; set; }

    public long BlogId1 { get; set; } //In data base this column is long
    [ForeignKey("BlogId1")]
    public Blog Blog { get; set; }

    public long BlogId2 { get; set; }
}
```

If i change the data type of Id on Blog class to long and map it with `modelBuilder.Entity<Blog>().Property(x => x.Id).HasColumnType("int")` i have these exceptions when i call `_context.Post.Include(p => p.Blog)`:

InnerException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
Message: An exception occurred while reading a database value for property 'Post.BlogId1'. The expected type was 'System.Int64' but the actual value was of type 'System.Int64'.

Change the type of column it's not an option for now, my question is, how can i map this case?

**Comment by ajcvickers** [comment]
@walter-silveira This is not supported by EF6.

**Comment by walter-silveira** [comment]
@ajcvickers thanks for answer, what is not supported by EF6? The fix i suggest or the way i'm doing?

**Comment by walter-silveira** [comment]
@ajcvickers thanks for answer.
