### ISSUE TITLE
Code First Many to Many relationship creates a duplicate joining table?

### ISSUE THREAD

**Issue by Josrph** [dotnet/ef6#1833]
I'm trying to create a many to many relationship between **Product** and **Category** with a joining table using EF 6.4.4 and MySQL 8, but EF keeps creating a duplicate joining table no matter what I do???
```

public class AppDbContext : DbContext
{
    //Schema Tables
    public DbSet<Product> Products { get; set; }
    public DbSet<Category> Categories { get; set; }
    public DbSet<ProductCategory> ProductCategories { get; set; }
}

public abstract class BaseEntity
{
    [Key]
    public int ID { get; set; }
    public string Name { get; set; }
}
public class Product : BaseEntity
{
    public virtual IList<Category> Categories { get; set; }
}
public class Category : BaseEntity
{
    public virtual IList<Product> Products { get; set; }
}

```
I tried creating the joining table like this: 
```
public class ProductCategory
{
    [Key, Column(Order = 1)]
    public int ProductID { get; set; }
    [Key, Column(Order = 2)]
    public int CategoryID { get; set; }
    
    public Product Product { get; set; }
    public Category Category { get; set; }
}
```
and this:
```
public class ProductCategory : BaseEntity
{
    public int ID { get; set; }

    [ForeignKey(nameof(Product)), Column(Order = 1)]
    public int ProductID { get; set; }
    [ForeignKey(nameof(Category)), Column(Order = 2)]
    public int CategoryID { get; set; }

    public Product Product { get; set; }
    public Category Category { get; set; }
}
```
or this:
```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);
    
    modelBuilder.Entity<ProductCategory>().HasKey(x => new { x.ProductID, x.CategoryID });
}
```

but nothing seems to work ...it always keeps creating a duplicate joining table? 

What am I doing wrong? Is this even possible?

```
products
categories
productcategories
productcategory1 (duplicate)
```

**Comment by ajcvickers** [comment]
@Josrph EF6 supports only many-to-many relationships without any reference to the join table, so what you are trying to do is not supported by EF6. Many-to-many support in EF Core does allow this.

**Comment by Josrph** [comment]
> @Josrph EF6 supports only many-to-many relationships without any reference to the join table, so what you are trying to do is not supported by EF6. Many-to-many support in EF Core does allow this.

but I got the same result even when I tried with EF Core 5.0? a duplicate table was created the same as EF 6?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
