### ISSUE TITLE
Converting to Web Application Project, Entity Framework object Code-first from database compile errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1837]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Converting-to-Web-Application-Project-E/1367365)._

---
[severity:I'm unable to use this version]
I'm working on converting an old Website Project to a Web Application Project and have run into an issue with files generated by Visual Studio 2019 V16.9.1 (and previous versions) for EntityFramework data models Code First from Existing Database.

The error is this: 
error CS0433: The type 'ColumnAttribute' exists in both 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

The generated code snippet where the error is reported looks like this:

```
    [Column(TypeName = "ntext")]
        [Required]
        public string r_roleDescription { get; set; }
```

I am stopped in the conversion process until this can be fixed.
Thanks,
Owen

---
#### Feedback Bot on 3/11/2021, 07:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
