### ISSUE TITLE
auto migration for sqlite.codefirst

### ISSUE THREAD

**Issue by usapop** [dotnet/ef6#1841]
I want to create auto migration for my project with sqlite.codefirst
sqlite does not support alter table command, so I create my custom migrationSqlGenerator but for addColumn or DropColumn operation, I need to rename old table, create new and copy old data to new table and then drop old table.
Can anyone help me, how can I change my migrationGenerator class for this scenario?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
