### ISSUE TITLE
HierachyId's Root GetDescendant throws an exception.

### ISSUE THREAD

**Issue by AaronRPrince** [dotnet/ef6#1847]
In HierarchyId, when using GetDescendant from the root node and supplying both children, an exception is thrown. The exception is only thrown when both children are not null. The other permutations return as expected.

### Steps to reproduce
```c#
var newChild = HierarchyId.GetRoot().GetDescendant(HierarchyId.Parse("/1/"), HierarchyId.Parse("/2/"));
```

### Exception
System.ArgumentException : The input string '//1.1/' is not a valid string representation of a HierarchyId node.

### Source
In the root node, _nodes is an empty array. The string join on Line 201 will always return an empty string.

```c#
hierarchyStr = PathSeparator +
    string.Join(PathSeparator, _nodes.Select(IntArrayToStirng))
    + PathSeparator
    + IntArrayToStirng(child1LastNode)
    + PathSeparator;
return new HierarchyId(hierarchyStr);
```
[HierarchyId.cs line 201](https://github.com/dotnet/ef6/blob/main/src/EntityFramework/Hierarchy/HierarchyId.cs#L201)

### Further technical details
EF version: 6.4.0 and 6.4.4
Database Provider: EntityFramework.SqlServer

**Comment by Poltuu** [comment]
EF Core has been fixed 
https://github.com/dotMorten/Microsoft.SqlServer.Types/commit/e5625eabcaa46cc6839f4a333ad3fc53ee9a810e
Could we hope for a EF 6.4 release with the fix ? 🙏

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
