### ISSUE TITLE
Wiki: Building the Runtime is outdated

### ISSUE THREAD

**Issue by zbrkic** [dotnet/ef6#1854]
Please update wiki page Building the Runtime.
Instructions are wrong, I cannot make tests run locally.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
