### ISSUE TITLE
cannot be loaded because its operation is blocked by software policie

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1856]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/cannot-be-loaded-because-its-operation-i/1412736)._

---
Today i just start getting this error on entity framework
microsoft.entityframeworkcore.tools\2.2.3\tools\init.ps1 cannot be loaded because its operation is blocked by softwate policies

---
#### Feedback Bot on 5/5/2021, 07:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
