### ISSUE TITLE
System.Data.Entity.Core.EntityCommandExecutionException: 'An error occurred while executing the command definition. See the inner exception for detail

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1859]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemDataEntityCoreEntityCommandExe/1407036)._

---

```C#
 public List<ComAfterconnect> GetByComAfter(string key)
        {
            using (SomaContext context = new SomaContext())
            {
                return context.**ComAfterconnect**. Where(p => p.Command.StartsWith(key)). ToList();
            }
        }
```

```
SqlException: Invalid object name 'dbo.ComAfterconnect**s**'.
```

```sql
SELECT 
    [Extent1]. [Id] AS [Id], 
    [Extent1]. [VendorId] AS [VendorId], 
    [Extent1]. [TypeId] AS [TypeId], 
    [Extent1]. [Command] AS [Command]
    FROM [dbo]. [ComAfterconnect**s**] AS [Extent1]
```

Why adds the letter "s" at the end of the table name?

---
#### Feedback Bot on 4/24/2021, 07:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
