### ISSUE TITLE
Package manager console not exiting after running a command

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1862]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Package-manager-console-not-exiting-afte/1423992)._

---
[severity:It's more difficult to complete my work]
I have encountered the same issue as already reported [one](https://developercommunity2.visualstudio.com/t/Package-manager-console-not-exiting-afte/668241?entry=problem&ref=native&refTime=1620989229857&refUserId=06e7ff62-b528-6e60-9936-18461fd6ce1a). It happens for me every time when I use some command for EF. And worst of all, after those command I should build project, then look at output to find out what process block .dll files, and then manually kill it. Restart VS does not help.

---
#### Feedback Bot on 5/16/2021, 10:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
