### ISSUE TITLE
EF Code First Migrations failure in VS 2022 v17.0.0 P1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1870]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF-Code-First-Migrations-failure/1461046)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.10.2]
I'm unable to enable-migrations, add-migration, update-database in vs 2022 v17.0.0 P1. 
My project is asp.net based, running entity framework, code first migration.

All three of these commands return the following error...

```
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2. <.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Value cannot be null.
Parameter name: type``
```

---
#### Feedback Bot on 6/27/2021, 06:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AndriySvyryd** [comment]
As a workaround use ef6.exe on compiled assemblies.
See https://github.com/dotnet/EntityFramework.Docs/issues/1740#issuecomment-557204757 and https://github.com/dotnet/ef6/issues/1053#issuecomment-522054334 for more information

**Comment by bronthulke** [comment]
I am having this same issue now, just upgraded to VS2022 and can't run an `add-migration` command for an EF6 project.  I have reviewed the comment/issue that @AndriySvyryd linked but can't see a clear solution in there.

Can you please provide a bit more clarity around how we can continue to use EF6 Code First Migrations in VS2022?

**Comment by AKruimink** [comment]
Upgrading to 6.4.4 from 6.2.0 solved the issue for me

**Comment by ABDULLAH9090** [comment]
I am having this same issue now
Has it been resolved?
Please help me

**Comment by will-russell** [comment]
Using EF 6.4.4 (NuGet package) in VS 2022 17.0.2 (C#, ASP.NET app) has this issue when attempting to use "add-migration" or "update-database" from Package Manager Console. 
Get exact error as OP, so this is still happening on absolute latest available builds.

Only "workaround" that works for me is to use VS2019 at this time.
Full disclosure: this website was originally created in VS 2017 and EF 6.0.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by alexmaie** [comment]
Hi,

What workaround would you suggest for the future? Right now you are saying that we should have both VS2022 and Vs2019 installed.

Thanks
