### ISSUE TITLE
Is it safe to run the migration concurrently? If not, how to perform "locking"?

### ISSUE THREAD

**Issue by drauch** [dotnet/ef6#1873]
Our applicaiton runs in k8s, and the database migration is running as part of init containers. This means, that each node will try to run the migration when it comes up -> as we have multiple nodes, that may happen concurrently.

Are EF6 migrations safe to perform concurrently? 

If not, how to properly lock the database before running the migration?

Best regards,
D.R.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by drauch** [comment]
This has been a question and not a request for a change. Are you sure you wanted to close this?

**Comment by ajcvickers** [comment]
@drauch Yes; please see the readme.
