### ISSUE TITLE
Entity Framework 6 management with Package Manager Console locks the UI (freezes)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1878]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entity-Framework-6-management-with-Packa/1467995)._

---
[severity:I'm unable to use this version]
Open Package Management Console
Switch to the EF6 project in the Default Project dropdown
Run the command: `Get-Migrations`

Result:
The UI Freezes (hangs)

I tried recording the actions but when the VS 2022 instance hangs the recorder hangs as well.

---
#### Feedback Bot on 7/6/2021, 07:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
