### ISSUE TITLE
Entity Framework 6 migrations are not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1879]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entity-Framework-6-migrations-are-not-wo/1471932)._

---
[severity:It's more difficult to complete my work]
Entity Framework Code First migrations are not working in preview 1.  It error while generating the migration. I have created the migration on Visual Studio 2019 and every command works find regarding the EF 6 migration

To replicate this, Just create an ASP.NET Full framework application with Identity authentication. Just add an extra property to the Application user model and then try to go Add-Migration.

It will show error and unable to create the migration

---
#### Feedback Bot on 7/12/2021, 01:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
