### ISSUE TITLE
EF6 migration history table has changed to _EFMigrationsHistory from _MigrationHistory

### ISSUE THREAD

**Issue by keerthimaryala18** [dotnet/ef6#1885]
We have two services using different db contexts pointing to the same MySQL DB. One service uses EF6 and the other uses EF Core. Up Until now, we ran migrations only from the EF6 service and the history was maintained in _MigrationHistory. After running migrations in the EF Core service, I tried to run Migrations in the EF6 service and it seems to have lost context of the _MigrationHistory table and point to the _EFMigrationHistory table. 

The _MigrationHistory table has a lot of history and I don't want to reset the migrations in that service. Is there a way to point the EF6 service back to _MigrationHistory table?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
