### ISSUE TITLE
System namespace is sometimes unneccesary in migration class

### ISSUE THREAD

**Issue by 1Jesper1** [dotnet/ef6#1890]
` using System;
`

 is **sometimes** unneccesary in migration class when created with `Add-Migration`

### Further technical details
EF version: 6.4.4
Database Provider: MSSQL
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
