### ISSUE TITLE
All nullable reference type annotations to QueryableExtensions.cs

### ISSUE THREAD

**Issue by madelson** [dotnet/ef6#1893]
When using EF6 in a solution with nullable reference types, if I call `FirstOrDefaultAsync()` it doesn't know that it returns Task<T?> instead of Task<T> (unlike `Queryable.FirstOrDefault()`). Seems like it would be low-investment to enable annotations in this file and add annotations to match the synchronous queryable methods.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
