### ISSUE TITLE
Scaffold-DbContext throws could not load assembly error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1917]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Scaffold-DbContext-throws-could-not-load/1580647)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.0.0 Preview 7]
This is the command I've been using for quite some time run from PM console:

Scaffold-DbContext "Data Source=xxx.database.windows.net;Initial Catalog=xxx;User ID=xxx;Password=xxx" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Tables "PlutoExchFinalFunctionalTest", "SWD_0013", "SWD_0025" -Force -UseDatabaseNames -Context "EFContext"

Started throwing the error after upgrading to latest preview version.

Could not load assembly 'FinalFunctionalTest'. Ensure it is referenced by the startup project 'FinalFunctionalTest'.

---
#### giorgi kikalishvili on 11/11/2021, 05:40 PM: 

<p>Scaffold-DbContext “Server=(local);Database=LMSNewProject;Trusted_Connection=True;” Microsoft.EntityFrameworkCore.SqlServer -OutputDir Databases -force<br>
returns error:<br>
Could not load assembly ‘LmsDataLibrary’. Ensure it is referenced by the startup project ‘LMSNewProject’.</p>

#### Feedback Bot on 11/12/2021, 05:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
