### ISSUE TITLE
Please provide EF6.1 to generate a parametric method in the SQL statement to replace

### ISSUE THREAD

**Issue by gallop1** [dotnet/ef6#1925]
Please provide EF6.1 to generate a parametric method in the SQL statement to replace, directly to the SQL statement assignment query, rather than generating a parametric SQL statement query. Similar to: select from A where A.Id=@id, you can get the real statement directly: select s from A where A.Id=2, assigned statement.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
