### ISSUE TITLE
Explicit value must be specified for identity column in table '<TableName>' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity column.

### ISSUE THREAD

**Issue by Sreejithga** [dotnet/ef6#1926]
**Problem :** Insertion of explicit value into an IDENTITY column in SQL is not working from C#.Net with Entity Framework 6.2.0, below error is being thrown always. 
"Explicit value must be specified for identity column in table '<TableName>' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity column."

I have taken the code from below page
https://entityframework.net/identity-insert
but its not working in my IDE when tested but giving the error as mentioned above.

**Code Start**
```
        private void button1_Click(object sender, EventArgs e)
        {
            using (var context = new DataContextIdentity())
            {
                using (var transaction = context.Database.BeginTransaction())
                {
                    AUTHOR author = new AUTHOR()
                    {
                        ID = 1001,
                        Name = "Johny",
                    };
                    context.AUTHORs.Add(author);

                    context.Database.ExecuteSqlCommand(@"SET IDENTITY_INSERT [dbo].[AUTHORs] ON");
                    context.SaveChanges();
                    context.Database.ExecuteSqlCommand(@"SET IDENTITY_INSERT [dbo].[AUTHORs] OFF");

                    transaction.Commit();
                }
            }
        }

```

SaveChanges throws this error. If I remove SET IDENTITY_INSERT lines, it works as usual inserting a new record into SQL Table  with autogenerated value into ID column. But my requirement is to set an explicit value '1001' as I'm trying to insert from the above code which is not working. Kindly help to resolve this issue, what am I missing here. All the steps mentioned in this link (https://entityframework.net/identity-insert) was done, but did not work
**Code End**

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10)
IDE: Visual Studio 2017
<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>

**Comment by Sreejithga** [comment]
App.Config as below

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <connectionStrings>

  </connectionStrings>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
</configuration>

**Comment by CZEMacLeod** [comment]
@Sreejithga It looks like EF is assuming the database will supply the identity (and EF will generate an insert statement without an identity value and read it back). Perhaps your `DataContextIdentity` class does not include the correct `OnModelCreating` or something else is wrong.
In the example, it calls `base.OnModelCreating(modelBuilder);` after setting the property, although I think it should be before, so that the `HasDatabaseGeneratedOption` can be overwritten. The example code also seems to be missing where it declares the model that states that AuthorID is DatabaseGenerated in the first place.
I think you need to post your `DataContextIdentity` and `AUTHOR` classes as well as the base class for `DataContextIdentity` (`DataContext`?) to be sure.

**Comment by Sreejithga** [comment]
@CZEMacLeod  Thanks for your response, Below is the code from DataContextIdentity class

![image](https://user-images.githubusercontent.com/53110553/145723239-7a9e894b-d7a4-4bce-adf7-6e6ebe5962d7.png)

As you've mentioned I tried putting the highlighted line of code as the first line and then as the second line inside  OnModelCreating function, still the result is the same in both the cases.

Base class is as below
![image](https://user-images.githubusercontent.com/53110553/145723414-ae1f070c-0cf6-4601-95a6-0a10a10e09cc.png)

Author Class
![image](https://user-images.githubusercontent.com/53110553/145723466-73bd8a27-e82d-41f2-ae01-31aa1526e4d8.png)

This helps ? If any further information required, please let me know, thanks..

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
