### ISSUE TITLE
Alternate key I'm not expecting is generated since net6 upgrade

### ISSUE THREAD

**Issue by TehWardy** [dotnet/ef6#1939]
We have recently updated to the latest of everything (net6, ef6 all latest non preview versions) and I've now got a new problem I have not seen before. We have started experiencing an issue on one of our endpoints due to the db model no longer being in sync with the coded class for some reason. The model and the class have not changed.

When I add a new test migration I get this ...

```cs
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AddColumn<int>(
        name: "TempId1",
        schema: "Payments",
        table: "RemittanceAdvices",
        type: "int",
        nullable: false,
        defaultValue: 0);

    migrationBuilder.AddUniqueConstraint(
        name: "AK_RemittanceAdvices_TempId1",
        schema: "Payments",
        table: "RemittanceAdvices",
        column: "TempId1");
}
```
This is an existing table, but there's no "TempId1" property on it, and the only thing I can deduce from the documentation is that EF thinks that an "alternative key" is needed due to some relationship somewhere so ...
   How do I track down where this is coming from?

**Comment by ErikEJ** [comment]
This is the EF6 repo, not EF Core 6.

**Comment by TehWardy** [comment]
Never mind ... we found it anyway.
Figured this would be good to know though rather than randomly clicking though the entire object model.
