### ISSUE TITLE
What is the unit of time???

### ISSUE THREAD

**Issue by Lucas-Ferguson** [dotnet/ef6#1942]
The page does not specify whether the timeout value is milliseconds, seconds, nanoseconds....it just says "Timeout Value".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aeb3b9b-c4e7-c548-e1eb-01ca6f9e6178
* Version Independent ID: 9c583239-f9a4-de68-962d-51aa0b7f4ef3
* Content: [DbMigrationsConfiguration.CommandTimeout Property (System.Data.Entity.Migrations)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.dbmigrationsconfiguration.commandtimeout?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.Migrations/DbMigrationsConfiguration.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Migrations/DbMigrationsConfiguration.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
