### ISSUE TITLE
Unable to connect to SQLite database on Visual Studio 2022 .Net Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1943]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-connect-to-SQLite-database-on-/1638075)._

---
[severity:I'm unable to use this version]
I have Installed these packages with Nuget :
- EntityFramework
- SQLite
- System.Data.Sqlite
- System.Data.Sqlite.Core
- System.Data.Sqlite.EF6
- System.Data.Sqlite.Linq
- Sub.System.Data.Sqlite.Core.NetFramework
When I try to connect a DataGridView to a Dataset, using **SQLite Provider (Simple EF6 by EricEJ)**, I get the message:
_Could not find the data provider. NET Framework requested_
I couldn't connect to SQLite database with these packages in Visual Studio 2019, but I used **DotConnect** from Devart. But DotConnect doesn't run in Visual Studio 2022. 
Thanks for a fix.
Windows 11 Professionnel 21H2 Build 22000.434

---
#### Feedback Bot on 1/17/2022, 07:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
@ErikEJ Any ideas?

**Comment by ErikEJ** [comment]
I did some research and I think the issue is that there is no Sqlite 64 bit DbProvider (and there never will be one until @bricelam or someone else releases a Sqlite  DDEX provider) 😉  https://github.com/ErikEJ/SqlCeToolbox/issues/924#issuecomment-1006812169

**Comment by bricelam** [comment]
I updated my [VS.Data.Sqlite](https://github.com/bricelam/VS.Data.Sqlite) project to work on VS 2022 back in November, but I'm not sure how close it is to enabling the DataGridView stuff. And there's still [a lot I want to do](https://github.com/bricelam/VS.Data.Sqlite/projects/1) before making an official release of it.

**Comment by bricelam** [comment]
I wonder if the original poster was intentionally bypassing EF6 and using ADO.NET directly for binding. I wonder if following [these steps](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/winforms#bind-object-to-controls) would work with SQLite or if they'd hit the same limitation.

**Comment by bricelam** [comment]
Also worth noting that [the official DDEX provider](http://system.data.sqlite.org/index.html/doc/trunk/www/downloads-unsup.wiki) hasn't been supported since VS 2015.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
