### ISSUE TITLE
EF Query translation fails with 'Case expressions may only be nested to level 10' when using EF6.3/6.4 but works in EF6.2

### ISSUE THREAD

**Issue by JasonBodley** [dotnet/ef6#1946]
When we run a complex linq query on our DB context, the query contains something like this:

```c#
address.Country == EnumCountry.NotSpecified ? "Not Specified" :
address.Country == EnumCountry.AFG ? "Afghanistan" :
address.Country == EnumCountry.ALB ? "Albania" :
...
"Invalid Enum Value"
```

and so on for a minimum of 10 conditions.
The query fails when run with EF6.3/6.4 due to badly translated SQL.

When doing this as part of a simple query e.g.

```c#
MyContext.Addresses.Select(address => new {
  Value =
    address.Country == EnumCountry.NotSpecified ? "Not Specified" :
    address.Country == EnumCountry.AFG ? "Afghanistan" :
    address.Country == EnumCountry.ALB ? "Albania" :
    ...
   "Invalid Value"
});
```

The query works fine, and translated to SQL CASE expressions are value:

```
CASE WHEN 0 THEN 'Not Specified'
         WHEN 1 THEN 'Afghanistan'
         WHEN 2 THEN 'Albania' ...
```

However, when the query becomes more complex, for some reason it begins to translate the same to something like:

```
CASE WHEN 0 THEN 'Not Specified'
         ELSE CASE WHEN 1 THEN 'Afghanistan'
         ELSE CASE WHEN 2 THEN 'Albania' ...
```

Which will fail whenever there are more than 10 comparands.

```
Case expressions may only be nested to level 10
```

### Steps to reproduce

This has been difficult to reproduce across different Entities within our context, but it appears that all queries will work as expected when using EF6.2 but will fail in EF6.4, with it only starting to fail when the queries become more and more complex (i.e. additional joins (Navigation Properties), cross applies with other entities (Context.SomeOtherEntity...).

### Further technical details
EF version: 6.3/6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10)
IDE: Visual Studio 2019

**Comment by JasonBodley** [comment]
After some digging, we have realised that some performance changes that were added as part of EF6.3, reduced the limit for the number of nodes that the plan compiler accepts for transformation: https://github.com/dotnet/ef6/pull/971/files.

I couldn't find any formal documentation around this, but after applying the `EntityFramework_EntityClient_IgnoreOptimizationLimit = true` in app config, this resolved our issue.

Perhaps this should better documented or exposed as options via `DbContext.Configuration`?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
