### ISSUE TITLE
Tables generation: column order ignored

### ISSUE THREAD

**Issue by skini82** [dotnet/ef6#1970]
Hello,
when Migrating a derived model class, the generated column order is: 
1. Derived class properties
2. Class properties

This happens even if specifing a column order on derived class.

`    

    public class TrackingProperties
    {
        [Column(Order =994)]
        public DateTime Created_at { get; set; }
        [Column(Order = 995)]
        public DateTime Edited_at { get; set; }

        [Column(Order = 996)]
        public DateTime? Deleted_at { get; set; }

        [Column(Order = 997)]
        public Guid Created_byUserGuid { get; set; }

        [Column(Order = 998)]
        public Guid Edited_byUserGuid { get; set; }

        [Column(Order = 999)]
        public Guid? Deleted_byUserGuid { get; set; }
    }
`

This class is going to be generated as table in my database:
`

    public class Company : TrackingProperties
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CompanyID { get; set; }
        public string CompanyName { get; set; } = string.Empty;
        public bool Disabled { get; set; } //if the company is disabled = true
    }
`

![immagine](https://user-images.githubusercontent.com/5445572/157645628-92cf76ff-8779-47a2-89c7-b0723fd21136.png)

My Database tables were generated through the following command:
`await dbContext.Database.EnsureCreatedAsync(cancellationToken);`

My EntityFramework library version is 6.0.3
Thanks.
Dario.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
