### ISSUE TITLE
SaveChanges interception to perform after database update was successful

### ISSUE THREAD

**Issue by pjonusas** [dotnet/ef6#1979]
We're currently using `SavedChangesAsync()` from SaveChanges interception to publish domain event, which among other data contains affected records' ids. In the event handler we pull records based on these ids and perform some actions based on other properties. Unfortunately we noticed that if we don't introduce some manual delay, sometimes it seems that handler pulls data before changes were saved.

Is there a way to use interceptor and make sure it performs some actions (e.g. publish event) after database was successfully updated?

### Further technical details
EF version: 6.0.1
Database Provider: EntityFrameworkCore.SqlServer

**Comment by ErikEJ** [comment]
Wrong repo
