### ISSUE TITLE
Update-database -script

### ISSUE THREAD

**Issue by rolandwales10** [dotnet/ef6#2004]
I am responding to documentation that describes the option to generate a script from the update-database command.  Here are two attempts at following the documentation:

PM> update-database -script 
Update-Database : A parameter cannot be found that matches parameter name 'script'.

The migration 'script' was not found.
PM> update-database script c:\temp\out.txt
Update-Database : A positional parameter cannot be found that accepts argument 'c:\temp\out.txt'.

I'm using .net core 3.1 and Visual Studio 2022.  Why is there such a disconnect between the documentation and the reality of the command?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
