### ISSUE TITLE
Issue with speed of returning data from Database

### ISSUE THREAD

**Issue by SohilAhmed** [dotnet/ef6#2020]
Hello, I'm not so sure of this is a issue of or bug in EF6 but many times there occurs slow speed of returning data while querying database. One thing that i can think of is that EF in almost all cases uses all columns from tables and in case of querying multiple tables like in a JOIN or UNION(Concat) speed of running the query is extremely slow, it takes about 2000ms (2sec) to return 10 columns and 30-40 records which is slow compared running similar query on SSMS.

Is there is a improvement to this slow speed?

Also Note that user load on database is very low and my laptop has i7 9Gen(~60% load) with 16GB RAM(8GB free most of the time), 256GB SSD(100+GB free)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
