### ISSUE TITLE
Singular / Pluralize Mistakes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2025]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Singular--Pluralize-Mistakes/10123418)._

---
When creating a Database-first EF6 dbContext, I chose the option to singularize/pluralize the created objects, which mostly works OK.

However, there are many instances where this has gone horribly wrong.
For example:
I have a database table called `JobStatus`. This results in an object called `JobStatu`,
and an entry: `public virtual DbSet JobStatus { get; set; }`

whereas, the items should be:

an object called `JobStatus`,
and an entry: `public virtual DbSet JobStatuses { get; set; }`

It shouldn't be too difficult to add an exception list for words which end in '**s**' but aren't plural,
or word-endings which don't pluralize by just adding 's' e.g. Activit**y** => Activit**ies**

This list could/should be visible in VisualStudio, so that Developers can add their own words if required.

---
#### Feedback Bot on 8/18/2022, 04:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
