### ISSUE TITLE
EF6 in .Net6 or even .Net5 freezes while materializing objects

### ISSUE THREAD

**Issue by webJose** [dotnet/ef6#2036]
## Background

ASP.net Kestrel microservices, programmed using EF6 instead of Core (God knows why) + Microsoft.AspNetCore.OData v7.5.17.

## Problem

As stated in the title, I am seeing mayor performance problems because the process of materializing seems to freeze for no good reason.  I know this by logging the execution of the **ObjectMaterialized** event from EF's **ObjectContext** object.

## Question

Is this a known issue?  If so, is there a quick workaround that does not require me moving to a different version of .Net or to EF Core?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
