### ISSUE TITLE
EF Update-database needs to be run twice

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2048]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF-Update-database-needs-to-be-run-twice/10159051)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:Community 2022 (2) (64-bit) -17.3.4]
VS 2022 Version 17.4.0 Preview 2.1
VB Solution

When I create a new EF migration I need to run update-database twice to commit changes to database.

PM> add-migration Divisions2_Add
Scaffolding migration 'Divisions2_Add'.
The Designer Code for this migration file includes a snapshot of your current Code First model. This snapshot is used to calculate the changes to your model when you scaffold the next migration. If you make additional changes to your model that you want to include in this migration, then you can re-scaffold it by running 'Add-Migration Divisions2_Add' again.

PM> update-database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
No pending explicit migrations.
Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.
You can use the Add-Migration command to write the pending model changes to a code-based migration.

PM> update-database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [202209280208100_Divisions2_Add].
Applying explicit migration: 202209280208100_Divisions2_Add.
Running Seed method.

---
#### Feedback Bot on 9/28/2022, 03:23 AM: 

(private comment, text removed)
#### andybrum on 9/28/2022, 05:23 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
