### ISSUE TITLE
Package Manager Console languaje is diferent than Visual Studio global language

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2050]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Package-Manager-Console-languaje-is-dife/10163806)._

---
Windows is in spanish language but i use Visual Studio in English for bether problem search on the web but some code on Package Manager Console is in spanish

---
#### Feedback Bot on 10/8/2022, 03:12 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
