### ISSUE TITLE
Dictionary corruption in TryGetEntryFromKeyLessStore

### ISSUE THREAD

**Issue by mishas2303** [dotnet/ef6#2059]
### Include your code

https%3A%2F%2Fazureprofiler.azurewebsites.net%2F%23%2Fprofiler%2Fcollection%2FLcsProd-westus3-uswe3lcs33bg-HighCPUEvent%2Frole%2Fbg_IN_0-instance%2Fprocess%2FWaWorkerHost.exe%2Ffunction%2Fmscorlib.ni.dll!System.Collections.Generic.Dictionary%25602%255bSystem.__Canon%252cSystem.__Canon%255d.FindEntry%2528System.__Canon%2529%2524%2523%25236003936%2Fflamegraph%3Fcontainer%3Dazure%26date%3D2022-11-10&data=05%7C01%7Cmishas%40microsoft.com%7C03ae95e93bc14709f43f08dac6f2c44b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638041043276951131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8uQen%2B1E3dkWBnUqWtIBr%2FvjOCPMXYdTrriOv%2ByzB0c%3D&reserved=0
![image](https://user-images.githubusercontent.com/56610352/202020626-1752ee97-f645-4244-b4b8-19ff8709f670.png)

It appears in https://github.com/dotnet/ef6/blob/99c172bc465492fa37f9efa07900653975ec79b4/src/EntityFramework/Core/Objects/ObjectStateManager.cs

We should be defining concurrentDictionary to prevent endless loop and corruption as 

            Dictionary<EntityKey, EntityEntry>[] stores =
                {
                    _unchangedEntityStore, _modifiedEntityStore, _addedEntityStore,
                    _deletedEntityStore
                };

EF version: 6.4.4
Database provider:
Target framework:
Operating system:
IDE:

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by mishas2303** [comment]
Can you help provide workaround please as we're seeing high CPU events quite often.?
