### ISSUE TITLE
permission denied in database 'master'

### ISSUE THREAD

**Issue by tiagomreis** [dotnet/ef6#2060]
Hi,

On a shared MSSQLSERVER 2019, where public view any database is denied to all users, Entity Framework returns the following error:

```xml
<Message>An error has occurred.</Message>
<ExceptionMessage>CREATE DATABASE permission denied in database 'master'.</ExceptionMessage>
<ExceptionType>System.Data.SqlClient.SqlException</ExceptionType>
<StackTrace> at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at
```

If we give to the user "sysadmin" or "View any database", the application works, without that, fails.

If we define wrong password, the system returns failed login.

Even with this error, using SMSS, we can login with user and password, database is not visible but if we query the MSSQL.

```
SELECT name FROM master.dbo.sysdatabases

1 master
2 tempdb
3 MYDATABASE
```

Based on this, user and password have access and can access to the MYDATABASE but for some reason without sysadmin or see "any database", the Entity Framework returns that Exception.

Any suggestion to workaround this on a shared environment where user cannot be a sysadmin / dbcreator / etc?

Thank you

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
