### ISSUE TITLE
Update System.Data.SqlClient dependency to version 4.8.5

### ISSUE THREAD

**Issue by Rockvolleyball** [dotnet/ef6#2061]
November 8th a vulnerability was reported to System.Data.SqlClient versions <=4.8.4 which is fixed in 4.8.5 (https://github.com/advisories/GHSA-8g2p-5pqh-5jmc).

We are using the latest EF6 (6.4.4) and we found that the it contains System.Data.SqlClient 4.8.1. No update available within the NuGet packages.

Is there a reason why this is not updated? Is EF6 not affected because of some other protections are in place? Or will there be an update soon to replace the System.Data.SqlClient?

Thanks!

**Comment by ErikEJ** [comment]
You can just add an explicit reference to 4.8.5

**Comment by Rockvolleyball** [comment]
OK, why not update EF6 which is still in support so that everybody will get the updated version?

**Comment by ErikEJ** [comment]
Maybe it will as part of #823 which is planned for this year @ajcvickers ?

**Comment by Rockvolleyball** [comment]
Thanks for all the work!
