### ISSUE TITLE
EF6 is no longer being actively developed. See the repo README.md for more information.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/ef6#2099]
EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by ErikEJ** [comment]
@ajcvickers assume this excludes the new MDS provider or ???

**Comment by ajcvickers** [comment]
Yes. I just created this issue so I could pin it to the top of the issues page.

**Comment by AraHaan** [comment]
What about problems that happens that prevents people from using it?

**Comment by ErikEJ** [comment]
@AraHaan "it" ??

**Comment by ajcvickers** [comment]
@AraHaan There are paid support options. If the issue is serious enough, then we would still fix it. But the bar is very high.

**Comment by PerryCodes** [comment]
Why did you remove "defaultConnectionFactory" from being added to the config file when the EF6 package is installed?
