### ISSUE TITLE
Designer file casing issue

### ISSUE THREAD

**Issue by valadas** [dotnet/ef6#2105]
When using package manager console to add a manual migration, it creates a .Designer file but in the project file it is referenced as .designer (lower case d). This is totally fine on windows, but on ubuntu build runners it fails as the filesystem is case-sensitive.

EF version: 6.4.4
Database provider: Microsoft SQL
Target framework: .NetFramework 4.7.2
Operating system: Ubuntu or other linux variants for this specific issue
IDE: Visual Studio 2022 community edition

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by valadas** [comment]
I understand. Is it a no-no or if a PR comes in it gets a little fixup? I spent about 10 minutes trying to figure it out, so just wondering if it's worth for me to invest more time into this or not.

**Comment by ajcvickers** [comment]
We're very unlikely to accept a PR for this.

**Comment by valadas** [comment]
@ajcvickers cool cool. I need to support an .NetFramework application with it. Say I make my data-layer EFCore6.0, I could not use it from a .NetFramework assembly right, so I would have to use an EFCore version that supports .NetStandard and they are all EOL anyway right ?

**Comment by ajcvickers** [comment]
Correct.
