### ISSUE TITLE
EF6 Power Tools needs documentation

### ISSUE THREAD

**Issue by DougAtClir** [dotnet/ef6#2121]
I have a VB.NET project using EF6 code first. I need to make some entity and database changes. I installed EF6 Power Tools. I have no clue what these options do. I would like to add a EDMX file to my EF6 project. Is this something that EF6 Power Tools can do? No clue.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
