### ISSUE TITLE
Need to redeploy the DLL in all the dependent projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2125]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Need-to-redeploy-the-DLL-in-all-the-depe/10391774)._

---
[severity:It's more difficult to complete my work]
I have entity project which contains 100+ entities, evetime if one of the entities is modified, we had to deploy in all depended projects to maintain same version of dll. Is there any way to reduce the deployment by having the entity dll in a shared place that if we do any update it reflects in all places or anything that will worthy to try for?

---
#### Feedback Bot on 6/15/2023, 03:23 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
