### ISSUE TITLE
Your project references the latest version of entity framework however an entity framework database 

### ISSUE THREAD

**Issue by FaizanYounasTanooli** [dotnet/ef6#2133]
I am using latest entity Framework
6.44
MySQL.Data.EntityFramework 8.0.33
MySQL.Data 8.033
MySQL Connector NET 8.0.33
Still i am getting this error in Wizard for database first 
Your project references the latest version of entity framework however an entity framework database ...

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
