### ISSUE TITLE
Changing connection string is not reflected in Package Manager Console

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2153]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Changing-connection-string-is-not-reflec/10452588)._

---
[severity:It bothers me. A fix would be nice]
Whenever I make changes to my connection strings (.config, xml), I need to restart Visual Studio in order for the changes to be reflected into the package manager console. I would expect any command that uses connection strings, like Update-Database, to fetch valid connection strings when being called and not rely any on any cache.

---
#### Feedback Bot on 8/30/2023, 03:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
