### ISSUE TITLE
Include SetAfterSaveBehavior as attribute [DatabaseGenerated] parameter

### ISSUE THREAD

**Issue by preira** [dotnet/ef6#2154]
Before describing my request, if EF 6 is no longer accepting new features, how do we suggest new features for EF 7? This info could be included in this field default text.

Now, the request is very simple to ask. At this point I have lots of minimal web api that only use attributes to describe the model, but, since EF doesn't allow naturally overriding default column values, I am facing the need to add extra complexity by including `OnModelCreating` to call `.Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Save);`. 
This should be as simple as passing a second argument to the attribute [DatabaseGenerated] but it isn't. So let's make it like that.

Regards,
João

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by preira** [comment]
Where do we submit new feature proposals? Is there aa EF 7 version project?

**Comment by ErikEJ** [comment]
@preira https://github.com/dotnet/efcore
