### ISSUE TITLE
Simple Bug Solution Path is LowerCase:

### ISSUE THREAD

**Issue by edsonfast** [dotnet/ef6#2161]
## File a bug
If you do choose to file a bug, then:

### Include your code
Parâmetro incorreto. (Exceção de HRESULT: 0x80070057 (E_INVALIDARG))
"An error occurred while trying to instantiate the DBContext type N/A."

`private Project GetStartUpProject()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var startupProjectPaths = (object[])_dte2.Solution.SolutionBuild.StartupProjects;

            if (startupProjectPaths.Length == 1)
            {
                var startupProjectPath = (string)startupProjectPaths[0];
                
                if (!Path.IsPathRooted(startupProjectPath))
                {
                    **// .Value return lowercase name folder ex: \source\repos\**
                    var solutionPath = Path.GetDirectoryName((string)_dte2.Solution.Properties.Item("Path").Value);
                    startupProjectPath = Path.Combine(
                        solutionPath,
                        startupProjectPath);
                }

                return GetSolutionProjects().Single(
                    p =>
                    {
                        ThreadHelper.ThrowIfNotOnUIThread();
                        string fullName;
                        try
                        {
                            fullName = p.FullName;
                        }
                        catch (NotImplementedException)
                        {
                            return false;
                        }

                        **// fullName is Capitalized case**
                        return fullName == startupProjectPath;
                    });
            }

            return null;
        }
`

C:\Users\Edson\source\repos\SysValley\LenusUX\LenusUX.sln
C:\Users\Edson\Source\Repos\SysValley\LenusUX\Lenus.UX.Model\Lenus.UX.Model.csproj

### Include stack traces
System.InvalidOperationException: A sequência não contém elementos de correspondência
   em System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   em Microsoft.DbContextPackage.DbContextPackage.GetStartUpProject()
   em Microsoft.DbContextPackage.DbContextPackage.DiscoverUserContextType(Type& systemContextType)

EF version: 6
Database provider:
Target framework:
Operating system:
IDE: 2019

**Comment by ErikEJ** [comment]
You should report this in the dotnet/ef6tools repo.
