### ISSUE TITLE
Visual Studio DB Save Changes 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2164]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-DB-Save-Changes-/10491908)._

---
I am having a problem with my data not saving in the SQL Server Management Database I have this data correct and everything yet when I try to enter records it never saves to the database. 

---
#### Feedback Bot on 10/16/2023, 05:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
