### ISSUE TITLE
Bulk Insert/Update from C# .Net 4.8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bulk-InsertUpdate-from-C-Net-48/10500073)._

---
Hi,

I am using Enityframework 6.0 with .Net 4.8

in a transaction have to insert batch of 50,000 rows in each iteration. committing each of them is time consuming and causing the Transaction to rollback because of time out.

there are some commercial extension packages that allows bulkinsert /bulkupdate but I am wondering if there is a other library or solution that can do insert in one shot?

---
#### Feedback Bot on 10/26/2023, 06:34 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
