### ISSUE TITLE
Package Manager Console doesn't take configuration from project only always compiles with ANY CPU option

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2173]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Package-Manager-Console-doesnt-take-con/10480838)._

---
I have project which is compiled using Debug x86. When I use Add-Migration command since last VS update I have info that project "failed to build". When I look at output I see that Package Manager console build projects with "ANY CPU" option and thats reason that it doesn't work.

When I change in Configuration Manager Active Solution Platform on ANY CPU and rebuild all it works - new migration file is generated.
But I dont want to switch on ANY CPU and then back to x86. Previously it worked. Now it doesnt. Why?

---
#### Feedback Bot on 10/2/2023, 03:51 AM: 

(private comment, text removed)
#### Nigusu Yenework [MSFT] on 10/3/2023, 11:49 PM: 

(private comment, text removed)
#### Aleksander Brzozowski on 10/4/2023, 07:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
