### ISSUE TITLE
Error when updating code to .NET 8

### ISSUE THREAD

**Issue by manutiedra** [dotnet/ef6#2184]
When updating a project that uses EF 6.4.4 and SQL Server in WIndows 10 to .NET 8.0, the following error appears:

System.TypeLoadException: Could not load type 'SqlGuidCaster' from assembly 'System.Data.SqlClient, Version=4.6.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.

I have seen there is a branch for 6.5 that uses a new version of System.Data.SqlClient. When will it be officially released?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by ErikEJ** [comment]
@manutiedra You can use my package in the meantime, looking forward to the outcome. 

https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServer

**Comment by manutiedra** [comment]
> @manutiedra You can use my package in the meantime, looking forward to the outcome.
> 
> https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServer

I will try it. Thank you
