### ISSUE TITLE
After upgrading to the latest version of vs, running DbMigrator reports an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2185]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/After-upgrading-to-the-latest-version-of/10523840)._

---
![1700710190166.png](https://aka.ms/dc/image?name=Ba24181b5c29744de9c1061da075fb8ad638363069729251579_20231123-112956-1700710190166.png&tid=a24181b5c29744de9c1061da075fb8ad638363069729251579)

---
#### Feedback Bot on 11/23/2023, 05:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
