### ISSUE TITLE
Entity Framework not able to import stored procedures

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#2191]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entity-Framework-not-able-to-import-stor/10536532)._

---
[severity:I'm unable to use this version]
After updating Visual studio from 17.7 to 17.8 we are not able to import Stored procedures using Entity Framework 6.4.4

---
#### Feedback Bot on 12/8/2023, 02:24 AM: 

(private comment, text removed)
#### Birkan Bozoğlu on 12/8/2023, 09:27 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
