### ISSUE TITLE
Exception in System.Data.Entity.Core.Common.DbProviderServices.ExpandDataDirectory(String path)

### ISSUE THREAD

**Issue by bksharma13** [dotnet/ef6#222]
I have a clickonce deployed WPF application where we have marked our SQL Local database as a data component. At times when the clickonce is upgraded our database is kind of inaccessible from the application and all DB operations fail. 

Following log is seen in the log file: 
Database Initialization Failed : **Expansion of |DataDirectory| failed while processing the connection string. Ensure that |DataDirectory| is set to a valid fully-qualified path.** 
System.ArgumentException: Expansion of |DataDirectory| failed while processing the connection string. Ensure that |DataDirectory| is set to a valid fully-qualified path. 
**at System.Data.Entity.Core.Common.DbProviderServices.ExpandDataDirectory(String path)** 
at System.Data.Entity.SqlServer.SqlProviderServices.GetOrGenerateDatabaseNameAndGetFileNames(SqlConnection sqlConnection, String& databaseName, String& dataFileName, String& logFileName) 
at System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable1 commandTimeout, StoreItemCollection storeItemCollection) 
at System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable1 commandTimeout, StoreItemCollection storeItemCollection) 
at System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase() 
at System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection) 
at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) 
at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) 

When i went to the code piece(in bold above) I can see a if block like this:
      // Verify root folder path is a real path without unexpected "..\"
        if (rootFolderPath.Contains(".."))
        {
            throw new ArgumentException(Strings.ExpandingDataDirectoryFailed);
        }

When we watched the location of the data folder, it was something like this: 
**C:\Users\<USERNAME>\AppData\Local\Apps\2.0\Data\98O56D2Q.EM1\R4LXLEL4.85M\tech..tion_0000000000000000_0003.0001_80c92a08f8b673c0\Data** 

So it results that our path at "**tech..tion_0000000000000000_0003.0001_80c92a08f8b673c0**" do contains (**..**). 

But based on the if block check this actually does not satisfies the condition because it is not at the start of the folder location. 

As per my suggestion the if block should be like:
        // Verify root folder path is a real path without unexpected "..\"
        if (rootFolderPath.StartsWith("..\", StringComparison.Ordinal))
        {
            throw new ArgumentException(Strings.ExpandingDataDirectoryFailed);
        }

Please suggest what should I do as the install folder path is not under control. The name and path is decided by the clickonce deployment. Waiting for your reply.

**Comment by bksharma13** [comment]
I posted the same in Codeplex:
_https://entityframework.codeplex.com/workitem/2965_

And ErikEJ wrote:
"Avoid using DataDirectory in your connection string, resolve the path yourself"

I don't think its a solution. Clickonce deployment on client machine cannot be controlled and this path is dynamic so how can I resolve it.

**Comment by ErikEJ** [comment]
You can resolve the path during runtime, using for example: AppDomain.CurrentDomain.BaseDirectory

**Comment by bksharma13** [comment]
I first log the Data folder of the application where the database is deployed by clickonce, when lauching and I have used below code to get it:
ApplicationDeployment.CurrentDeployment.DataDirectory

The whole stack trace I have shared is generated by the EntityFramework DLL when my code tries to implement the migration code of database on the local database when my application is loaded after logging the DATA folder path.

The problem is not because the folder path can be resolved. Its because the if block check(shared in the issue). The dynamic path generated by the clickonce contains **".."** which breaks this internal code flow of ExpandDataDirectory in EntityFramework DLL that cannot be handled by my code.

**Comment by ErikEJ** [comment]
Please share your connection string! 

You can avoid the EF code path by avoiding use of |DataDirectory| in your connection string.

**Comment by bksharma13** [comment]
This is my connection string:
```
<connectionStrings>
	<add name="LeathermanDbContext" connectionString="Server=(localdb)\v11.0;Integrated Security=true; AttachDbFileName=|DataDirectory|LeathermanDb.mdf;" providerName="System.Data.SqlClient" />
</connectionStrings>
```

Please suggest what should I use here.

**Comment by ErikEJ** [comment]
Before doing any data access, replace the AttachDbFileName key and use the generated connection string in your app:

            var connectionString = "Server=(localdb)\v11.0;Integrated Security = true;AttachDbFileName=|DataDirectory|LeathermanDb.mdf; ";
            var builder = new SqlConnectionStringBuilder(connectionString);
            builder.AttachDBFilename = Path.Combine(ApplicationDeployment.CurrentDeployment.DataDirectory, "LeathermanDb.mdf");
            connectionString = builder.ConnectionString;

**Comment by bksharma13** [comment]
I am using Code first approach in my application. And your suggestion suits fit for cases when I would have created a manual connection to the local DB in the application.
The only action I take manually is verify if SQL instance is installed correctly and the required DB migration is applied successfully. Rest action like connection is done by the EntityFramework code first approach.

**Comment by ErikEJ** [comment]
Yes, I understand, but Code First is not pure magic, just pass your own connection string to the DbContext constructor - https://msdn.microsoft.com/en-us/library/gg679467(v=vs.113).aspx

**Comment by bksharma13** [comment]
Thanks for the suggestion. I can try this approach as of now and see the behavior. Will update you after my client doesn't report us back. :)

**Comment by ajcvickers** [comment]
Assigning to @divega to follow-up.

**Comment by divega** [comment]
**Note for triage:** This is a legitimate bug.

As explained by @bksharma13 one of the checks that we have in `ExpandDataDirectory()` is incorrect: It currently throws for any data directory path that contains `".."`. This results in an exception for valid direct paths such as `@"c:\dots..are..valid..inside"`. 

It also seems that ClickOnce has a propensity to produce deployment paths that contain double dots. Here are two previous hits I found:

http://stackoverflow.com/questions/32169633/publishing-winforms-app-that-uses-ef-code-first
http://forum.vingrad.ru/forum/topic-388917/kw-net-entity-framework-clickonce.html 

I believe the method should only fail if the data directory path contains `@"\..\"`, ends with `@"\.."`, starts with `@"..\"` or is equal to `".."`. 

Alternatively we could avoid altogether throwing and instead we could just expand the data directory using `Path.GetFullPath()` (although you would still hit an exception at a later point if the database provider requires direct paths only, as it is the case with SqlClient).

@bksharma13 I would recommend pursuing the workaround that @ErikEJ suggested. If you want to use the actual value of |DataDirectory| and do the expansion yourself, you can obtain it with `AppDomain.CurrentDomain.GetData("DataDirectory")`.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
