### ISSUE TITLE
Documentation for HResult -2146232004

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/ef6#2259]
I have a question about the HResult `-2146232004` defined here: https://github.com/dotnet/ef6/blob/758b816caa8df17aba10a37b5b64b74c59f8e08a/src/EntityFramework/Core/EntityCommandExecutionException.cs#L16

Is this HResult documented anywhere and contains a code name? When parsed it gives me the facility `FACILITY_URT` but with an un-named code `6460`. Do you know if this code has a name?

And to make it clear. I'm asking because I'm working on an open-source project that will let you parse an HResult and output various information like the facility, code, and description.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
