### ISSUE TITLE
No app.config override for Microsoft.Data.SqlClient?

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/ef6#2261]
I was having some troubles with integrating Microsoft.Data.SqlClient into one of my projects when I noticed something in my app.config that isn't in my other app.configs:

```xml
<configuration>
  <configSections>
  <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework"
      type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
      requirePermission="false"/>
  </configSections>

  <!-- ....more configuration... -->
  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer"/>
    </providers>
  </entityFramework>
</configuration>
```

I removed that section and my tests started working again. 

Is there a way to incorporate that app.config settings in place of the method used here: https://github.com/dotnet/ef6/issues/2250? 

Also, do you have an FAQ on how to transition from System.Data.SqlClient to Microsoft.Data.SqlClient?

**Comment by ErikEJ** [comment]
@EdLichtman use the new package and refer to the readme here: https://www.nuget.org/packages/Microsoft.EntityFramework.SqlServer/6.5.0-preview2-24180-01#readme-body-tab

**Comment by EdLichtman** [comment]
Oh I see! I was looking for Microsoft.Data.Entity.SqlServer.SqlProviderServices instead of System....MicrosoftSqlProviderServices.

Thanks!
