### ISSUE TITLE
EF 6.5.0 RTM NuGet Package BROKEN

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/ef6#2262]
# RTM PACKAGE FAILURE

There is an error in the package for 6.5.0 that has broken the EF build process in Visual Studio. The package is not being built properly, therefore `EntityDeploy` is no longer being called to compile EDMX files into the project.

👉🏻 **For people experiencing this issue, there is a temporary workaround, see below.** 👈🏻

## SYMPTOMS:
You will suddenly get a "Metadata cannot be loaded" error in any project that leverages the `DbContext`, where the code previously functioned normally.

## IMPACT
Automated builds that were previously working are now failing. I spent several hours tracking down why my services suddenly stopped working.

## NEEDED RESOLUTION
- [ ] **EntityFramework 6.5.0 package must be deprecated on NuGet.org IMMEDIATELY**
- [ ] Revert the change from Preview 2 that broke the build folder
- [ ] The release process should be validating the package contents before deploying the package

## EVIDENCE
New EntityFramework 6.5.0 RTM vs EntityFramework 6.4.4 RTM packages:

![image](https://github.com/dotnet/ef6/assets/1657085/73494fbf-8ab7-42e6-9829-e602a790ac73)
![image](https://github.com/dotnet/ef6/assets/1657085/1be1fb70-aaa9-4e13-ad3d-260f6bbced37)

## WORKAROUND
In the project with your EDMX file, replace your `<PackageReference Include="EntityFramework" ... />` line with the following entries:

```xml
        <PackageReference Include="Microsoft.EntityFramework.SqlServer" Version="6.*" />
        <PackageReference Include="EntityFramework" Version="6.4.*" ExcludeAssets="compile,runtime" NoWarn="NU1605" />
```
This will tell the build process to use the `EntityCompile` tasks from the EF 6.4.4 package, [but NOT to reference anything in the `lib` folder for compilation](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets). That means the downstream reference to `EntityFramework` 6.5 from the `Microsoft.EntityFramework.SqlServer` package will still get compiled into the build and your code will work correctly. The "NoWarn" attribute will tell the build process not to complain that you're referencing a version that the `.SqlServer` package doesn't like.

**Comment by robertmclaws** [comment]
@ajcvickers @ErikEJ tagging you both since this is a "broken in Production" situation.

**Comment by robertmclaws** [comment]
Updated with a verified workaround.

**Comment by ErikEJ** [comment]
@robertmclaws I created a PR with a fix...

**Comment by AndriySvyryd** [comment]
Fixed in [ac4a11e](https://github.com/dotnet/ef6/commit/ac4a11e42e9521b992a51b008db20317dca794c1)

**Comment by robertmclaws** [comment]
Thanks everyone for getting this fixed so quickly!

**Comment by birbilis** [comment]
wonder if issues with the NuGet package (the unrecognized framework shown in 1st screenshot) could be caught automatically via some test case

**Comment by robertmclaws** [comment]
The NuGet package is just a zip file, so there absolutely could be a smoke test to enumerate through the file and make sure the structure is the way it is supposed to be. 

Sounds like something I could add to [Breakdance](https://github.com/cloudnimble/breakdance).

**Comment by AndriySvyryd** [comment]
Adding any sort of automated testing is out of scope for EF 6.x
And we use a very different release process for EF Core

**Comment by robertmclaws** [comment]
> Adding any sort of automated testing is out of scope for EF 6.x And we use a very different release process for EF Core

I mean, if someone contributes a fix to make sure people's builds don't randomly break again, are you going to reject it? This took significant time and expense out of my weekend to triage and fix... I would prefer to not have that happen again.

**Comment by AndriySvyryd** [comment]
> > Adding any sort of automated testing is out of scope for EF 6.x And we use a very different release process for EF Core
> 
> I mean, if someone contributes a fix to make sure people's builds don't randomly break again, are you going to reject it? This took significant time and expense out of my weekend to triage and fix... I would prefer to not have that happen again.

We might, since code reviews can take a non-trivial amount of time and the chance of hitting the same kind of packaging issue isn't high. Also, any new dependency would be unacceptable.

**Comment by birbilis** [comment]
maybe GitHub could have similar sanity checks for automated NuGet package releases, but guess EF isn't using that pipeline
