### ISSUE TITLE
Bug: Nuget doesn't have the build DLLs?

### ISSUE THREAD

**Issue by bh3605** [dotnet/ef6#2294]
##Problem

Installing any version beyond 6.2 doesn't download everything.

You can see in the image below there are compile time assemblies in 6.2.0
![image](https://github.com/user-attachments/assets/c64c9a21-c70b-4aea-ac53-7a671e067790)

However, in 6.5.1, there are none.
![image](https://github.com/user-attachments/assets/06ad4240-cce6-4e89-a303-6ae92082431c)

Help?

**Comment by ErikEJ** [comment]
@bh3605 Does the package not work for you??

**Comment by bh3605** [comment]
Nope, I use Nuget to install it and it looks like not everything is downloaded

**Comment by bh3605** [comment]
That probably explains. Thanks
