### ISSUE TITLE
If an entity MyEntity has a property called MyProp, I cannot create an entity called MyEntity_MyProp. How do I fix that?

### ISSUE THREAD

**Issue by icnocop** [dotnet/ef6#308]
Copied from https://github.com/aspnet/EntityFramework/issues/1979.

I'm using Entity Framework 6, with POCO and fluent-API and I've noticed an annoying bug.

If I have an entity called `MyEntity` and this entity has a property called `MyProp`, that makes it impossible to create an entity called `MyEntity_MyProp`.

Exception:
```
The item with identity 'MyEntity_MyProp' already exists in the metadata collection.\r\nParameter name: item
```
The error immediately goes away if I rename any of the entities, or rename the properties.

The "bug" is obvious: the key [EntityName]_[PropertyName] must be unique in the metadata collection.

Screenshot:
![argumentexception](https://user-images.githubusercontent.com/507649/27759096-48c3b1fc-5ddb-11e7-9576-f3ba306b506a.png)

I'm migrating a huge Entity Framework model with 390+ classes from EF 4, database first, to EF 6, code first, with fluent-API. It's out of question to rename the entities or the tables.

How do I solve that?

**Comment by ajcvickers** [comment]
@icnocop Does database first with EF6 still work correctly?

**Comment by icnocop** [comment]
I ran into this issue when trying to switch from Entity Framework 4 and database first to Entity Framework 6 and code first. I didn't actually try EF6 and database first.

I used the POCO Generator Wizard to create the code first database module, and was eventually able to work-around the issue by just manually renaming one of the properties.

I'm currently using Entity Framework 6.1.3 and code first and things are working as expected.

Thank you.

**Comment by ajcvickers** [comment]
Triage: investigate #427 and this as the same issue.

**Comment by kmkelly2015** [comment]
@ajcvickers Is this issue still being considered?

**Comment by FloMaetschke** [comment]
I have the same issue. This is really annoying, when you have an existing enterprise database you have to work with and can't change it.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
