### ISSUE TITLE
"System assertion check has failed" when querying an in-memory table that has clustered columnstore index (SQL Server 2016)

### ISSUE THREAD

**Issue by jakubro** [dotnet/ef6#337]
## Current Behavior

After adding clustered columnstore index to an in-memory table in SQL Server 2016, I cannot query this table from Entity Framework, because an `EntityCommandExecutionException` exception is thrown. This exception contains an inner exception with message implying that `a system assertion check has failed.`

However executing the same query from SQL Server Management Studio (SSMS) is successful. If I remove the clustered columnstore index from this table, then querying it from Entity Framework is successful too.

The mentioned error appears only when using EF designer generated model, i.e. not the code-first approach.

## Expected Behavior

Querying in-memory table with clustered columnstore index should succeed.

## Steps to Reproduce
1. In SQL Server 2016 SP1 create in-memory table with clustered columnstore index
```sql
CREATE TABLE [dbo].[DemoData] (
    [Id] uniqueidentifier NOT NULL,
    [Date] datetime2 NOT NULL
    CONSTRAINT [PK_DemoData_Id] PRIMARY KEY NONCLUSTERED HASH ([Id]) WITH (BUCKET_COUNT = 512),
    INDEX [CCI_DemoData] CLUSTERED COLUMNSTORE
)
WITH (
    MEMORY_OPTIMIZED = ON,
    DURABILITY = SCHEMA_AND_DATA
)
GO
```

2. Create model using the "EF Designer from database" template

```cs
public class DemoDataDbContext : DbContext
{
    public DemoDataDbContext()
        : base("name=demoDataDb")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<DemoData> DemoDatas { get; set; }
}

public class DemoData
{
    public System.Guid Id { get; set; }
    public System.DateTime Date { get; set; }
}   
```

3. Use this connection string
```
metadata=res://*/Model.csdl|res://*/Model.ssdl|res://*/Model.msl;provider=System.Data.SqlClient;provider connection string=&quot;
            data source=.\sql2016;initial catalog=DemoDataDb;persist security info=True;user id=sa;password=*******;MultipleActiveResultSets=True;App=EntityFramework&quot;
```

4. Query table created in step 1 from EntityFramework 6.1.3
```cs
using (var context = new DemoDataDbContext())
{
    var result = context.DemoDatas.Select(t => t.Id).ToList();
}
```

5. Following exception is thrown

```
System.Data.Entity.Core.EntityCommandExecutionException occurred
  HResult=0x8013193C
  Message=Calling 'Read' when the data reader is closed is not a valid operation.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.HandleReaderException(Exception e)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()

Inner Exception:
  HResult: -2146232060
  System.Data.SqlClient.SqlErrorCollection: 
    A system assertion check has failed. Check the SQL Server error log for details. Typically, an assertion failure is caused by a software bug or data corruption. To check for database corruption, consider running DBCC CHECKDB. If you agreed to send dumps to Microsoft during setup, a mini dump will be sent to Microsoft. An update might be available from Microsoft in the latest Service Pack or in a Hotfix from Technical Support.
    Cannot continue the execution because the session is in the kill state.
    A severe error occurred on the current command.  The results, if any, should be discarded.
    Location:	 columndataset.cpp:2435     Expression:	 !m_pDud->GetVerScanParams ()->IsScanVersioned ()
  Source=.Net SqlClient Data Provider
  StackTrace:
    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
    at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
    at System.Data.SqlClient.SqlDataReader.Read()
    at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
```

## Context (Environment)
- **SQL Server** - Microsoft SQL Server 2016 (SP1-CU4) (KB4024305) - 13.0.4446.0 (X64)   Jul 16 2017 18:08:49   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 15063: ) (Hypervisor)
- **Entity Framework** - 6.1.3
- **.NET Target Framework** - .NET 4.6.2

**Comment by divega** [comment]
@jakubro would it be possible for you to try executing the same SQL generated by EF6 through the ADO.NET provider? SqlClient may configure the query differently than SSMS.

**Comment by jakubro** [comment]
@divega I've made a runnable demo for this issue - [https://github.com/jakubro/ef-inmemory-columnstore].

I'd run the EF-generated query [through ADO.NET](https://github.com/jakubro/ef-inmemory-columnstore/blob/master/src/DemoDataApp/Program.cs#L84-L99), but that was executed correctly.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
