### ISSUE TITLE
Unable to debug EF queries: Children could not be evaluated

### ISSUE THREAD

**Issue by MatejQ** [dotnet/ef6#399]
Hello,
yesterday we upgraded EF in our solution from 6.1.3 to 6.2.0. But now we cannot debug queries in debugger, it says "Children could not be evaluated". Using VS2015 Update 3.

![1](https://user-images.githubusercontent.com/14346231/32840930-59bc75b6-ca19-11e7-83c0-1f9a75241f1a.png)

The only possible workaround is to add a call to .ToList() but it is very cumbersome as it requires stopping debugging, changing code, recompiling and relaunching debug session.
Note - this worked correctly in version 6.1.3 and I confirmed it works again when I downgrade.
This issue is a major showstopper for us. Can you please fix this?

**Comment by Spongman** [comment]
how about 6.2.1?

**Comment by ajcvickers** [comment]
@Spongman That might happen but currently we have not yet reproduced this--any runnable project/solution that exhibits this issue would be useful. Also, there may not be a 6.2.1 depending on the schedule for 6.3.0.

**Comment by JukkaM** [comment]
We are facing the same issue. We upgraded EF from 6.1.3 to 6.2.0 and now we are not able to debug EF queries before they are actually loaded from database in the code. The problem exists both in VS2015 Update 3 and VS2017. We tried to eliminate possible causes by removing some EF extensions from our project but they didn't have any effect.

We got the same error as @MatejQ when we had set "Use Managed Compatibility Mode" on in Visual Studio Debugger settings. But when the settings was unchecked, we got more detailed error saying: "The function evaluation requires all threads to run." and when trying to force the query execution "Unable to evaluate the expression. Operation not supported. Unknown error: 0x80070057."

Hopefully this will be fixed soon as this slows down debugging.

**Comment by MatejQ** [comment]
Today I tried it again, with nightly EF version 6.3.0-beta1-61231. Sadly, the problem is still there.
I made a small console application that you can attach to local db server where the problem can be easily reproduced.
Note: I used instance .\sql2012 and project is reading from master database.
[EFBug.zip](https://github.com/aspnet/EntityFramework6/files/1663828/EFBug.zip)

**Comment by MatejQ** [comment]
So you got the application where problem can be reproduced. Anyone had a look at it yet? Any news?

**Comment by Spongman** [comment]
i'm not able to repro this any more with vs 15.5.7

**Comment by MatejQ** [comment]
Ok, please try with VS2015 Update 3 (version 14.0.25431.01)

**Comment by MatejQ** [comment]
Can someone please take this issue?
Upgrading Visual Studio is not an option because we have to support Silverlight and MS dropped it.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
