### ISSUE TITLE
Sequence contains no elements when trying to create index on inherited properties

### ISSUE THREAD

**Issue by mstaessen** [dotnet/ef6#409]
We have a couple of TPC hierarchies where we have EntityTypeConfigurations for the base classes and EntityTypeConfigurations for the child classes.

The configurations for the children, use 

    Map(m => {
        m.MapInheritedProperties();
    })

to propagate the mappings for the base class.

In our case, the base class also defines a column that needs to be indexed. When adding the requried ```HasIndex()``` on the EntityTypeConfiguration of the base class, the index is not created for the leaf types. When adding it on the EntityTypeConfiguration of the leaf type, EF generates the most descriptive exception: "Sequence contains no elements"

After some digging it appears that - in order to configure the index - EF will look for properties in DeclaredProperties, which does not contain the properties of the base type. This then causes an exception on ```EntityTypeExtensions.GetDeclaredPrimitiveProperty(EntityType, PropertyInfo)```.

How would we need to map this scenario without having to repeat the mapping of the base class and without having to derive from a custom EntityTypeConfiguration class?

I was thinking about something like ```MapInheritedIndexes()``` but that would also not cover the TPC scenario where you want to span a single index over properties in base and derived types.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
