### ISSUE TITLE
SQL DROP CONSTRAINT WITH SCHEMA NAMES

### ISSUE THREAD

**Issue by Paul-C-Caesar** [dotnet/ef6#491]
[`System.Data.Entity.SqlServer.SqlServerMigrationSqlGenerator.DropDefaultConstraint`](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework.SqlServer/SqlServerMigrationSqlGenerator.cs#L832) does not construct `DROP CONSTRAINT` correctly when using schema names.

A default constraint name is created from the schema, table and column name and a query `FROM sys.default_constraints` shows the name as:

 `DF_[Example.Test].Table1_UtcDateTime`
(`DF_[SchemaName].TableName_ColumnName`)

The constructed drop constraint is:

`ALTER TABLE [Example.Test].[Table1] DROP CONSTRAINT [DF_[Example.Test].Table1_UtcDateTime]
`

This should be constructed with a double `]` after the schema name as:

`ALTER TABLE [Example.Test].[Table1] DROP CONSTRAINT [DF_[Example.Test]].Table1_UtcDateTime]`

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
