### ISSUE TITLE
ScriptIgnore attribute causing invalid Migration

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/ef6#519]
From VS Feedback:

Using an existing project with an entity that has the [ScriptIgnore] attribute and another attribute, such as [ForeignKey]. 

Migrations are set up and have been performed before.

There are no pending migrations and no migrations needed. Running the application in the debugger does NOT trigger the error when the database and code are out of sync.

In the package manager console, run the add-migration command. You would expect to see an empty up and empty down. Instead, you see changes. In this case, it created a new column for the foreign key.

```C#
    public class CustomFieldValue
    {
        public int CustomFieldValueId { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }

        public int CustomFieldId { get; set; }

        [JsonIgnore]
        [ScriptIgnore(ApplyToOverrides = true)]
        [Required]
        [ForeignKey("CustomFieldId")]
        public virtual CustomField CustomField { get; set; }
    }

Here is the invalid migration:
   public partial class testing : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CustomFieldValues", "CustomFieldId", "dbo.CustomFields");
            DropIndex("dbo.CustomFieldValues", new[] { "CustomFieldId" });
            AddColumn("dbo.CustomFieldValues", "CustomField_CustomFieldId", c => c.Int());
            CreateIndex("dbo.CustomFieldValues", "CustomField_CustomFieldId");
            AddForeignKey("dbo.CustomFieldValues", "CustomField_CustomFieldId", "dbo.CustomFields", "CustomFieldId");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.CustomFieldValues", "CustomField_CustomFieldId", "dbo.CustomFields");
            DropIndex("dbo.CustomFieldValues", new[] { "CustomField_CustomFieldId" });
            DropColumn("dbo.CustomFieldValues", "CustomField_CustomFieldId");
            CreateIndex("dbo.CustomFieldValues", "CustomFieldId");
            AddForeignKey("dbo.CustomFieldValues", "CustomFieldId", "dbo.CustomFields", "CustomFieldId");
        }
    }
```

We found this because we were doing a real migration where we did have changes to other entities. And we wondered what had changed in this table. But nothing changed.

If we remove the [ScriptIgnore] attribute and run add-migration. We get an empty up and empty down.

**Comment by trueleader** [comment]
Same here. We have the problem since multiple months but could´t find the issue until today.

One of our solutions have ~200 entities split into multiple projects. We was thinking about some caching issues with Visual Studio because after a fresh VS startup with the above solution (which takes ~5 minutes to load ... may be caused by multiple required plugins such as resharper, devexpress and others) an initial "Add-Migration" creates a correct migration. A second run want to create new foreign-key columns.

We striped down the issue that removing "ScriptIgnore" from a navigation property (used for ignoring in JSON serialization) - which additionally uses "ForeignKey" or "InverseProperty" - solves the problem.

```C#
public partial class TIMEPERIOD
{
	...
	[ScriptIgnore]
	[InverseProperty(nameof(AUDITTYPE.TIMEPERIOD_VALIDFROM))]
	public virtual IList<AUDITTYPE> AUDITTYPE_VALIDFROM { get; set; } = new List<AUDITTYPE>();
	[ScriptIgnore]
	[InverseProperty(nameof(AUDITTYPE.TIMEPERIOD_VALIDTO))]
	public virtual IList<AUDITTYPE> AUDITTYPE_VALIDTO { get; set; } = new List<AUDITTYPE>();
	...
}
public partial class AUDITTYPE
{
	...
	public int? VALIDFROMID { get; set; }
	public int? VALIDTOID { get; set; }
	...
	[ForeignKey(nameof(VALIDFROMID))]
	public virtual TIMEPERIOD TIMEPERIOD_VALIDFROM { get; set; }
	[ForeignKey(nameof(VALIDTOID))]
	public virtual TIMEPERIOD TIMEPERIOD_VALIDTO { get; set; }
	...
}
```

tries to create

```C#
...
AddColumn("dbo.AUDITTYPE", "TIMEPERIOD_TIMEPERIODID", c => c.Int());
AddColumn("dbo.AUDITTYPE", "TIMEPERIOD_TIMEPERIODID1", c => c.Int());
...
```

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
