### ISSUE TITLE
EF6.2 error the function evaluation needs to run all the threads 

### ISSUE THREAD

**Issue by zxcyfz** [dotnet/ef6#602]
var query = db.User.Where(t => t.Disable == 0);
            query = query.Where(t => t.DeptName != null);
            query = query.Where(t => t.StaffName=="Json");
            var list = query.ToList();
When debugging, I can look at the results of the query in version 6.13, but in version  6.2 it will report the function evaluation needs to run all the threads of the error, or that can not calculate the expression, not support the operation。
How do I normally debug in version 6.2?

**Comment by ajcvickers** [comment]
@zxcyfz What version of VS are you using?

**Comment by zxcyfz** [comment]
vs2017 and vs2013

**Comment by zxcyfz** [comment]
@ajcvickers vs2017 and vs2013
