### ISSUE TITLE
Enable migration is generating query without escape character which is causing compilation error

### ISSUE THREAD

**Issue by archanasoni** [dotnet/ef6#613]
Hi,

We are working to have Code First support  for IBM EntityFramework Provider . We are targeting EF 6.1.3 currently.
Our problem starts when we enable migration, It is generating class file but from procedure body ignoring the escape character, for example Generated body in *_InitialCreate.cs is:
  body:
                    @"insert into "dbo"."Students"("StudentId", "StudentName", "DoB")
                      values (StudentId, StudentName, DoB)"

it results in compilation error.
We could observe that during forming the sql \" is getting added but when value is assigned to writer, \ is ignored.

Now we need to figure out a way to remain \ with " in *.cs file as well for procedure body.

Would you suggest some pointer here ?

Regards,
Archana

**Comment by archanasoni** [comment]
We're still waiting for response.. it has become critical for us, as in few days we have to release and bcoz of this we are unable to support SP.

**Comment by CZEMacLeod** [comment]
This seems to be the same issue I raised as #198 and was supposed to be fixed with my pull #202.
@bricelam merged it but then the changes were reverted as they got mixed up with another fix I believe?

Anyway, the easy way round this for now, is to inherit from CSharpMigrationCodeGenerator, override the Quote method with the fix in #202 and then configure your migrations class to use your new code generator class.

**Comment by CZEMacLeod** [comment]
@archanasoni From memory you add to the Migration Configuration class inside the constructor a line like `this.CodeGenerator = new MyCSMigrationCodeGenerator();`

**Comment by archanasoni** [comment]
Thanks @CZEMacLeod , But ours is  EF Provider like MS EF.  So when our Customer runs Enable-Migrations, Generated Configuration.cs either must have this.CodeGenerator = new Db2CSharpMigrationCodeGenerator();

OR internally through some services dependency, it should be taken care.

We don't want our End User to tell to manually edit Configuration.cs.

Hence we are looking to add this as services.

**Comment by archanasoni** [comment]
@bricelam any pointers on this ?

**Comment by ajcvickers** [comment]
@archanasoni We will look into fixing this for the next release.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
