### ISSUE TITLE
Can't add second record to Many-To-Many entity

### ISSUE THREAD

**Issue by agpreynolds** [dotnet/ef6#625]
I'm having an issue where I can't insert a second record for a Many-To-Many entity. See code example and explanation below. Apologies for the poor issue name, description could do with improving

```
Exception message: Violation of PRIMARY KEY constraint 'PK_AccountUser'. Cannot insert duplicate key in object 'dbo.LinkedAccountIssuer'. The duplicate key value is (e90a665e-7d32-4954-9426-58f65409a74a, 1).
The statement has been terminated.
```

### Steps to reproduce
```
    public class Account
    {
        [Key]
        public Guid Id { get; set; }

        public string Name { get; set; }
    }
```

```
    public class User
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
    }
```

```
    public class AccountUser
    {
        [Key, ForeignKey("User"), Column(Order = 0)]
        public int UserId { get; set; }

        [Key, ForeignKey("Account"), Column(Order = 1)]
        public Guid AccountId { get; set; }

        public bool Administrator { get; set; }

        public Account Account { get; set; }
        public User User { get; set; }
    }
```

Given that user with id "1" already exists as administrator under account "e90a665e-7d32-4954-9426-58f65409a74a" I then run the following blocks to link my user to another account.

```
Guid newAccountId = Guid.ParseExact("6010ac5f-d0e8-43c7-90de-d9efca632043");

AccountUser accountUser = new AccountUser()
{
    user = _loggedInUser,
    accountId = newAccountId
};

using (MyContext context = new MyContext())
{
    context.AccountUsers.Add(accountUser);
    context.SaveChanges();
}
```

This generates an exception claiming that I would be violating my primary key:
```
Violation of PRIMARY KEY constraint 'PK_AccountUser'. Cannot insert duplicate key in object 'dbo.LinkedAccountIssuer'. The duplicate key value is (e90a665e-7d32-4954-9426-58f65409a74a, 1).
The statement has been terminated.
```
Note how the Guid is for the pre-existing accountId and not the new one I have specified.

I then tried one more thing which surprised me:

```
Guid newAccountId = Guid.ParseExact("6010ac5f-d0e8-43c7-90de-d9efca632043");

AccountUser accountUser = new AccountUser()
{
    userId = _loggedInUser.Id,
    accountId = newAccountId
};

using (MyContext context = new MyContext())
{
    context.AccountUsers.Add(accountUser);
    context.SaveChanges();
}
```

This worked and allowed me to insert the new value as expected.

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2017 15.7.2

_N.B. Code example is only based on my real code, and some has been produced freehand. Therefore syntax / naming issues in the code sample are possible._

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
