### ISSUE TITLE
Entity Splitting implies that a mapping fragment with no Properties call will contain all remaining properties, but that appears not to work

### ISSUE THREAD

**Issue by kEph13** [dotnet/ef6#631]
The helper text for the Properties method when mapping a split entity fragment says: 

_Configures the properties that will be included in this mapping fragment. If this method is not called then all properties that have not yet been included in a mapping fragment will be configured._

However, with the following entity:
```
public class Partner
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string StateOrProvidence { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string AddressLine2 { get; set; }
        public decimal? Longitude { get; set; }
        public decimal? Latitude { get; set; }
        public string TimeZone { get; set; }

        public long SyncStatus { get; set; }
        public DateTime? SyncUpdate { get; set; }
}
```
And the following mapping definition in OnModelCreating:
```
modelBuilder.Entity<Partner>()
                .Map(map =>
                {
                    map.Properties(p => new
                    {
                        p.Id,
                        p.SyncStatus,
                        p.SyncUpdate
                    });
                    map.ToTable("Partners", "sync");
                })
                .Map(map =>
                {
                    map.ToTable("Partners", "dbo");
                });
```
I get an InvalidOperationException saying:

_Properties for type "Partner" can only be mapped once. The non-key property 'SyncStatus' is mapped more than once. Ensure the Properties method specifies each non-key property only once._

Is this a documentation issue or a bug or am I missing something?

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: VS2017 15.8.4

**Comment by brandonmartinez** [comment]
Any progress on this? I'm running into the exact same issue.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
