### ISSUE TITLE
Private property in base class can't be mapped using EntityTypeConfiguration

### ISSUE THREAD

**Issue by OskarKlintrot** [dotnet/ef6#640]
*Describe what is not working as expected.*

I try to move some backing properties to an abstract base class and map them using `EntityTypeConfiguration<T>`. If they are in the concrete class or `public` it works but not when they are `private` or `protected`. This seem similar to a bug @ajcvickers talks about [here](https://stackoverflow.com/questions/10268062/does-the-entity-framework-code-first-support-readonly-navigation-property#comment13206757_10268214) but then it didn't work with public either.

*If you are seeing an exception, include the full exceptions details (message and stack trace).*
When I try to add a migration I get this:

`The property '_startDate' is not a declared property on type 'ProductDateInterval'. Verify that the property has not been explicitly excluded from the model by using the Ignore method or NotMappedAttribute data annotation. Make sure that it is a valid primitive property.`

### Steps to reproduce
Base class:
```Csharp
public abstract class DateIntervalBase
{
    public int Id { get; set; }

    [Column("StartDate", TypeName = "Date")]
    private DateTime? _startDate { get; set; }

    [Column("EndDate", TypeName = "Date")]
    internal protected DateTime? _endDate{ get; set; }

    [NotMapped]
    public LocalDate? StartDate
    {
        get => _startDate.HasValue ? LocalDate.FromDateTime(_startDate.Value) : (LocalDate?)null;
        set => _startDate= value.HasValue ? value.Value.ToDateTimeUnspecified() : (DateTime?)null;
    }

    [NotMapped]
    public LocalDate? EndDate
    {
        get => _endDate.HasValue ? LocalDate.FromDateTime(_endDate.Value) : (LocalDate?)null;
        set => _endDate= value.HasValue ? value.Value.ToDateTimeUnspecified() : (DateTime?)null;
    }

    public class DateIntervalBaseConfiguration<T> : EntityTypeConfiguration<T>
        where T : DateIntervalBase
    {
        public DateIntervalBaseConfiguration()
        {
            Property(x => x._startDate);
            Property(x => x._endDate);
        }
    }
}
```
```Csharp
[Table("ProductDateInterval")]
public class ProductDateInterval : DateIntervalBase
{
    public int ProductId { get; set; }

    public virtual Product Product { get; set; }
}
```
```Csharp
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    modelBuilder.Configurations
        .Add(new DateIntervalBase.DateIntervalBaseConfiguration<ProductDateInterval>())
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
