### ISSUE TITLE
EF 6.2 generates an incorrect migration when having unique constraints consisting of multiple columns

### ISSUE THREAD

**Issue by rubend30** [dotnet/ef6#665]
This bug occurs with Code First Migrations using Entity Framework 6.2. When configuring unique constraints on multiple properties (multiple columns for one constraint) and having at least two of these constraint on one class, then the problem occurs.

The following link is to my stackoverflow question about it: [link](https://stackoverflow.com/questions/53316623/ef-6-2-unique-constraints-with-multiple-overlapping-columns-is-not-generated-c?noredirect=1#comment93526119_53316623)

```
Exception message: No exception
Stack trace: No stack trace
```

### Steps to reproduce
The following Fluent API lines configure my two unqiue constraints consisting of each 3 columns. These two have multiple columns that are overlapping.

```c#
modelBuilder.Entity<TagDTO>().HasIndex(p => new { p.SiteId, p.InputId, p.Name }).IsUnique();
modelBuilder.Entity<TagDTO>().HasIndex(p => new { p.SiteId, p.InputId, p.SqlColumn }).IsUnique();
```

Next when creating the migration code this is the result of those two lines:
```c#
...
.Index(t => new { t.SiteId, t.InputId, t.Name }, unique: true)
.Index(t => t.SqlColumn, unique: true, name: "IX_SiteId_InputId_SqlColumn")
...
```

With the following migration code only the `t.Name` property will have the correct unqiue constraint.
The `t.SqlColumn` must be unique even if the the `t.SiteId` and/or `t.InputId` are different wich is not what I configured.

The excpected result should have been the following:
```c#
...
.Index(t => new { t.SiteId, t.InputId, t.Name }, unique: true)
.Index(t => new { t.SiteId, t.InputId, t.SqlColumn }, unique: true)
...
```

In the attached project is a small application with one Migration that shows that the code generated.
[ConsoleApp2.zip](https://github.com/aspnet/EntityFramework6/files/2588478/ConsoleApp2.zip)

### Further technical details
EF version: 6.2
Database Provider: System.Data.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.7

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
