### ISSUE TITLE
SqlException: Could not find stored procedure ''. when using IDbCommandInterceptor

### ISSUE THREAD

**Issue by dekenless** [dotnet/ef6#666]
If you implement a IDbCommandInterceptor and modify the command text the following exception is thrown:

> System.Data.Entity.Core.EntityCommandExecutionException
>   HResult=0x8013193C
>   Message=An error occurred while executing the command definition. See the inner exception for details.
>   Source=EntityFramework
>   StackTrace:
>    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
>    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.Execute(EntityCommand entityCommand, CommandBehavior behavior)
>    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteReader(CommandBehavior behavior)
>    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteNonQuery()
>    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunctionCommand(EntityCommand entityCommand)
>    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass4b.<ExecuteFunction>b__4a()
>    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
>    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass4b.<ExecuteFunction>b__49()
>    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
>    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction(String functionName, ObjectParameter[] parameters)
>    at DbInterceptorBug.ppv74Entities.TestProc() in c:\projects\DbInterceptorBug\DbInterceptorBug\Model1.Context.cs:line 33
>    at DbInterceptorBug.Program.Main(String[] args) in c:\projects\DbInterceptorBug\DbInterceptorBug\Program.cs:line 17
> 
> Inner Exception 1:
> SqlException: Could not find stored procedure ''.
> 

### Steps to reproduce
Attached is a sample solution illustrating the issue. The problem occurs with an EDMX when a stored procedure is executed. The DbInterceptor simply adds a space (" ") to the end of the command text to illustrate the issue. If I profile the SQL, the stored procedure is successfully executed, but the exception is thrown after that, e.g. exec [dbo].[TestProc]  

[DbInterceptorBug.zip](https://github.com/aspnet/EntityFramework6/files/2605788/DbInterceptorBug.zip)

To use the sample, create a stored procedure called TestProc without any parameters.

### Further technical details
EF version: 6.2
Database Provider:  EntityFramework.SqlServer
Operating system:  Windows 10
IDE:  Visual Studio 2017 15.9

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
