### ISSUE TITLE
Can't use HierarchyId when creating ADO .NET Entity Model

### ISSUE THREAD

**Issue by gotestrand** [dotnet/ef6#668]
I am using the latest prerelease nuget package for EntityFramework (6.3.0-beta1-62230). From what I can read and find i the source code, there should now be support for HierarchyId. 

When generating an EntityModel and trying to import a table with HierarchyId I get the error
```
Error 6005: The data type 'hierarchyid' is currently not supported for the target Entity Framework version
```

The Entity Type is not showing in design mode when trying to manually set a column. 

In my package config...
```
<packages>
  <package id="EntityFramework" version="6.3.0-beta1-62230" targetFramework="net461" />
  <package id="Microsoft.SqlServer.Types" version="14.0.1016.290" targetFramework="net461" />
</packages>
```

### Steps to reproduce
- Create new project .NET Class Library Project
- Install EntityFramework (6.3.0-beta1-62230)
- Create a new item ADO.NET Entity Model
- Update model from database, database first. Include a table with HierarchyId as type for one column.

**Comment by emjiowen** [comment]
This bug is still in the latest 6.3.0 release.

I'm surprised that one of the major new features in EF 6.3.0 simply doesn't work when using an .edmx (ADO.NET Entity Data Model). 

Are .edmx files just no longer supported...?

**Comment by 1234567abcdefg** [comment]
I have the same concern. we need the mapping feature for HierarchyId in EF for our project!!!

**Comment by nfgodfather** [comment]
Also since EF 6.3 is supported on .NET Core now, will the EFCore tools be able to Scaffold HierarchyId types?

**Comment by ardennext99** [comment]
I've installed the 6.4, and error is still present. I've to start a new project and hierarchyid can improve my work, but at this moment i've not found any solution to use it.
hierarchyid should be supported since 6.3, but it' not.
Please fix it.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
