### ISSUE TITLE
Setting a FK  to an entity not in memory causes DetectChangesInForeignKeys() to throw a NullReferenceException

### ISSUE THREAD

**Issue by aslotte** [dotnet/ef6#706]
We have a one-to-many relationship set up (unidirectional)

When we attempt to only change the foreign-key on the entity, thus leaving the virtual navigation property unchanged, and thereafter call any EF method that triggers DetectChanges, EF will throw a NullReferenceException.

The specific NullReferenceException occurs in RelatedEnd.GetOtherEndOfrelationship, line 2658 as the RelationshipManager is null.

The issue appears to stem directly from the ObjectStateManager.TryGetEntityEntry method which appears to only load objects from it's cache of unmodified, changed or deleted objects. ~~If it cannot find the entity, it wraps the entity in a NullEntityWrapper which exposes a null RelationshipManager.~~

**Update**: The EntityEntry, which we want to reference, appears in the _unmodified dictionary (most likely added there by a previous call, but the WrapperEntity is of type NullEntityWrapper, which causes the issue down the line. 

Questions: 
1. When does it create a NullEntityWrapper?
2. Wouldn't it make sense to attempt to fetch the object directly from the database if it cannot be located in the cache?

```
Exception message:
Stack trace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.Core.Objects.EntityEntry.DetectChangesInForeignKeys()
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChangesInForeignKeys(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
```

### Steps to reproduce
```
    public class Parent
    {
        public int ParentId { get; set; }

        public int StatusId { get; set; }

        public virtual Status Status { get; set; }
    }

    public class Status
    {
        public int StatusId { get; set; }

        public string Code { get; set; }

        public string Description { get; set; }
    }

    public static Main()
    {
        var parent = this.dbContext.Get<Parent>(x => x.Id == 1);
        parent.StatusId = (int)Status.History;

        dbContext.Save();    
    }
```

We currently are mapping this FK as:
```
this.HasRequired(t => t.Status).WithMany().HasForeignKey(x => x.StatusId);
```

### Further technical details
EF version: 6.2.0
Database Provider:  EntityFramework.SqlServer)
Operating system: Windows 10
IDE: Visual Studio 2017 15.6

**Comment by johnpage-agixis** [comment]
Weirdly, this is a pattern that I use very often, and it mostly works.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
