### ISSUE TITLE
Specifying Source: 0 creates broken HistoryContext (which is passed to Interceptors)

### ISSUE THREAD

**Issue by worthy7** [dotnet/ef6#790]
https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EntityFramework/Migrations/Infrastructure/MigratorScriptingDecorator.cs#L83

I've spent a good week on this issue which stemmed from me simply trying to write up some documentation for a project, to discovering this very annoying bug when trying to generate a script which starts from `$initialDatabase` when using a different schema name.

The conclusion of which, is that the code referenced, initializes and uses a `HistoryContext` whose `schemaName` is `dbo` when specifying `SourceMigration: 0`.
This in turn creates a faulty `HistoryContext`, which in turn triggers any `DbCommandTreeDispatchers` with this broken `HistoryContext`

This does not happen I generate a script from any other `sourceMigration`
Why is starting from `SourceMigration:0` different from `SourceMigration:1`?

I have a test project set up demonstrating the bug.
https://github.com/Worthy7/EfHistorySourceZeroMigrationBug

Check out the unit tests

**Comment by Worthy7** [comment]
Just want to emphasize that this doesn't cause the generated scripts to use dbo at all.

**Comment by worthy7** [comment]
@ajcvickers Any news on this?

**Comment by worthy7** [comment]
The true source of the bug is that the default `HistoryContext` is not using any user set `ContextKey` as it's `defaultSchema`.

I added this to the Configuration and it works:
`

            ContextKey = "NotDbo";
            this.SetHistoryContextFactory("System.Data.SqlClient",
                    (connection, defaultSchema) => new System.Data.Entity.Migrations.History.HistoryContext(connection, this.ContextKey));
`

Note I'm passing in `this.ContextKey` instead of letting it use the `defaultSchema`.

What should happen is EF should be using the `ContextKey` as the `defaultSchema` right?

**Comment by worthy7** [comment]
Sorry ignore my previous post, I was thinking that ContextKey == SchemaName and it isn't.

So the issue is related to the use of `modelBuilder.HasDefaultSchema("NotDbo");` and how this is not passed on to the default history context.

**Comment by worthy7** [comment]
Hello 2021, we are working on our project )EF6 + Oracle) and again I am running into this issue because I am unable to create a SQL script that will create a database from scratch, because I cannot specify `$initialDatabase`

Since it seems I am literally the only person trying to do this, I would appreciate any kind of workaround, thanks.

**Comment by worthy7** [comment]
This is still an issue.

**Comment by worthy7** [comment]
I dug deeper on this issue, and it seems that the HistoryContext created in this case, has some other issues like it cannot do an `SqlQuery`, it causes an exception.

This broken `HistoryContext` created just for this purpose really needs to either be initialized properly per the related context, or have its interceptors all disabled so it is not passed into any application code.

**Comment by worthy7** [comment]
I just want to extend this to say that the context being passed into interceptors, has a connectionstate of "closed" and this is actually the source of the problem. (not the schema name, but that is likely not great too)

Should EF be passing in a closed connection context to interceptors?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
