### ISSUE TITLE
DateTime type comparison issue

### ISSUE THREAD

**Issue by koalagon** [dotnet/ef6#804]
Our DB system has Datetime data type in all tables because EF code first generates Datetime data type as default (NOT Datetime2). If I want to filter the data based on the Datetime, EF generates a query converting the Datetime input to Datetime2 type.
For example,
```
var dt = new DateTime(2019, 4, 29, 18, 55, 8, 453);
var coursesCnt = dbContext.Courses.Count(s => s.DateEdited > dt);

Above code generates this query. This query is captured by SQL profiler.
exec sp_executesql N'SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Courses] AS [Extent1]
        WHERE [Extent1].[DateEdited] > @p__linq__0
    )  AS [GroupBy1]',N'@p__linq__0 datetime2(7)',@p__linq__0='2019-04-29 18:55:08.4530000'
```
DB has the `2019-04-29 18:55:08.453` value in Datetime column.
I expect nothing should be returned, but EF returns count 1. This is caused by different data type conversion. If the DB column type is datetime, it should convert the value to datetime, not datetime2.

### Steps to reproduce
Make sure that your DB is SQL sever 13 version(2016). When I ran these queries, I expected nothing returned. But actually 1) & 2) return record.
```
CREATE TABLE DateTimePrecision 
(Id uniqueidentifier,
DateEdited Datetime)

INSERT INTO DateTimePrecision VALUES (newid(), '2019-04-29 18:55:08.453')

select top 1000 * from DateTimePrecision where DateEdited > cast('2019-04-29 18:55:08.4530000' as datetime2(7))
select top 1000 * from DateTimePrecision where DateEdited > cast('2019-04-29 18:55:08.453' as datetime2(7))
select top 1000 * from DateTimePrecision where DateEdited > cast('2019-04-29 18:55:08.453' as datetime)
```

I found this article. http://www.dbdelta.com/sql-server-2016-and-azure-sql-database-v12-breaking-change
For proper filtering, EF should handle this datetime convert scenario.

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017
DB: SQL Server v13

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
