### ISSUE TITLE
Rollback throws error on failed ExecuteSqlCommand

### ISSUE THREAD

**Issue by qbunia** [dotnet/ef6#867]
When I `ExecuteSqlCommand` query that creates table and it fails then I want to rollback anything that happened before like modifying entities or any other `ExecuteSqlCommands`. Rollback fails in this case.

```
Exception message: The underlying provider failed on Rollback.
Stack trace:
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
   at System.Data.Entity.DbContextTransaction.Rollback()
   at ConsoleApp3.Program.Main(String[] args) in C:\Users\Qbusoft\Documents\Visual Studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 33

Inner exception message : Value cannot be null. Parameter name: connection
Stack trace:
   at System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext.WithConnection(DbConnection connection)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Rollback(DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
```

### Steps to reproduce
I attached solution to reproduce the error:
https://ufile.io/7hj2yuc0

Code to reproduce:
```c#
var context = new DataContext();

using (var transaction = context.Database.BeginTransaction())
{
	try
	{
		context.Database.ExecuteSqlCommand(@"create table [form].[Pat]
		(
			FormItemId int not null identity primary key)
		");

		context.Database.ExecuteSqlCommand(@"create table [form].[Pat]
		(
			FormItemId int not null identity primary key)
		");
	}
	catch (Exception e)
	{
		transaction.Rollback();
		throw;
	}
}
```

### Further technical details
EF version: 6.1.3
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.11

**Comment by ajcvickers** [comment]
@qbunia I am unable to access the repro code. Can you post it again, preferably somewhere it won't expire.

**Comment by qbunia** [comment]
@ajcvickers 
Sorry I dont have option to host endlessly. I updated link its available till 26.07.19

**Comment by ajcvickers** [comment]
@qbunia I'm still not able to access it. Can you just post it on here? Or put it in a GitHub repro? (That's what people normally do.)

**Comment by qbunia** [comment]
There you go
[ConsoleApp3.zip](https://github.com/aspnet/EntityFramework6/files/3340165/ConsoleApp3.zip)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
