### ISSUE TITLE
Update VS Tools to work with SDK-style projects

### ISSUE THREAD

**Issue by bricelam** [dotnet/ef6#883]
Breaking this out from #231 since it’s tied to VS releases, not .NET Core releases.

We’ll need to update the designer to work with the CPS-based project system used by SDK-style csproj (and vbproj) files.

**Comment by bricelam** [comment]
*@divega said in #189*:

Currently we use NuGet packages (entityframework.codetemplates.csharp and entityframework.codetemplates.visualbasic) to distribute customizable versions of the T4 templates for the "code first from an existing database" option in the EF6 designer. We would need to have alternative ways to distribute them, e.g. add them as item templates in the designer's setup, or point customers to the code in docs, github, etc.

**Comment by ErikEJ** [comment]
Could EF 6 Power Tools help here??

**Comment by divega** [comment]
@bricelam can you remind me (once more) what is the reason the T4 templates as VSIX wouldn't work anymore?

**Comment by bricelam** [comment]
We could distribute them as a VSIX, but I’d just make them part of the main installer if we did that. (Or part of the power tools if we think it’s too corner-case to add in the main package)

I don’t think an item template (File > Add new item) isn’t a good fit because they need to go in a specific directory. On the other hand I doubt we can add a new item in the project right-click menu...

**Comment by bricelam** [comment]
...but Erik can. 😉

**Comment by husseinraoouf** [comment]
will this be implement soon or i should expect a long time 
ef 6.3 is already released for more than month now and this is an important issue for any one want to use 6.3 release

**Comment by Flem100** [comment]
Just to be clear, this is the place to if I want to follow the progress of getting EF 6.3 in a core project, to work with EDMX files? Any ETA? This is the only thing left, keeping us from going forward with our Blazor serverside project. :). I know there are workarounds, but we can wait for the real deal, if it's not too long ;).

**Comment by ajcvickers** [comment]
@Flem100 This is not planned for anytime soon. Instead, follow the documentation here: https://docs.microsoft.com/en-us/ef/ef6/what-is-new/#ef-designer-support

**Comment by Flem100** [comment]
@ajcvickers Thank you for that information! :)

**Comment by fretje** [comment]
Not sure if this is the right issue to report this, but I have an problem with the ef6 commands after updating my MVC5 web-project to the new SDK style project, following the instructions [here](https://github.com/dotnet/project-system/issues/2670#issuecomment-740837305).

Everything works, except that the tools look for app.config in stead of web.config because the [IsWeb method in EntityFramework6.psm1](https://github.com/dotnet/ef6/blob/master/src/EntityFramework.NuGet/tools/EntityFramework6.psm1#L1001) doesn't take this scenario into account.

So I can work around it by creating an app.config file with the connectionstring information, but it would be nice if that wouldn't be necessary.

**Comment by bricelam** [comment]
@fretje That seems unrelated. Can you submit a new issue?

**Comment by agilenut** [comment]
We have a project that is using EF 6.4.4 with Database-First (EDMX files). 

We converted the project to SDK-style and are targeting net48. We are able to use the "Update Models from Database..." option and save the EDMX file. This correctly updates the EDMX file but does not run the T4 templates. Previously, before the SDK-style update, it did run the T4 templates automatically.

We are able to manually run the T4 templates after updating the EDMX file but would prefer for it to run them automatically as it did in non-SDK-style projects.

Is this issue going to address this or should this be a separate issue?
