### ISSUE TITLE
Consider adding a central API for EF 6 providers to resolve what ADO.NET provider to use by default

### ISSUE THREAD

**Issue by divega** [dotnet/ef6#920]
An EF provider normally uses DbProviderFactories to resolve what ADO.NET provider to use. But in platforms different form .NET Framework like .NET Core, DbProviderFactories is usually empty. 

In https://github.com/aspnet/EntityFramework6/pull/849/ we added fallback resolution logic in a couple of places so that System.Data.SqlClientFactory can be resolved even if the registration doesn't exist. 

I am proposing that we add a virtual method in either DbProviderServices or DbProviderManifest so that each provider can implement its own fallback logic.

cc @bricelam @ajcvickers

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
