### ISSUE TITLE
Update-Database OutOfMemoryException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#965]
Launching the command Update-Database -force -script from the Package Manager Console throws OutOfMemoryException (in the project there are something like 200 migrations). Everything works after a restart of Visual Studio 2017

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/617148/update-database-outofmemoryexception.html
VSTS ticketId: 935583_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 02:40 AM (7 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 6/24/2019, 08:05 PM (6 days ago): <markdown><p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
Are you using EF Core or EF6, and which version?

**Comment by amoroso81** [comment]
EF 6.2

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by PilotBob** [comment]
@ajcvickers  We are getting this scripting as well. 

EF 6.x is still supported though, right?

Even though you aren't making changes, is there any guidance you can provide to lower the memory usage when scripting? Or perhaps point to the source code and the community can perhaps look into modifying this. There are several issues with the scripting I would like to enhance/resolve in addition to this.

Are you accepting/reviewing pull requests?

**Comment by ErikEJ** [comment]
Use DbMigrator from a 64 bit app? 

https://stackoverflow.com/questions/9701781/how-do-i-use-migratorscriptingdecorator-in-entity-framework-code-first

**Comment by PilotBob** [comment]
@ErikEJ  Hi, thanks for your response. But, I'm not sure how this is relevant to using the ef6.exe tool shipped with the EF6 Framework nuget package? Is there a way to force ef6.exe to run as 64-bit?

**Comment by ErikEJ** [comment]
I meant create you own 64 bit tool.

**Comment by ajcvickers** [comment]
@PilotBob The repo [README](https://github.com/dotnet/ef6/blob/main/README.md) should answer your questions. 

> EF 6.x is still supported though, right?

Yes. As the readme says, you can contact Microsoft support about EF6, and we are still shipping security updates.

> Even though you aren't making changes, is there any guidance you can provide to lower the memory usage when scripting?

No; the team is focusing their efforts on EF Core. The readme contains other options for getting help.

> Are you accepting/reviewing pull requests?

No; we are focusing on stability. As the readme indicates, you may wish to fork the code.
